### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by jimrrchen** [Epix37/Hearthstone-Deck-Tracker#1019]
After an arena game is finished, the tracker crashed. When I tried to open it again, it immediately crashed on start

Here are the contents of the crash on start. The first crash dump (the one after arena game) is sent to your gmail since it is huge

########## 6/2/2015 10:21:21 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.HandleGoldReward(Int32 amount)
   at Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   at Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 6/2/2015 10:21:36 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.HandleGoldReward(Int32 amount)
   at Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   at Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Just released v0.10.3, should be fixed with that.

(Restarting hearthstone will fix the crash temporarily)
