### ISSUE TITLE
New game begins with chat window open

### ISSUE THREAD

**Issue by justintout** [Epix37/Hearthstone-Deck-Tracker#1039]
1) Get in quete
2) Open chat window to friend 
3) Get selected for a game with chat window open
4) Opponent conceded before first turn with chat window open 
Causes crash

CRASH REPORTS BELOW, seemingly irrelevant data deleted
########## 6/6/2015 2:36:52 AM ##########

[2:27:59 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:27:59 AM] OpponentSecrets: Cleared secrets
[2:28:00 AM] UpdateOverlay: Refreshed overlay topmost status
[2:28:01 AM] Game: set CurrentGameMode to Casual
[2:28:13 AM] UpdateOverlay: Refreshed overlay topmost status
[2:28:18 AM] GameEventHandler: Game start
[2:28:18 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:28:18 AM] OpponentSecrets: Cleared secrets
[2:28:18 AM] Game: set CurrentGameMode to None
[2:28:18 AM] GameEventHandler: Opponent-turn (1)
[2:28:18 AM] GameEventHandler: PlayerDraw (id:NEW1_019 turn:0 from:-1)
[2:28:18 AM] GameStats: New play: PlayerDraw (NEW1_019, turn: 0)
[2:28:18 AM] GameEventHandler: PlayerDraw (id:FP1_002 turn:0 from:-1)
[2:28:18 AM] GameStats: New play: PlayerDraw (FP1_002, turn: 0)
[2:28:18 AM] GameEventHandler: PlayerDraw (id:FP1_002 turn:0 from:-1)
[2:28:18 AM] GameStats: New play: PlayerDraw (FP1_002, turn: 0)
[2:28:18 AM] GameEventHandler: PlayerDraw (id:CS2_203 turn:0 from:-1)
[2:28:18 AM] GameStats: New play: PlayerDraw (CS2_203, turn: 0)
[2:28:18 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:28:18 AM] Hearthstone: Set card 0 to age 0
[2:28:18 AM] Hearthstone: Opponent Hand after draw: 0K,  ,  ,  ,0C,  ,  ,  ,  ,  
[2:28:18 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:28:18 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:28:18 AM] Hearthstone: Set card 1 to age 0
[2:28:18 AM] Hearthstone: Opponent Hand after draw: 0K,0K,  ,  ,0C,  ,  ,  ,  ,  
[2:28:18 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:28:18 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:28:18 AM] Hearthstone: Set card 2 to age 0
[2:28:18 AM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,  ,0C,  ,  ,  ,  ,  
[2:28:18 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:28:18 AM] GameEventHandler: PlayerGet (id:GAME_005 turn:0 from:-1)
[2:28:18 AM] Hearthstone: Player got the coin
[2:28:18 AM] GameStats: Got coin
[2:28:18 AM] GameStats: New play: PlayerGet (GAME_005, turn: 0)
[2:28:18 AM] GameEventHandler: Playing against Hunter
[2:28:24 AM] GameEventHandler: set rank to 15
[2:28:40 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:28:40 AM] Hearthstone: Set card 3 to age 0
[2:28:40 AM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,0K,  ,  ,  ,  ,  ,  
[2:28:40 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:28:40 AM] GameEventHandler: OpponentMulligan (id: turn:0 from:2)
[2:28:40 AM] Hearthstone: Fixed hand ages after mulligan (removed 3)
[2:28:40 AM] Hearthstone: Opponent Hand after draw: 0K,0M,0K, K,  ,  ,  ,  ,  ,  
[2:28:40 AM] GameStats: New play: OpponentMulligan (, turn: 0)
[2:28:40 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:28:40 AM] Hearthstone: Set card 3 to age 0
[2:28:40 AM] Hearthstone: Opponent Hand after draw: 0K,0M,0K,0K,  ,  ,  ,  ,  ,  
[2:28:40 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:28:40 AM] GameEventHandler: OpponentMulligan (id: turn:0 from:3)
[2:28:40 AM] Hearthstone: Fixed hand ages after mulligan (removed 3)
[2:28:40 AM] Hearthstone: Opponent Hand after draw: 0K,0M,0M, K,  ,  ,  ,  ,  ,  
[2:28:40 AM] GameStats: New play: OpponentMulligan (, turn: 0)
[2:29:33 AM] GameEventHandler: OpponentDraw (id: turn:1 from:-1)
[2:29:33 AM] Hearthstone: Set card 3 to age 1
[2:29:33 AM] Hearthstone: Opponent Hand after draw: 0K,0M,0M,1 ,  ,  ,  ,  ,  ,  
[2:29:33 AM] GameStats: New play: OpponentDraw (, turn: 1)
[2:30:08 AM] UpdateOverlay: Refreshed overlay topmost status
[2:30:35 AM] UpdateOverlay: Refreshed overlay topmost status
[2:30:48 AM] GameEventHandler: Player-turn (2)
[2:30:48 AM] GameEventHandler: PlayerDraw (id:NEW1_031 turn:0 from:-1)
[2:30:48 AM] GameStats: New play: PlayerDraw (NEW1_031, turn: 1)
[2:31:00 AM] GameEventHandler: PlayerPlay (id:GAME_005 turn:0 from:-1)
[2:31:00 AM] GameStats: New play: PlayerPlay (GAME_005, turn: 1)
[2:31:02 AM] GameEventHandler: PlayerPlay (id:NEW1_019 turn:0 from:-1)
[2:31:02 AM] GameStats: New play: PlayerPlay (NEW1_019, turn: 1)
[2:31:03 AM] GameEventHandler: Opponent-turn (2)
[2:31:03 AM] GameEventHandler: OpponentDraw (id: turn:2 from:-1)
[2:31:03 AM] Hearthstone: Set card 4 to age 2
[2:31:03 AM] Hearthstone: Opponent Hand after draw: 0K,0M,0M,1 ,2 ,  ,  ,  ,  ,  
[2:31:03 AM] GameStats: New play: OpponentDraw (, turn: 2)
[2:31:19 AM] GameEventHandler: OpponentPlay (id:FP1_004 turn:2 from:1)
[2:31:19 AM] Hearthstone: (opponent deck) Mad Scientist count 0 -> 1
[2:31:19 AM] Hearthstone: Opponent Hand after draw: 0M,0M,1 ,2 ,  ,  ,  ,  ,  ,  
[2:31:19 AM] GameStats: New play: OpponentPlay (FP1_004, turn: 2)
[2:31:20 AM] GameEventHandler: Player-turn (3)
[2:31:20 AM] GameEventHandler: PlayerDraw (id:EX1_611 turn:0 from:-1)
[2:31:20 AM] GameStats: New play: PlayerDraw (EX1_611, turn: 2)
[2:31:27 AM] GameEventHandler: PlayerPlay (id:FP1_002 turn:0 from:-1)
[2:31:27 AM] GameStats: New play: PlayerPlay (FP1_002, turn: 2)
[2:31:29 AM] GameEventHandler: Opponent-turn (3)
[2:31:29 AM] GameEventHandler: OpponentDraw (id: turn:3 from:-1)
[2:31:29 AM] Hearthstone: Set card 4 to age 3
[2:31:29 AM] Hearthstone: Opponent Hand after draw: 0M,0M,1 ,2 ,3 ,  ,  ,  ,  ,  
[2:31:29 AM] GameStats: New play: OpponentDraw (, turn: 3)
[2:31:43 AM] GameEventHandler: OpponentSecretPlayed (id: turn:0 from:-1)
[2:31:43 AM] GameStats: New play: OpponentSecretPlayed (, turn: 3)
[2:31:43 AM] OpponentSecrets: Added secret with id:42
[2:32:01 AM] GameEventHandler: OpponentPlay (id:EX1_531 turn:3 from:5)
[2:32:01 AM] Hearthstone: (opponent deck) Scavenging Hyena count 0 -> 1
[2:32:01 AM] Hearthstone: Opponent Hand after draw: 0M,0M,1 ,2 ,  ,  ,  ,  ,  ,  
[2:32:01 AM] GameStats: New play: OpponentPlay (EX1_531, turn: 3)
[2:32:02 AM] GameEventHandler: OpponentPlay (id:FP1_011 turn:3 from:4)
[2:32:02 AM] Hearthstone: (opponent deck) Webspinner count 0 -> 1
[2:32:02 AM] Hearthstone: Opponent Hand after draw: 0M,0M,1 ,  ,  ,  ,  ,  ,  ,  
[2:32:02 AM] GameStats: New play: OpponentPlay (FP1_011, turn: 3)
[2:32:04 AM] GameEventHandler: Player-turn (4)
[2:32:04 AM] GameEventHandler: PlayerDraw (id:EX1_534 turn:0 from:-1)
[2:32:04 AM] GameStats: New play: PlayerDraw (EX1_534, turn: 3)
[2:32:35 AM] GameEventHandler: PlayerPlay (id:NEW1_031 turn:0 from:-1)
[2:32:35 AM] GameStats: New play: PlayerPlay (NEW1_031, turn: 3)
[2:32:39 AM] GameEventHandler: OpponentSecretTrigger (id:EX1_610 turn:0 from:-1)
[2:32:39 AM] Hearthstone: (opponent deck) Explosive Trap count 0 -> 1
[2:32:39 AM] OpponentSecrets: Removed secret with id:42
[2:32:39 AM] GameStats: New play: OpponentSecretTriggered (EX1_610, turn: 3)
[2:32:47 AM] GameEventHandler: Opponent-turn (4)
[2:32:47 AM] GameEventHandler: OpponentDraw (id: turn:4 from:-1)
[2:32:47 AM] Hearthstone: Set card 3 to age 4
[2:32:47 AM] Hearthstone: Opponent Hand after draw: 0M,0M,1 ,4 ,  ,  ,  ,  ,  ,  
[2:32:47 AM] GameStats: New play: OpponentDraw (, turn: 4)
[2:32:54 AM] GameEventHandler: OpponentPlay (id:NEW1_019 turn:4 from:3)
[2:32:54 AM] Hearthstone: (opponent deck) Knife Juggler count 0 -> 1
[2:32:54 AM] Hearthstone: Opponent Hand after draw: 0M,0M,4 ,  ,  ,  ,  ,  ,  ,  
[2:32:54 AM] GameStats: New play: OpponentPlay (NEW1_019, turn: 4)
[2:32:56 AM] GameEventHandler: OpponentGet (id: turn:4 from:-1)
[2:32:56 AM] Hearthstone: Opponent Hand after draw: 0M,0M,4 ,4S,  ,  ,  ,  ,  ,  
[2:32:56 AM] GameStats: New play: OpponentGet (, turn: 4)
[2:33:01 AM] GameEventHandler: OpponentSecretPlayed (id: turn:0 from:-1)
[2:33:01 AM] Hearthstone: Opponent Hand after draw: 0M,4 ,4S,  ,  ,  ,  ,  ,  ,  
[2:33:01 AM] GameStats: New play: OpponentSecretPlayed (, turn: 4)
[2:33:01 AM] OpponentSecrets: Added secret with id:47
[2:33:05 AM] GameEventHandler: Player-turn (5)
[2:33:05 AM] GameEventHandler: PlayerDraw (id:EX1_089 turn:0 from:-1)
[2:33:05 AM] GameStats: New play: PlayerDraw (EX1_089, turn: 4)
[2:33:49 AM] UpdateOverlay: Refreshed overlay topmost status
[2:33:51 AM] GameEventHandler: PlayerPlay (id:CS2_203 turn:0 from:-1)
[2:33:51 AM] GameStats: New play: PlayerPlay (CS2_203, turn: 4)
[2:33:57 AM] GameEventHandler: PlayerPlay (id:FP1_002 turn:0 from:-1)
[2:33:57 AM] GameStats: New play: PlayerPlay (FP1_002, turn: 4)
[2:33:58 AM] GameEventHandler: Opponent-turn (5)
[2:33:58 AM] GameEventHandler: OpponentDraw (id: turn:5 from:-1)
[2:33:58 AM] Hearthstone: Set card 3 to age 5
[2:33:58 AM] Hearthstone: Opponent Hand after draw: 0M,4 ,4S,5 ,  ,  ,  ,  ,  ,  
[2:33:58 AM] GameStats: New play: OpponentDraw (, turn: 5)
[2:34:01 AM] UpdateOverlay: Refreshed overlay topmost status
[2:34:16 AM] GameEventHandler: OpponentPlay (id:EX1_531 turn:5 from:2)
[2:34:16 AM] Hearthstone: (opponent deck) Scavenging Hyena count 1 -> 2
[2:34:16 AM] Hearthstone: Opponent Hand after draw: 0M,4S,5 ,  ,  ,  ,  ,  ,  ,  
[2:34:16 AM] GameStats: New play: OpponentPlay (EX1_531, turn: 5)
[2:34:21 AM] GameEventHandler: OpponentPlay (id:DS1_175 turn:5 from:1)
[2:34:21 AM] Hearthstone: (opponent deck) Timber Wolf count 0 -> 1
[2:34:21 AM] Hearthstone: Opponent Hand after draw: 4S,5 ,  ,  ,  ,  ,  ,  ,  ,  
[2:34:21 AM] GameStats: New play: OpponentPlay (DS1_175, turn: 5)
[2:34:28 AM] GameEventHandler: Player-turn (6)
[2:34:28 AM] GameEventHandler: PlayerDraw (id:GVG_043 turn:0 from:-1)
[2:34:28 AM] GameStats: New play: PlayerDraw (GVG_043, turn: 5)
[2:34:55 AM] GameEventHandler: PlayerPlay (id:GVG_043 turn:0 from:-1)
[2:34:55 AM] GameStats: New play: PlayerPlay (GVG_043, turn: 5)
[2:35:00 AM] GameEventHandler: PlayerSecretPlayed (id:EX1_611 turn:0 from:-1)
[2:35:00 AM] GameStats: New play: PlayerSecretPlayed (EX1_611, turn: 5)
[2:35:03 AM] GameEventHandler: OpponentSecretTrigger (id:EX1_554 turn:0 from:-1)
[2:35:03 AM] Hearthstone: (opponent deck) Snake Trap count 0 -> 1
[2:35:03 AM] OpponentSecrets: Removed secret with id:47
[2:35:03 AM] GameStats: New play: OpponentSecretTriggered (EX1_554, turn: 5)
[2:35:27 AM] GameEventHandler: Opponent-turn (6)
[2:35:27 AM] GameEventHandler: OpponentDraw (id: turn:6 from:-1)
[2:35:27 AM] Hearthstone: Set card 2 to age 6
[2:35:27 AM] Hearthstone: Opponent Hand after draw: 4S,5 ,6 ,  ,  ,  ,  ,  ,  ,  
[2:35:27 AM] GameStats: New play: OpponentDraw (, turn: 6)
[2:35:34 AM] GameEventHandler: OpponentBackToHand (id:EX1_554t turn:6 from:-1)
[2:35:34 AM] GameStats: New play: OpponentBackToHand (EX1_554t, turn: 6)
[2:35:44 AM] GameEventHandler: OpponentPlay (id:EX1_534 turn:6 from:3)
[2:35:44 AM] Hearthstone: (opponent deck) Savannah Highmane count 0 -> 1
[2:35:44 AM] Hearthstone: Opponent Hand after draw: 4S,5 ,6R,  ,  ,  ,  ,  ,  ,  
[2:35:44 AM] GameStats: New play: OpponentPlay (EX1_534, turn: 6)
[2:35:53 AM] GameEventHandler: Player-turn (7)
[2:35:53 AM] GameEventHandler: PlayerDraw (id:EX1_539 turn:0 from:-1)
[2:35:53 AM] GameStats: New play: PlayerDraw (EX1_539, turn: 6)
[2:35:58 AM] GameEventHandler: PlayerPlay (id:EX1_089 turn:0 from:-1)
[2:35:58 AM] GameStats: New play: PlayerPlay (EX1_089, turn: 6)
[2:36:02 AM] GameEventHandler: PlayerHeroPower (id:DS1h_292 turn:6 from:-1)
[2:36:02 AM] GameStats: New play: PlayerHeroPower (DS1h_292, turn: 6)
[2:36:03 AM] GameEventHandler: Game was lost!
[2:36:03 AM] Gamestats: Current Game ended after 6 turns
[2:36:03 AM] GameStats: Assigned current deck to default Hunter deck.
[2:36:11 AM] UpdateOverlay: Refreshed overlay topmost status
[2:36:16 AM] Game: set CurrentGameMode to Casual
[2:36:16 AM] GameEventHandler: Set CurrentGameStats.GameMode to Casual
[2:36:16 AM] GameEventHandler: Saving DefaultDeckStats
[2:36:17 AM] LogReader: Cleared log file
[2:36:39 AM] GameEventHandler: Game start
[2:36:39 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:36:39 AM] OpponentSecrets: Cleared secrets
[2:36:39 AM] Game: set CurrentGameMode to None
[2:36:39 AM] GameEventHandler: Opponent-turn (1)
[2:36:39 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:36:39 AM] Hearthstone: Set card 0 to age 0
[2:36:39 AM] Hearthstone: Opponent Hand after draw: 0K,  ,  ,  ,0C,  ,  ,  ,  ,  
[2:36:39 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:36:39 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:36:39 AM] Hearthstone: Set card 1 to age 0
[2:36:39 AM] Hearthstone: Opponent Hand after draw: 0K,0K,  ,  ,0C,  ,  ,  ,  ,  
[2:36:39 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:36:39 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:36:39 AM] Hearthstone: Set card 2 to age 0
[2:36:39 AM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,  ,0C,  ,  ,  ,  ,  
[2:36:39 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:36:39 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:36:39 AM] Hearthstone: Set card 3 to age 0
[2:36:39 AM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,0K,0C,  ,  ,  ,  ,  
[2:36:39 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:36:39 AM] GameEventHandler: PlayerDraw (id:EX1_539 turn:0 from:-1)
[2:36:39 AM] GameStats: New play: PlayerDraw (EX1_539, turn: 0)
[2:36:39 AM] GameEventHandler: PlayerDraw (id:EX1_536 turn:0 from:-1)
[2:36:39 AM] GameStats: New play: PlayerDraw (EX1_536, turn: 0)
[2:36:39 AM] GameEventHandler: PlayerDraw (id:NEW1_019 turn:0 from:-1)
[2:36:39 AM] GameStats: New play: PlayerDraw (NEW1_019, turn: 0)
[2:36:39 AM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[2:36:39 AM] GameStats: New play: OpponentDraw (, turn: 0)
[2:36:39 AM] GameEventHandler: Playing against Mage
[2:36:44 AM] GameEventHandler: set rank to 15
[2:36:51 AM] GameEventHandler: Game was won!
[2:36:51 AM] Gamestats: Current Game ended after 0 turns
[2:36:51 AM] GameStats: Assigned current deck to default Hunter deck.

########## 6/6/2015 2:37:03 AM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.HandleGoldReward(Int32 amount)
   at Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   at Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
You actually deleted the most important part of the log :(. (Please always post the full log, upload it somewhere if it's too big)

What version of HDT are you using? v0.10.3 fixes this crash.

**Comment by justintout** [comment]
10.2

Was just about to expand on what got deleted and more background. Upgrading now and trying to reproduce.
