### ISSUE TITLE
Crah after changing the language

### ISSUE THREAD

**Issue by antoinejoerg** [Epix37/Hearthstone-Deck-Tracker#1104]
I changed the language from English to French and then I clicked on "Restart HDT".

########## 18/06/2015 12:02:55 ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.MainWindow.Restart()
   at Hearthstone_Deck_Tracker.FlyoutControls.Options.Tracker.TrackerAppearance.ButtonRestart_OnClick(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[12:01:54] ConvertLegacyConfig: changed config values
[12:01:54] UpdateLogConfig: Added Zone to log.config.
[12:01:54] UpdateLogConfig: Added Bob to log.config.
[12:01:54] UpdateLogConfig: Added Power to log.config.
[12:01:54] UpdateLogConfig: Added Asset to log.config.
[12:01:54] UpdateLogConfig: Added Rachelle to log.config.
[12:01:54] Game: set CurrentGameMode to None
[12:01:54] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:01:54] OpponentSecrets: Cleared secrets
[12:01:54] Tracker: set player item source to PlayerDrawn
[12:01:54] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:01:54] OpponentSecrets: Cleared secrets
[12:01:54] GameEventHandler: Reset constructed importing
[12:01:54] Helper: Checking for LIVE updates...
[12:01:54] Helper: Current version: 0.10.6.0
[12:01:55] LogReader: Current region: EU
[12:01:55] UpdateOverlay: Refreshed overlay topmost status
[12:01:55] BackupManager: Running BackupManager
[12:01:55] BackupManager: Creating backup for today
[12:01:56] PluginManager: Loading Plugins...
[12:01:57] Helper: Latest LIVE version: 0.10.6.0
[12:02:05] UpdateOverlay: Refreshed overlay topmost status
[12:02:07] UpdateOverlayLoop: Exited game
[12:02:07] UpdateOverlayLoop: Reset region
[12:02:07] LogReader: Error cleared log file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Hearthstone_Data\output_log.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Hearthstone_Deck_Tracker.HsLogReader.ClearLog()
[12:02:07] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:02:07] OpponentSecrets: Cleared secrets
[12:02:12] UpdateOverlay: Refreshed overlay topmost status
[12:02:30] Overlay: Enabled mouse hook
[12:02:55] Overlay: Disabled mouse hook

**Comment by Epix37** [comment]
Not really sure why this happens :( (fine on my end).

Maybe someone has an idea? ([Restart method](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/MainWindow/MainWindow.xaml.cs#L1571))

**Comment by irufus** [comment]
@antoinejoerg can you reproduce the issue?

**Comment by antoinejoerg** [comment]
Absolutely,

Change the language in options->Appearance->Languages
Then click on Restart HDT...

[image: Images intégrées 1]

2015-06-25 6:46 GMT+01:00 Ishmael Rufus <notifications@github.com>:

> @antoinejoerg <https://github.com/antoinejoerg> can you reproduce the
> issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1104#issuecomment-115113627>
> .
>



-- 
Cordialement,

Antoine JOERG.

########## 25/06/2015 10:24:18 ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.MainWindow.Restart()
   at Hearthstone_Deck_Tracker.FlyoutControls.Options.Tracker.TrackerAppearance.ButtonRestart_OnClick(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[10:23:50] Game: set CurrentGameMode to None
[10:23:50] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[10:23:50] OpponentSecrets: Cleared secrets
[10:23:50] DeckList: Set active deck to: Controle (Warrior)
[10:23:50] Overlay: Enabled mouse hook
[10:23:51] Tracker: Set player itemsource as PlayerDeck
[10:23:51] Tracker: Switched to deck: Controle
[10:23:51] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[10:23:51] OpponentSecrets: Cleared secrets
[10:23:51] GameEventHandler: Reset constructed importing
[10:23:51] Helper: Checking for LIVE updates...
[10:23:51] Helper: Current version: 0.10.6.0
[10:23:52] BackupManager: Running BackupManager
[10:23:52] BackupManager: Creating backup for today
[10:23:52] PluginManager: Loading Plugins...
[10:23:54] Helper: Latest LIVE version: 0.10.6.0
[10:24:16] Overlay: Disabled mouse hook

**Comment by chucklu** [comment]
12:02:07] LogReader: Error cleared log file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Hearthstone_Data\output_log.txt'.
The path for the game is not correct
The right path Hearthstone\Hearthstone_Data\output_log.txt'
so,C:\Hearthstone_Data\output_log.txt',How could this be possible?

**Comment by andburn** [comment]
@antoinejoerg if you still have this problem:
@chucklu is right your Hearthstone path seems to be wrong. Go to `options > tracker > settings` and press *Set Hearthstone Path* point it to the Hearthstone install directory.
