### ISSUE TITLE
Deck Tracker Crashing

### ISSUE THREAD

**Issue by Incutt** [Epix37/Hearthstone-Deck-Tracker#1192]
This is my crash report: 

########## 8/1/2015 11:23:38 AM ##########
System.Runtime.InteropServices.COMException (0x88980406): Exception from HRESULT: 0x88980406
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[11:22:18 AM] Game: set CurrentGameMode to None
[11:22:18 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[11:22:18 AM] OpponentSecrets: Cleared secrets
[11:22:20 AM] Tracker: set player item source to PlayerDrawn
[11:22:20 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[11:22:20 AM] OpponentSecrets: Cleared secrets
[11:22:20 AM] GameEventHandler: Reset constructed importing
[11:22:20 AM] Helper: Checking for LIVE updates...
[11:22:20 AM] Helper: Current version: 0.10.7.0
[11:22:22 AM] LogReader: Current region: US
[11:22:22 AM] UpdateOverlay: Refreshed overlay topmost status
[11:22:22 AM] BackupManager: Running BackupManager
[11:22:22 AM] BackupManager: Backup for today already exists
[11:22:22 AM] PluginManager: Loading Plugins...
[11:22:23 AM] Helper: Latest LIVE version: 0.10.7.0
[11:22:49 AM] UpdateOverlay: Refreshed overlay topmost status
[11:23:26 AM] UpdateOverlay: Refreshed overlay topmost status
[11:23:30 AM] Game: set CurrentGameMode to Arena

########## 8/1/2015 11:23:38 AM ##########
System.Runtime.InteropServices.COMException (0x88980406): Exception from HRESULT: 0x88980406
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[11:22:18 AM] Game: set CurrentGameMode to None
[11:22:18 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[11:22:18 AM] OpponentSecrets: Cleared secrets
[11:22:20 AM] Tracker: set player item source to PlayerDrawn
[11:22:20 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[11:22:20 AM] OpponentSecrets: Cleared secrets
[11:22:20 AM] GameEventHandler: Reset constructed importing
[11:22:20 AM] Helper: Checking for LIVE updates...
[11:22:20 AM] Helper: Current version: 0.10.7.0
[11:22:22 AM] LogReader: Current region: US
[11:22:22 AM] UpdateOverlay: Refreshed overlay topmost status
[11:22:22 AM] BackupManager: Running BackupManager
[11:22:22 AM] BackupManager: Backup for today already exists
[11:22:22 AM] PluginManager: Loading Plugins...
[11:22:23 AM] Helper: Latest LIVE version: 0.10.7.0
[11:22:49 AM] UpdateOverlay: Refreshed overlay topmost status
[11:23:26 AM] UpdateOverlay: Refreshed overlay topmost status
[11:23:30 AM] Game: set CurrentGameMode to Arena

########## 8/1/2015 11:23:43 AM ##########
System.Runtime.InteropServices.COMException (0x88980406): Exception from HRESULT: 0x88980406
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[11:22:18 AM] Game: set CurrentGameMode to None
[11:22:18 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[11:22:18 AM] OpponentSecrets: Cleared secrets
[11:22:20 AM] Tracker: set player item source to PlayerDrawn
[11:22:20 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[11:22:20 AM] OpponentSecrets: Cleared secrets
[11:22:20 AM] GameEventHandler: Reset constructed importing
[11:22:20 AM] Helper: Checking for LIVE updates...
[11:22:20 AM] Helper: Current version: 0.10.7.0
[11:22:22 AM] LogReader: Current region: US
[11:22:22 AM] UpdateOverlay: Refreshed overlay topmost status
[11:22:22 AM] BackupManager: Running BackupManager
[11:22:22 AM] BackupManager: Backup for today already exists
[11:22:22 AM] PluginManager: Loading Plugins...
[11:22:23 AM] Helper: Latest LIVE version: 0.10.7.0
[11:22:49 AM] UpdateOverlay: Refreshed overlay topmost status
[11:23:26 AM] UpdateOverlay: Refreshed overlay topmost status
[11:23:30 AM] Game: set CurrentGameMode to Arena

**Comment by Epix37** [comment]
You could try reinstalling .NET 4.5 and DirectX.

**Comment by riQQ** [comment]
And try updating your video card driver.

**Comment by CompeteHS** [comment]
I am having this problem too.
