### ISSUE TITLE
Not tracking

### ISSUE THREAD

**Issue by HPGMaphax** [Epix37/Hearthstone-Deck-Tracker#1196]
Not sure why but the tracker won't import decks nor track decs in game. I tried to redirect the hearthstone path but got this error when restarting HDT:

```
########## 03-08-2015 16:51:24 ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.MainWindow.Restart()
   at Hearthstone_Deck_Tracker.FlyoutControls.Options.Tracker.TrackerSettings.ButtonRestart_OnClick(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[16:46:59] Game: set CurrentGameMode to None
[16:46:59] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[16:46:59] OpponentSecrets: Cleared secrets
[16:46:59] Tracker: set player item source to PlayerDrawn
[16:46:59] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[16:46:59] OpponentSecrets: Cleared secrets
[16:46:59] GameEventHandler: Reset constructed importing
[16:46:59] Helper: Checking for LIVE updates...
[16:46:59] Helper: Current version: 0.10.7.0
[16:46:59] LogReader: Current region: EU
[16:46:59] UpdateOverlay: Refreshed overlay topmost status
[16:46:59] BackupManager: Running BackupManager
[16:46:59] BackupManager: Backup for today already exists
[16:46:59] PluginManager: Loading Plugins...
[16:47:00] Game: set CurrentGameMode to Arena
[16:47:00] Game: set CurrentGameMode to Arena
[16:47:00] Helper: Latest LIVE version: 0.10.7.0
[16:47:32] UpdateOverlay: Refreshed overlay topmost status
[16:47:41] UpdateOverlay: Refreshed overlay topmost status
[16:47:42] GameEventHandler: Reset constructed importing
[16:48:23] UpdateOverlay: Refreshed overlay topmost status
[16:48:24] GameEventHandler: Reset constructed importing
```

**Comment by Epix37** [comment]
The restarting crash is definitely an issue, but for HDT to track your deck you have to manually create the deck in HDT or import im from the game via the `IMPORT > FROM GAME` menu item.

**Comment by HPGMaphax** [comment]
Importing decks doesn't work, whenever i try it just gives me the tutorial, even after following it. It might be me being stupid and doing something wrong but it feels like it isn't picking up the client at all. Also tried manualy creating the deck but when i do it doesn't track, it just displays the deck but doesn't update it at all.

**Comment by jtkeating** [comment]
Did you ever figure this out? I believe I'm having the same issue.

**Comment by Epix37** [comment]
I may have fixed the crash now. 

Try
a) manually restarting HDT after changing the path 
and/or 
b) manually setting it as described here: https://github.com/Epix37/Hearthstone-Deck-Tracker#faq (Win+R - paste "%AppData%/HearthstoneDeckTracker")

**Comment by HPGMaphax** [comment]
Do i need to direct to the hearthstone folder or the application in the folder?

**Comment by Epix37** [comment]
The hearthstone folder. It should look something like this: 
`<HearthstoneDirectory>C:\Program Files (x86)\Hearthstone</HearthstoneDirectory>`

**Comment by HPGMaphax** [comment]
When i try the:
"Copy the log.config from Hearthstone Deck Tracker/Files"
I can't find the folder "Files" is this because of a new version? If so, where can i find the log.config?

**Comment by Epix37** [comment]
That should still be there. It's the folder that also contains the "Hearthstone Deck Tracker.exe" - the one you downloaded & extracted, *not* the %AppData% one.

**Comment by HPGMaphax** [comment]
I copied the log and i can import decks now, thanks :)
Now the only problem is that it has some problems importing the decks, it sometimes imports more than the cards in the deck and sometimes less?

**Comment by HPGMaphax** [comment]
Also, it seems to always take 2 of each card even if there is only one in the deck, not sure why it sometimes has less though.

**Comment by HPGMaphax** [comment]
It also throws in random cards.

**Comment by HPGMaphax** [comment]
Other than that it tracks fine now :)

**Comment by Epix37** [comment]
The method HDT uses to import decks has it's limits. The major one being that it can only detect *what*   cards are in a deck, not *how many*. Whether all the cards are added with 1 or 2 copies depends on which way around the total number of cards is closer to 30 such that it takes the least clicks to correct it. A deck with 17 different cards will have them set at 2 because 34 is closer to 30 than 17. 

Not sure about the random cards. You could try restarting HS and then re-running the setup process via `options > tracker > importing > set up constructed importing`.

**Comment by HPGMaphax** [comment]
Well it's not a big problem, it just takes a minute or so to fix, anyway thanks a ton!

**Comment by KJImmy** [comment]
I seem to be having the same issues, although neither of the methods in the FAQ seemed to work for me.
