### ISSUE TITLE
HDT Crashes when trying to select any Paladin deck (Latest BETA)

### ISSUE THREAD

**Issue by samarthj** [Epix37/Hearthstone-Deck-Tracker#1226]
########## Sat, 15, Aug, 2015 07:36:11 ##########
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Match(String input)
   at Hearthstone_Deck_Tracker.Hearthstone.Card.get_Overload()
   at Hearthstone_Deck_Tracker.ManaCurve.UpdateValues()
   at Hearthstone_Deck_Tracker.ManaCurve.SetDeck(Deck deck)
   at Hearthstone_Deck_Tracker.MainWindow.SelectDeck(Deck deck, Boolean setActive)
   at Hearthstone_Deck_Tracker.MainWindow.DeckPickerList_OnSelectedDeckChanged(DeckPicker sender, Deck deck)
   at Hearthstone_Deck_Tracker.Controls.DeckPicker.DeckPicker.ListViewDecks_OnSelectionChanged(Object sender, SelectionChangedEventArgs e)
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.ListBox.MakeSingleSelection(ListBoxItem listItem)
   at System.Windows.Controls.ListBox.NotifyListItemClicked(ListBoxItem item, MouseButton mouseButton)
   at System.Windows.Controls.ListBoxItem.HandleMouseButtonDown(MouseButton mouseButton)
   at System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[07:36:01] Game: set CurrentGameMode to None
[07:36:01] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[07:36:01] OpponentSecrets: Cleared secrets
[07:36:02] Tracker: set player item source to PlayerDrawn
[07:36:02] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[07:36:02] OpponentSecrets: Cleared secrets
[07:36:02] GameEventHandler: Reset constructed importing
[07:36:02] Helper: Checking for LIVE updates...
[07:36:02] Helper: Current version: 0.10.8.0
[07:36:03] LogReader: Current region: US
[07:36:03] UpdateOverlay: Refreshed overlay topmost status
[07:36:03] BackupManager: Running BackupManager
[07:36:03] BackupManager: Creating backup for today
[07:36:03] PluginManager: Loading Plugins...
[07:36:06] GameEventHandler: Reset constructed importing
[07:36:06] Helper: Latest LIVE version: 0.10.7.0
[07:36:06] Helper: Checking for BETA updates...
[07:36:06] Helper: Current version: 0.10.8.0
[07:36:06] Helper: Latest BETA version: 0.10.8.0

**Comment by Epix37** [comment]
Found the issue, thank you!
