### ISSUE TITLE
New games are not synced with HEARTHSTATS.NET

### ISSUE THREAD

**Issue by johnmichaeld** [Epix37/Hearthstone-Deck-Tracker#1243]
complete game does not show online in my HEARTHSTATS.NET account. log shows:

[3:17:29 PM] HearthStatsManager: Uploading 1 new matches...
[3:17:29 PM] HearthStatsManager: trying to upload 1 matches for deck Aggro S1
[3:17:30 PM] HearthStatsAPI: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsAPI.<PostMultipleGameResultsAsync>d__1.MoveNext()
[3:17:30 PM] HearthStatsManager: finished sync process

previously got error in log:

[3:10:19 PM] HearthStatsManager: trying to upload 1 matches for deck Aggro S1
[3:10:19 PM] HearthStatsAPI: Game Win vs Priest, 8/17/2015 2:42:57 PM is not valid (invalid game mode: None)

**Comment by Epix37** [comment]
Is this the case with every game or just the one you posted the log of?

**Comment by johnmichaeld** [comment]
i just played a second game and it worked. non-working game xml is attached.

thanks!

--
Regards,
John-Michael D'Arcangelo <jmd@dvdempire.com>

**Comment by Epix37** [comment]
Sadly not possible to attach files in github replies via email.

I wouldn't worry about it for now though, probably just the oddball-game. Let me know if it happens again and I'll look into it!
