### ISSUE TITLE
Error when importing deck from constructed

### ISSUE THREAD

**Issue by zalidane** [Epix37/Hearthstone-Deck-Tracker#1412]
When trying to import a deck from constructed using the process outlined in the help popup, the application crashed with the following error:

########## 9/7/2015 8:54:35 AM ##########
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Last\[TSource\](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.MainWindow.<BtnConstructed_Click>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Any chance you were trying to import a deck without any class cards (i.e. neutrals only)?

**Comment by zalidane** [comment]
This is the deck list I was trying to import:

Innervate x2
Wild Growth x2
Millhouse Manastorm
Alarm-o-Bot x2
King Mukla
Astral Communion
Nourish x2
Blingtron 3000
Feugen
Loatheb
Stalagg
Cairne Bloodhoof
Emperor Thaurissan
Gelbin Mekkatorque
Justicar Trueheart
Sylvanus Windrunner
The Black Knight
Dr. Boom
Troggzor the Earthinator
Chromaggus
Kel'Thuzad
Ragnaros the Firelord
Sneed's Old Shredder
Alexstrasza
Nefarian
Nozdormu

I have noticed that it usually takes 3 or four 'scans' of the deck to
import the correct cards.  I guess it's possible that on this attempt, it
scanned the deck and didn't see any class cards.
