### ISSUE TITLE
Crashing upon startup after most recent update.

### ISSUE THREAD

**Issue by NihilityHS** [Epix37/Hearthstone-Deck-Tracker#1437]
I just updated a few minutes ago upon opening HDT and after the update the program is crashing upon startup. The loading icon  appears, then it crashes and informs me to post the crash report here. 

```
########## 9/11/2015 2:24:13 AM ##########
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.LoginWindow' that matches the specified binding constraints threw an exception. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Hearthstone_Deck_Tracker.Config.Reset(String name)
   at Hearthstone_Deck_Tracker.MainWindow.ConvertLegacyConfig(Version currentVersion, Version configVersion)
   at Hearthstone_Deck_Tracker.MainWindow..ctor(GameV2 game)
   at Hearthstone_Deck_Tracker.LoginWindow.StartMainApp()
   at Hearthstone_Deck_Tracker.LoginWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Demoniko** [comment]
Same issue.

**Comment by Epix37** [comment]
Fixed with v0.11.2. Sorry about that.
https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.11.2

**Comment by NihilityHS** [comment]
That took care of it. Thanks for the super fast fix!

**Comment by Demoniko** [comment]
Thanks, works fine now.
