### ISSUE TITLE
crashing deck tracker

### ISSUE THREAD

**Issue by aguwavic** [Epix37/Hearthstone-Deck-Tracker#1467]
here is the crash report.

########## 9/13/2015 8:39:59 AM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   at System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   at System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Shapes.Shape.get_Fill()
   at System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   at System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by riQQ** [comment]
What were the circumstances when this happened?

**Comment by aguwavic** [comment]
Start my computer then hearthstone then the deck tracker and it started to crash on startup.

**Comment by Epix37** [comment]
So.. I googled that and found an issue from this github. That's a first :D.

Have a look at #1057. Maybe it's that simple as well?

**Comment by aguwavic** [comment]
Thanks. Lol it was that simple...
