### ISSUE TITLE
Crash Log (Tavern Brawl) 

### ISSUE THREAD

**Issue by dfennd** [Epix37/Hearthstone-Deck-Tracker#1470]
Not sure if related to #1463 or just a coincidence. After I turned on recording for Brawl and starting playing a match, HDT crashed mid-game.

Crash Log:
########## 9/13/2015 2:29:19 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.Secret.<AdjustedCount>b__0(CardEntity x)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.Secret.AdjustedCount(GameV2 game)
   at Hearthstone_Deck_Tracker.OverlayWindow.ShowSecrets(Boolean force, Nullable`1 heroClass)
   at Hearthstone_Deck_Tracker.GameEventHandler.HandleOpponentSecretPlayed(Entity entity, String cardId, Int32 from, Int32 turn, Boolean fromDeck, Int32 otherId)
   at Hearthstone_Deck_Tracker.GameEventHandler.Hearthstone_Deck_Tracker.IGameHandler.HandleOpponentSecretPlayed(Entity entity, String cardId, Int32 from, Int32 turn, Boolean fromDeck, Int32 otherId)
   at Hearthstone_Deck_Tracker.LogReader.Handlers.TagChangeHandler.TagChange(IHsGameState gameState, String rawTag, Int32 id, String rawValue, IGame game, Boolean isRecursive)
   at Hearthstone_Deck_Tracker.LogReader.Handlers.PowerGameStateHandler.Handle(String logLine, IHsGameState gameState, IGame game)
   at Hearthstone_Deck_Tracker.LogReader.LogReaderManager.ProcessNewLines()
   at Hearthstone_Deck_Tracker.LogReader.LogReaderManager.<StartLogReaders>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2:20:48 PM] Game: -------- Reset ---------
[2:20:48 PM] OpponentSecrets: Cleared secrets
[2:20:48 PM] Game: -------- Reset ---------
[2:20:48 PM] OpponentSecrets: Cleared secrets
[2:20:48 PM] GameEventHandler: Reset constructed importing
[2:20:48 PM] Helper: Checking for LIVE updates...
[2:20:48 PM] Helper: Current version: 0.11.2.0
[2:20:48 PM] LogReader: Current region: US
[2:20:49 PM] UpdateOverlay: Refreshed overlay topmost status
[2:20:49 PM] BackupManager: Running BackupManager
[2:20:49 PM] BackupManager: Backup for today already exists
[2:20:49 PM] PluginManager: Loading Plugins...
[2:20:49 PM] : Checking for duplicate matches...
[2:20:49 PM] GameEventHandler: Reset constructed importing
[2:20:49 PM] Helper: Latest LIVE version: 0.11.2.0
[2:21:20 PM] Tracker: Switched to deck: Arena 13-09 02:44
[2:21:20 PM] Game: -------- Reset ---------
[2:21:20 PM] OpponentSecrets: Cleared secrets
[2:21:20 PM] DeckList: Set active deck to: Arena 13-09 02:44 (Mage)
[2:21:20 PM] GameEventHandler: Reset constructed importing
[2:21:26 PM] DeckList: Set active deck to: 
[2:21:36 PM] Game: set CurrentGameMode to Brawl
[2:23:03 PM] SaveDeck: Saved Decks
[2:23:03 PM] Tracker: Switched to deck: mana
[2:23:03 PM] Game: -------- Reset ---------
[2:23:03 PM] OpponentSecrets: Cleared secrets
[2:23:03 PM] DeckList: Set active deck to: mana (Mage)
[2:23:03 PM] GameEventHandler: Reset constructed importing
[2:23:03 PM] Game: set CurrentGameMode to Brawl
[2:23:08 PM] UpdateOverlay: Refreshed overlay topmost status
[2:23:34 PM] GameEventHandler: --- Game start ---
[2:23:34 PM] Game: -------- Reset ---------
[2:23:34 PM] OpponentSecrets: Cleared secrets
[2:23:34 PM] Game: set CurrentGameMode to None
[2:23:35 PM] GameEventHandler: --- Opponent turn 1 ---
[2:23:35 PM] Opponent Draw: id=11, cardId=, cardName=, turn=0
[2:23:35 PM] Opponent Draw: id=19, cardId=, cardName=, turn=0
[2:23:35 PM] Opponent Draw: id=28, cardId=, cardName=, turn=0
[2:23:35 PM] Player Draw: id=39, cardId=CS2_024, cardName=Frostbolt, turn=0
[2:23:35 PM] Player Draw: id=46, cardId=GVG_097, cardName=Lil' Exorcist, turn=0
[2:23:35 PM] Player Draw: id=54, cardId=GVG_003, cardName=Unstable Portal, turn=0
[2:23:35 PM] Player Draw: id=64, cardId=EX1_294, cardName=Mirror Entity, turn=0
[2:23:35 PM] Player CreateInHand: id=68, cardId=GAME_005, cardName=The Coin, turn=0, mark=Created, created=true
[2:23:35 PM] GameStats: Got coin
[2:23:35 PM] GameEventHandler: Playing against Paladin
[2:23:49 PM] UpdateOverlay: Refreshed overlay topmost status
[2:23:49 PM] Game: set CurrentGameMode to Brawl
[2:23:56 PM] Opponent Draw: id=17, cardId=, cardName=, turn=0
[2:23:56 PM] Opponent Mulligan: id=19, cardId=, cardName=, turn=0
[2:23:57 PM] Player Draw: id=38, cardId=GVG_097, cardName=Lil' Exorcist, turn=0
[2:23:57 PM] Player Mulligan: id=54, cardId=GVG_003, cardName=Unstable Portal, turn=0
[2:23:57 PM] Player Draw: id=47, cardId=CS2_203, cardName=Ironbeak Owl, turn=0
[2:23:57 PM] Player Mulligan: id=39, cardId=CS2_024, cardName=Frostbolt, turn=0
[2:23:57 PM] Player Draw: id=57, cardId=BRM_002, cardName=Flamewaker, turn=0
[2:23:57 PM] Player Mulligan: id=64, cardId=EX1_294, cardName=Mirror Entity, turn=0
[2:23:58 PM] Opponent Draw: id=34, cardId=, cardName=, turn=1
[2:24:06 PM] Opponent Play: id=28, cardId=EX1_029, cardName=Leper Gnome, turn=1
[2:24:07 PM] GameEventHandler: --- Player turn 2 ---
[2:24:07 PM] Player Draw: id=45, cardId=GVG_096, cardName=Piloted Shredder, turn=1
[2:24:14 PM] GameEventHandler: --- Opponent turn 2 ---
[2:24:14 PM] Opponent Draw: id=8, cardId=, cardName=, turn=2
[2:24:25 PM] Opponent SecretPlayedFromHand: id=17, cardId=, cardName=, turn=2, mark=Mulliganed
[2:24:25 PM] OpponentSecrets: Added secret with id:17
[2:24:28 PM] Opponent Play: id=8, cardId=CS2_087, cardName=Blessing of Might, turn=2
[2:24:28 PM] TagChange: WARNING - unhandled zone change (id=69): CREATED -> SETASIDE
[2:24:28 PM] Opponent CreateInPlay: id=69, cardId=CS2_087e, cardName=Blessing of Might, turn=2, mark=Created, created=true
[2:24:28 PM] Opponent PlayToGraveyard: id=8, cardId=CS2_087, cardName=Blessing of Might, turn=2
[2:24:32 PM] GameEventHandler: --- Player turn 3 ---
[2:24:32 PM] Player Draw: id=41, cardId=FP1_004, cardName=Mad Scientist, turn=2
[2:24:37 PM] Opponent PlayToGraveyard: id=28, cardId=EX1_029, cardName=Leper Gnome, turn=2
[2:24:37 PM] TagChange: WARNING - unhandled zone change (id=69): PLAY -> REMOVEDFROMGAME
[2:24:37 PM] Opponent CreateInPlay: id=70, cardId=EX1_029, cardName=Leper Gnome, turn=2, mark=Created, created=true
[2:24:37 PM] Opponent SecretTriggered: id=17, cardId=EX1_136, cardName=Redemption, turn=2, mark=Mulliganed
[2:24:37 PM] OpponentSecrets: Removed secret with id:17
[2:24:39 PM] GameEventHandler: --- Opponent turn 3 ---
[2:24:39 PM] Opponent Draw: id=25, cardId=, cardName=, turn=3
[2:24:45 PM] GameEventHandler: --- Game was lost! ---
[2:24:45 PM] Gamestats: Current Game ended after 3 turns
[2:24:45 PM] GameStats: Assigned current game to deck: mana
[2:24:54 PM] GameEventHandler: Reset constructed importing
[2:24:55 PM] GameEventHandler: Set CurrentGameStats.GameMode to Brawl
[2:24:55 PM] GameEventHandler: Saving DeckStats
[2:25:23 PM] GameEventHandler: --- Game start ---
[2:25:23 PM] Game: -------- Reset ---------
[2:25:23 PM] OpponentSecrets: Cleared secrets
[2:25:23 PM] Game: set CurrentGameMode to None
[2:25:23 PM] GameEventHandler: --- Opponent turn 1 ---
[2:25:23 PM] Player Draw: id=18, cardId=EX1_608, cardName=Sorcerer's Apprentice, turn=0
[2:25:23 PM] Player Draw: id=23, cardId=GVG_097, cardName=Lil' Exorcist, turn=0
[2:25:23 PM] Player Draw: id=28, cardId=BRM_002, cardName=Flamewaker, turn=0
[2:25:23 PM] Player Draw: id=29, cardId=GVG_096, cardName=Piloted Shredder, turn=0
[2:25:23 PM] Opponent Draw: id=42, cardId=, cardName=, turn=0
[2:25:23 PM] Opponent Draw: id=52, cardId=, cardName=, turn=0
[2:25:23 PM] Opponent Draw: id=59, cardId=, cardName=, turn=0
[2:25:23 PM] Player CreateInHand: id=68, cardId=GAME_005, cardName=The Coin, turn=0, mark=Created, created=true
[2:25:23 PM] GameStats: Got coin
[2:25:23 PM] GameEventHandler: Playing against Hunter
[2:25:38 PM] Game: set CurrentGameMode to Brawl
[2:25:40 PM] UpdateOverlay: Refreshed overlay topmost status
[2:25:46 PM] Player Draw: id=31, cardId=NEW1_012, cardName=Mana Wyrm, turn=0
[2:25:46 PM] Player Mulligan: id=29, cardId=GVG_096, cardName=Piloted Shredder, turn=0
[2:25:46 PM] Player Draw: id=10, cardId=AT_002, cardName=Effigy, turn=0
[2:25:46 PM] Player Mulligan: id=28, cardId=BRM_002, cardName=Flamewaker, turn=0
[2:25:46 PM] Player Draw: id=9, cardId=EX1_287, cardName=Counterspell, turn=0
[2:25:46 PM] Player Mulligan: id=18, cardId=EX1_608, cardName=Sorcerer's Apprentice, turn=0
[2:25:46 PM] Player Draw: id=29, cardId=GVG_096, cardName=Piloted Shredder, turn=0
[2:25:46 PM] Player Mulligan: id=23, cardId=GVG_097, cardName=Lil' Exorcist, turn=0
[2:26:00 PM] Opponent Draw: id=51, cardId=, cardName=, turn=0
[2:26:00 PM] Opponent Mulligan: id=42, cardId=, cardName=, turn=0
[2:26:00 PM] Opponent Draw: id=48, cardId=, cardName=, turn=0
[2:26:00 PM] Opponent Mulligan: id=59, cardId=, cardName=, turn=0
[2:26:00 PM] Opponent Draw: id=55, cardId=, cardName=, turn=0
[2:26:00 PM] Opponent Mulligan: id=52, cardId=, cardName=, turn=0
[2:26:01 PM] Opponent Draw: id=61, cardId=, cardName=, turn=1
[2:26:13 PM] GameEventHandler: --- Player turn 2 ---
[2:26:13 PM] Player Draw: id=13, cardId=CS2_024, cardName=Frostbolt, turn=1
[2:26:17 PM] Player Play: id=31, cardId=NEW1_012, cardName=Mana Wyrm, turn=1, mark=Mulliganed
[2:26:18 PM] GameEventHandler: --- Opponent turn 2 ---
[2:26:18 PM] Opponent Draw: id=67, cardId=, cardName=, turn=2
[2:26:25 PM] Opponent Play: id=61, cardId=FP1_007, cardName=Nerubian Egg, turn=2
[2:26:26 PM] GameEventHandler: --- Player turn 3 ---
[2:26:26 PM] Player Draw: id=33, cardId=AT_009, cardName=Rhonin, turn=2
[2:26:35 PM] Player Play: id=68, cardId=GAME_005, cardName=The Coin, turn=2, mark=Created, created=true
[2:26:35 PM] TagChange: WARNING - unhandled zone change (id=69): CREATED -> SETASIDE
[2:26:35 PM] Player CreateInPlay: id=69, cardId=NEW1_012o, cardName=Mana Gorged, turn=2, mark=Created, created=true
[2:26:35 PM] Player PlayToGraveyard: id=68, cardId=GAME_005, cardName=The Coin, turn=2, mark=Created, created=true
[2:26:36 PM] Player SecretPlayedFromHand: id=9, cardId=EX1_287, cardName=Counterspell, turn=2, mark=Mulliganed
[2:26:38 PM] GameEventHandler: --- Opponent turn 3 ---
[2:26:38 PM] Opponent Draw: id=62, cardId=, cardName=, turn=3
[2:26:48 PM] Opponent Play: id=55, cardId=EX1_536, cardName=Eaglehorn Bow, turn=3, mark=Mulliganed
[2:26:50 PM] Player PlayToGraveyard: id=31, cardId=NEW1_012, cardName=Mana Wyrm, turn=3, mark=Mulliganed
[2:26:50 PM] TagChange: WARNING - unhandled zone change (id=69): PLAY -> REMOVEDFROMGAME
[2:26:52 PM] GameEventHandler: --- Player turn 4 ---
[2:26:52 PM] Player Draw: id=28, cardId=BRM_002, cardName=Flamewaker, turn=3
[2:26:59 PM] Player Play: id=28, cardId=BRM_002, cardName=Flamewaker, turn=3
[2:27:01 PM] GameEventHandler: --- Opponent turn 4 ---
[2:27:01 PM] Opponent Draw: id=53, cardId=, cardName=, turn=4
[2:27:07 PM] Opponent Play: id=67, cardId=FP1_011, cardName=Webspinner, turn=4
[2:27:11 PM] Opponent Play: id=51, cardId=EX1_539, cardName=Kill Command, turn=4, mark=Mulliganed
[2:27:11 PM] Opponent PlayToGraveyard: id=51, cardId=EX1_539, cardName=Kill Command, turn=4, mark=Mulliganed
[2:27:15 PM] GameEventHandler: --- Player turn 5 ---
[2:27:15 PM] Player Draw: id=22, cardId=EX1_294, cardName=Mirror Entity, turn=4
[2:27:23 PM] Player Play: id=29, cardId=GVG_096, cardName=Piloted Shredder, turn=4
[2:27:27 PM] GameEventHandler: --- Opponent turn 5 ---
[2:27:27 PM] Opponent Draw: id=54, cardId=, cardName=, turn=5
[2:27:33 PM] Opponent Play: id=48, cardId=EX1_097, cardName=Abomination, turn=5, mark=Mulliganed
[2:27:35 PM] Opponent PlayToGraveyard: id=55, cardId=EX1_536, cardName=Eaglehorn Bow, turn=5, mark=Mulliganed
[2:27:35 PM] Player PlayToGraveyard: id=29, cardId=GVG_096, cardName=Piloted Shredder, turn=5
[2:27:35 PM] Player CreateInPlay: id=70, cardId=AT_109, cardName=Argent Watchman, turn=5, mark=Created, created=true
[2:27:35 PM] Player CreateInPlay: id=71, cardId=GVG_108, cardName=Recombobulator, turn=5, mark=Created, created=true
[2:27:46 PM] GameEventHandler: --- Player turn 6 ---
[2:27:46 PM] Player Draw: id=18, cardId=EX1_608, cardName=Sorcerer's Apprentice, turn=5
[2:27:52 PM] Player SecretPlayedFromHand: id=10, cardId=AT_002, cardName=Effigy, turn=5, mark=Mulliganed
[2:27:52 PM] Opponent PlayToGraveyard: id=67, cardId=FP1_011, cardName=Webspinner, turn=5
[2:27:52 PM] Opponent CreateInHand: id=72, cardId=, cardName=, turn=5, mark=Created, created=true
[2:27:52 PM] Opponent CreateInHand: id=73, cardId=, cardName=, turn=5, mark=Created, created=true
[2:27:59 PM] Opponent PlayToGraveyard: id=61, cardId=FP1_007, cardName=Nerubian Egg, turn=5
[2:27:59 PM] Opponent CreateInPlay: id=74, cardId=FP1_007t, cardName=Nerubian, turn=5, mark=Created, created=true
[2:27:59 PM] Opponent CreateInPlay: id=75, cardId=FP1_007t, cardName=Nerubian, turn=5, mark=Created, created=true
[2:27:59 PM] TagChange: WARNING - unhandled zone change (id=76): CREATED -> SETASIDE
[2:27:59 PM] Player CreateInPlay: id=76, cardId=AT_109e, cardName=Inspired, turn=5, mark=Created, created=true
[2:28:05 PM] Player PlayToGraveyard: id=71, cardId=GVG_108, cardName=Recombobulator, turn=5, mark=Created, created=true
[2:28:07 PM] Player PlayToGraveyard: id=28, cardId=BRM_002, cardName=Flamewaker, turn=5
[2:28:07 PM] Opponent PlayToGraveyard: id=48, cardId=EX1_097, cardName=Abomination, turn=5, mark=Mulliganed
[2:28:07 PM] Player PlayToGraveyard: id=70, cardId=AT_109, cardName=Argent Watchman, turn=5, mark=Created, created=true
[2:28:07 PM] TagChange: WARNING - unhandled zone change (id=76): PLAY -> REMOVEDFROMGAME
[2:28:07 PM] Opponent PlayToGraveyard: id=74, cardId=FP1_007t, cardName=Nerubian, turn=5, mark=Created, created=true
[2:28:07 PM] Opponent PlayToGraveyard: id=75, cardId=FP1_007t, cardName=Nerubian, turn=5, mark=Created, created=true
[2:28:11 PM] GameEventHandler: --- Opponent turn 6 ---
[2:28:11 PM] Opponent Draw: id=64, cardId=, cardName=, turn=6
[2:28:20 PM] Opponent Play: id=72, cardId=AT_058, cardName=King's Elekk, turn=6, mark=Created, created=true
[2:28:20 PM] Opponent JoustReveal: cardId=GVG_096, turn=6
[2:28:20 PM] Opponent Draw: id=43, cardId=, cardName=, turn=6
[2:28:34 PM] Opponent Play: id=54, cardId=FP1_004, cardName=Mad Scientist, turn=6
[2:28:37 PM] Opponent Play: id=62, cardId=FP1_002, cardName=Haunted Creeper, turn=6
[2:28:38 PM] GameEventHandler: --- Player turn 7 ---
[2:28:38 PM] Player Draw: id=19, cardId=CS2_029, cardName=Fireball, turn=6
[2:28:45 PM] Player SecretPlayedFromHand: id=22, cardId=EX1_294, cardName=Mirror Entity, turn=6
[2:29:00 PM] Player Play: id=18, cardId=EX1_608, cardName=Sorcerer's Apprentice, turn=6
[2:29:02 PM] Player Play: id=13, cardId=CS2_024, cardName=Frostbolt, turn=6
[2:29:02 PM] Player PlayToGraveyard: id=13, cardId=CS2_024, cardName=Frostbolt, turn=6
[2:29:03 PM] GameEventHandler: --- Opponent turn 7 ---
[2:29:03 PM] Opponent Draw: id=63, cardId=, cardName=, turn=7
[2:29:12 PM] Opponent Play: id=64, cardId=GVG_043, cardName=Glaivezooka, turn=7
[2:29:12 PM] TagChange: WARNING - unhandled zone change (id=79): CREATED -> SETASIDE
[2:29:12 PM] Opponent CreateInPlay: id=79, cardId=GVG_043e, cardName=Glaivezooka, turn=7, mark=Created, created=true

**Comment by Epix37** [comment]
Should be fixed with e0efea1.
