### ISSUE TITLE
Crash Just Before Game End

### ISSUE THREAD

**Issue by Spedwards** [Epix37/Hearthstone-Deck-Tracker#1539]
Was in a Tavern Brawl just before the end of the game. Not 100% sure on when HDT crashed but I'm fairly sure it was before the game ended. I was Boom Bot, against Annoy-o-tron. I played Madder Bomber. It first hit the opponent's taunt with divine shield, then hit both my Boom Bots. Boom Bots killed the Taunt and then hit face. I finished by winning the game.

########## 2015-10-01 09:12:12 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by riQQ** [comment]
See #1535
