### ISSUE TITLE
crash after game in tavern brawl

### ISSUE THREAD

**Issue by nehehe** [Epix37/Hearthstone-Deck-Tracker#1544]
nothing special :D tracker crash after game not matter if u win or not..

########## 1. 10. 2015 21:58:45 ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[21:54:35] Game: -------- Reset ---------
[21:54:35] OpponentSecrets: Cleared secrets
[21:54:37] Game: -------- Reset ---------
[21:54:37] OpponentSecrets: Cleared secrets
[21:54:37] GameEventHandler: Reset constructed importing
[21:54:38] Helper: Checking for LIVE updates...
[21:54:38] Helper: Current version: 0.11.3.0
[21:54:38] LogReader: Current region: EU
[21:54:38] UpdateOverlay: Refreshed overlay topmost status
[21:54:38] BackupManager: Running BackupManager
[21:54:38] BackupManager: Backup for today already exists
[21:54:38] PluginManager: Loading Plugins...
[21:54:43] : Checking for duplicate matches...
[21:54:43] HearthStatsManager: starting sync process: forceFullSync=False, background=True
[21:54:43] HearthStatsManager: background process indicator ON
[21:54:43] HearthStatsManager: Checking HearthStats for new decks...
[21:54:43] HearthStatsManager: trying to download decks
[21:54:43] HearthStatsAPI: getting decks since 1443728341
[21:54:45] Helper: Latest LIVE version: 0.11.3.0
[21:54:46] HearthStatsManager: no new decks
[21:54:46] HearthStatsManager: Checking HearthStats for new matches...
[21:54:46] HearthStatsManager: trying to download games
[21:54:46] HearthStatsAPI: getting games since 1443728341
[21:54:47] HearthStatsManager: no new games
[21:54:47] HearthStatsManager: Checking for new local decks...
[21:54:47] HearthStatsManager: Checking for new local versions...
[21:54:47] HearthStatsManager: Checking for edited local decks...
[21:54:47] HearthStatsManager: Checking for new local matches...
[21:54:47] HearthStatsManager: Uploading 24 new matches...
[21:54:47] HearthStatsManager: trying to upload 2 matches for deck zoo giant
[21:54:47] HearthStatsAPI: Game Loss vs Mage, 22. 5. 2015 17:32:56 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Rogue, 1. 6. 2015 13:24:28 is not valid (invalid game mode: None)
[21:54:47] HearthStatsManager: No valid games
[21:54:47] HearthStatsManager: trying to upload 7 matches for deck MID
[21:54:47] HearthStatsAPI: Game Loss vs Shaman, 16. 6. 2015 16:49:15 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Druid, 20. 6. 2015 14:31:58 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Warrior, 20. 6. 2015 21:55:11 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Warlock, 4. 7. 2015 11:26:06 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Warrior, 4. 7. 2015 16:52:11 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Warlock, 5. 7. 2015 12:11:04 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Mage, 22. 7. 2015 12:35:06 is not valid (invalid game mode: None)
[21:54:47] HearthStatsManager: No valid games
[21:54:47] HearthStatsManager: trying to upload 2 matches for deck grim - Senfglas
[21:54:47] HearthStatsAPI: Game Loss vs Priest, 7. 7. 2015 16:07:42 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Rogue, 10. 7. 2015 16:06:28 is not valid (invalid game mode: None)
[21:54:47] HearthStatsManager: No valid games
[21:54:47] HearthStatsManager: trying to upload 2 matches for deck Face
[21:54:47] HearthStatsAPI: Game Loss vs Hunter, 5. 7. 2015 20:37:15 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Warrior, 3. 8. 2015 15:01:58 is not valid (invalid game mode: None)
[21:54:47] HearthStatsManager: No valid games
[21:54:47] HearthStatsManager: trying to upload 8 matches for deck HYBRID
[21:54:47] HearthStatsAPI: Game Loss vs Warlock, 30. 5. 2015 20:36:29 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Paladin, 1. 6. 2015 21:36:28 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Rogue, 2. 6. 2015 12:10:22 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Mage, 3. 6. 2015 22:59:52 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Druid, 4. 6. 2015 23:06:27 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Warlock, 5. 6. 2015 22:28:48 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Mage, 8. 6. 2015 10:03:22 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Priest, 12. 6. 2015 15:50:53 is not valid (invalid game mode: None)
[21:54:47] HearthStatsManager: No valid games
[21:54:47] HearthStatsManager: trying to upload 1 matches for deck Eboladin
[21:54:47] HearthStatsAPI: Game Loss vs Druid, 3. 8. 2015 16:11:17 is not valid (invalid game mode: None)
[21:54:47] HearthStatsManager: No valid games
[21:54:47] HearthStatsManager: trying to upload 2 matches for deck face :P
[21:54:47] HearthStatsAPI: Game Loss vs Warlock, 22. 5. 2015 20:06:39 is not valid (invalid game mode: None)
[21:54:47] HearthStatsAPI: Game Loss vs Hunter, 30. 5. 2015 15:12:21 is not valid (invalid game mode: None)
[21:54:47] HearthStatsManager: No valid games
[21:54:47] HearthStatsManager: background process indicator OFF
[21:54:47] HearthStatsManager: finished sync process
[21:55:02] UpdateOverlay: Refreshed overlay topmost status
[21:55:15] GameEventHandler: --- Game start ---
[21:55:15] Game: -------- Reset ---------
[21:55:15] OpponentSecrets: Cleared secrets
[21:55:15] Game: set CurrentGameMode to None
[21:55:15] GameEventHandler: --- Opponent turn 1 ---
[21:55:15] TagChange: WARNING - unhandled zone change (id=19): CREATED -> SETASIDE
[21:55:15] TagChange: WARNING - unhandled zone change (id=20): CREATED -> SETASIDE
[21:55:15] Player Draw: id=21, cardId=GVG_044, cardName=Spider Tank, turn=0
[21:55:15] Player Draw: id=35, cardId=GVG_083, cardName=Upgraded Repair Bot, turn=0
[21:55:15] Opponent Draw: id=48, cardId=, cardName=, turn=0
[21:55:15] Opponent Draw: id=54, cardId=, cardName=, turn=0
[21:55:15] Opponent Draw: id=59, cardId=, cardName=, turn=0
[21:55:15] Player Draw: id=68, cardId=GVG_088, cardName=Ogre Ninja, turn=0
[21:55:15] Opponent Draw: id=71, cardId=, cardName=, turn=0
[21:55:15] Opponent Draw: id=72, cardId=, cardName=, turn=0
[21:55:15] Opponent Coin: id=72, cardId=, cardName=, turn=0, mark=Coin, created=true
[21:55:30] Game: set CurrentGameMode to Brawl
[21:55:37] Player Draw: id=30, cardId=AT_096, cardName=Clockwork Knight, turn=0
[21:55:37] Player Mulligan: id=35, cardId=GVG_083, cardName=Upgraded Repair Bot, turn=0
[21:55:37] Player Draw: id=25, cardId=GVG_037, cardName=Whirling Zap-o-matic, turn=0
[21:55:37] Player Mulligan: id=68, cardId=GVG_088, cardName=Ogre Ninja, turn=0
[21:55:57] Opponent Draw: id=56, cardId=, cardName=, turn=0
[21:55:57] Opponent Mulligan: id=71, cardId=, cardName=, turn=0
[21:55:57] Opponent Draw: id=52, cardId=, cardName=, turn=0
[21:55:57] Opponent Mulligan: id=59, cardId=, cardName=, turn=0
[21:55:57] Player Draw: id=34, cardId=GVG_031, cardName=Recycle, turn=0
[21:56:09] GameEventHandler: --- Opponent turn 1 ---
[21:56:09] Opponent Draw: id=57, cardId=, cardName=, turn=1
[21:56:27] GameEventHandler: --- Player turn 2 ---
[21:56:27] Player Draw: id=35, cardId=GVG_083, cardName=Upgraded Repair Bot, turn=1
[21:56:31] Player Play: id=25, cardId=GVG_037, cardName=Whirling Zap-o-matic, turn=1, mark=Mulliganed
[21:56:33] GameEventHandler: --- Opponent turn 2 ---
[21:56:33] Opponent Draw: id=63, cardId=, cardName=, turn=2
[21:56:41] Game: Could not find entry in db for cardId: TB_MechWar_Boss2_HeroPower
[21:56:45] GameEventHandler: --- Player turn 3 ---
[21:56:45] Player Draw: id=33, cardId=CS1_112, cardName=Holy Nova, turn=2
[21:56:49] Player Play: id=21, cardId=GVG_044, cardName=Spider Tank, turn=2
[21:56:53] GameEventHandler: --- Opponent turn 3 ---
[21:56:53] Opponent Draw: id=40, cardId=, cardName=, turn=3
[21:57:43] Game: Could not find entry in db for cardId: TB_MechWar_Boss2_HeroPower
[21:57:46] GameEventHandler: --- Player turn 4 ---
[21:57:46] Player Draw: id=32, cardId=GVG_011, cardName=Shrinkmeister, turn=3
[21:57:54] Player Play: id=32, cardId=GVG_011, cardName=Shrinkmeister, turn=3
[21:57:54] TagChange: WARNING - unhandled zone change (id=73): CREATED -> SETASIDE
[21:57:54] Player CreateInPlay: id=73, cardId=GVG_011a, cardName=Shrink Ray, turn=3, mark=Created, created=true
[21:57:55] Game: Could not find entry in db for cardId: TB_MechWar_Boss1_HeroPower
[21:58:00] Player PlayToGraveyard: id=73, cardId=GVG_011a, cardName=Shrink Ray, turn=3, mark=Created, created=true
[21:58:00] GameEventHandler: --- Opponent turn 4 ---
[21:58:00] Opponent Draw: id=50, cardId=, cardName=, turn=4
[21:58:18] Opponent Play: id=72, cardId=GAME_005, cardName=The Coin, turn=4, mark=Coin, created=true
[21:58:18] Opponent PlayToGraveyard: id=72, cardId=GAME_005, cardName=The Coin, turn=4, mark=Coin, created=true
[21:58:20] Opponent Play: id=40, cardId=GVG_090, cardName=Madder Bomber, turn=4
[21:58:33] GameEventHandler: --- Player turn 5 ---
[21:58:33] Player Draw: id=27, cardId=GVG_059, cardName=Coghammer, turn=4
[21:58:43] Player Play: id=30, cardId=AT_096, cardName=Clockwork Knight, turn=4, mark=Mulliganed
[21:58:43] TagChange: WARNING - unhandled zone change (id=74): CREATED -> SETASIDE
[21:58:43] Player CreateInPlay: id=74, cardId=AT_096e, cardName=Wound Up, turn=4, mark=Created, created=true

**Comment by riQQ** [comment]
See #1535.
