### ISSUE TITLE
Windows 10 Arena Helper Plugin won't start

### ISSUE THREAD

**Issue by NijeMiBrodo** [Epix37/Hearthstone-Deck-Tracker#1551]
So when I click the plugin Arena Helper it start's spamming new "alert window's" for about a minute and they cover my whole lower half of my computer and than HS Deck Tracker Crashes. I tried replacing HS Arena Helper plugin with the new downloaded one but it didn't help. HS Deck Tracker and all my plugins worked until i upgraded my WIN to WIN 10 so yeah it could be it but I don't know... Please help me I'm desperate.

I can't attach the crash file and I don't know why it says this "
Something went really wrong, and we can’t process that file.

**Comment by NijeMiBrodo** [comment]
########## 2.10.2015. 14:03:40 ##########
System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at ArenaHelper.Plugin.AddElements()
   at ArenaHelper.Plugin.InitializeMainWindow()
   at ArenaHelper.Plugin.ActivateArenaWindow()
   at ArenaHelper.Plugin.<AddMenuItem>b__1(Object sender, RoutedEventArgs args)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[14:03:33] Game: -------- Reset ---------
[14:03:33] OpponentSecrets: Cleared secrets
[14:03:34] GameEventHandler: Reset constructed importing
[14:03:34] BackupManager: Running BackupManager
[14:03:34] BackupManager: Backup for today already exists
[14:03:34] HearthStatsManager: starting sync process: forceFullSync=False, background=True
[14:03:34] HearthStatsManager: background process indicator ON
[14:03:34] HearthStatsManager: Checking HearthStats for new decks...
[14:03:34] HearthStatsManager: trying to download decks
[14:03:34] HearthStatsAPI: getting decks since 1443786343
[14:03:34] PluginManager: Loading Plugins...
[14:03:34] PluginWrapper: Loading Arena Helper
[14:03:34] PluginWrapper: Enabled Arena Helper
[14:03:34] PluginWrapper: Loading Collection Tracker
[14:03:34] PluginWrapper: Enabled Collection Tracker
[14:03:34] Helper: Checking for LIVE updates...
[14:03:34] Helper: Current version: 0.11.4.0
[14:03:35] LogReader: Current region: EU
[14:03:35] UpdateOverlay: Refreshed overlay topmost status
[14:03:35] Game: Set CurrentGameMode to Arena
[14:03:35] : Created new arena deck: Priest
[14:03:35] : Added new card to arena deck: GVG_089 (1/30)
[14:03:35] : Added new card to arena deck: EX1_007 (2/30)
[14:03:35] : Added new card to arena deck: GVG_096 (3/30)
[14:03:35] : Added new card to arena deck: EX1_019 (4/30)
[14:03:35] Helper: Latest LIVE version: 0.11.3.0
[14:03:35] Helper: Checking for BETA updates...
[14:03:35] Helper: Current version: 0.11.4.0
[14:03:35] Helper: Latest BETA version: 0.11.4.0
[14:03:35] HearthStatsManager: no new decks
[14:03:35] HearthStatsManager: Checking HearthStats for new matches...
[14:03:35] HearthStatsManager: trying to download games
[14:03:36] HearthStatsAPI: getting games since 1443786343
[14:03:36] HearthStatsManager: no new games
[14:03:36] HearthStatsManager: Checking for new local decks...
[14:03:36] HearthStatsManager: Checking for new local versions...
[14:03:36] HearthStatsManager: Checking for edited local decks...
[14:03:36] HearthStatsManager: Checking for new local matches...
[14:03:36] HearthStatsManager: Uploading 1 new matches...
[14:03:36] HearthStatsManager: trying to upload 1 matches for deck Midrange Hunter
[14:03:36] HearthStatsAPI: Game Win vs Shaman, 29.9.2015. 21:19:46 is not valid (invalid game mode: None)
[14:03:36] HearthStatsManager: No valid games
[14:03:36] HearthStatsManager: background process indicator OFF
[14:03:36] HearthStatsManager: finished sync process

########## 2.10.2015. 14:03:40 ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at ArenaHelper.Plugin.<OnUpdate>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[14:03:33] Game: -------- Reset ---------
[14:03:33] OpponentSecrets: Cleared secrets
[14:03:34] GameEventHandler: Reset constructed importing
[14:03:34] BackupManager: Running BackupManager
[14:03:34] BackupManager: Backup for today already exists
[14:03:34] HearthStatsManager: starting sync process: forceFullSync=False, background=True
[14:03:34] HearthStatsManager: background process indicator ON
[14:03:34] HearthStatsManager: Checking HearthStats for new decks...
[14:03:34] HearthStatsManager: trying to download decks
[14:03:34] HearthStatsAPI: getting decks since 1443786343
[14:03:34] PluginManager: Loading Plugins...
[14:03:34] PluginWrapper: Loading Arena Helper
[14:03:34] PluginWrapper: Enabled Arena Helper
[14:03:34] PluginWrapper: Loading Collection Tracker
[14:03:34] PluginWrapper: Enabled Collection Tracker
[14:03:34] Helper: Checking for LIVE updates...
[14:03:34] Helper: Current version: 0.11.4.0
[14:03:35] LogReader: Current region: EU
[14:03:35] UpdateOverlay: Refreshed overlay topmost status
[14:03:35] Game: Set CurrentGameMode to Arena
[14:03:35] : Created new arena deck: Priest
[14:03:35] : Added new card to arena deck: GVG_089 (1/30)
[14:03:35] : Added new card to arena deck: EX1_007 (2/30)
[14:03:35] : Added new card to arena deck: GVG_096 (3/30)
[14:03:35] : Added new card to arena deck: EX1_019 (4/30)
[14:03:35] Helper: Latest LIVE version: 0.11.3.0
[14:03:35] Helper: Checking for BETA updates...
[14:03:35] Helper: Current version: 0.11.4.0
[14:03:35] Helper: Latest BETA version: 0.11.4.0
[14:03:35] HearthStatsManager: no new decks
[14:03:35] HearthStatsManager: Checking HearthStats for new matches...
[14:03:35] HearthStatsManager: trying to download games
[14:03:36] HearthStatsAPI: getting games since 1443786343
[14:03:36] HearthStatsManager: no new games
[14:03:36] HearthStatsManager: Checking for new local decks...
[14:03:36] HearthStatsManager: Checking for new local versions...
[14:03:36] HearthStatsManager: Checking for edited local decks...
[14:03:36] HearthStatsManager: Checking for new local matches...
[14:03:36] HearthStatsManager: Uploading 1 new matches...
[14:03:36] HearthStatsManager: trying to upload 1 matches for deck Midrange Hunter
[14:03:36] HearthStatsAPI: Game Win vs Shaman, 29.9.2015. 21:19:46 is not valid (invalid game mode: None)
[14:03:36] HearthStatsManager: No valid games
[14:03:36] HearthStatsManager: background process indicator OFF
[14:03:36] HearthStatsManager: finished sync process

########## 2.10.2015. 14:03:40 ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at ArenaHelper.Plugin.<OnUpdate>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[14:03:33] Game: -------- Reset ---------
[14:03:33] OpponentSecrets: Cleared secrets
[14:03:34] GameEventHandler: Reset constructed importing
[14:03:34] BackupManager: Running BackupManager
[14:03:34] BackupManager: Backup for today already exists
[14:03:34] HearthStatsManager: starting sync process: forceFullSync=False, background=True
[14:03:34] HearthStatsManager: background process indicator ON
[14:03:34] HearthStatsManager: Checking HearthStats for new decks...
[14:03:34] HearthStatsManager: trying to download decks
[14:03:34] HearthStatsAPI: getting decks since 1443786343
[14:03:34] PluginManager: Loading Plugins...
[14:03:34] PluginWrapper: Loading Arena Helper
[14:03:34] PluginWrapper: Enabled Arena Helper
[14:03:34] PluginWrapper: Loading Collection Tracker
[14:03:34] PluginWrapper: Enabled Collection Tracker
[14:03:34] Helper: Checking for LIVE updates...
[14:03:34] Helper: Current version: 0.11.4.0
[14:03:35] LogReader: Current region: EU
[14:03:35] UpdateOverlay: Refreshed overlay topmost status
[14:03:35] Game: Set CurrentGameMode to Arena
[14:03:35] : Created new arena deck: Priest
[14:03:35] : Added new card to arena deck: GVG_089 (1/30)
[14:03:35] : Added new card to arena deck: EX1_007 (2/30)
[14:03:35] : Added new card to arena deck: GVG_096 (3/30)
[14:03:35] : Added new card to arena deck: EX1_019 (4/30)
[14:03:35] Helper: Latest LIVE version: 0.11.3.0
[14:03:35] Helper: Checking for BETA updates...
[14:03:35] Helper: Current version: 0.11.4.0
[14:03:35] Helper: Latest BETA version: 0.11.4.0
[14:03:35] HearthStatsManager: no new decks
[14:03:35] HearthStatsManager: Checking HearthStats for new matches...
[14:03:35] HearthStatsManager: trying to download games
[14:03:36] HearthStatsAPI: getting games since 1443786343
[14:03:36] HearthStatsManager: no new games
[14:03:36] HearthStatsManager: Checking for new local decks...
[14:03:36] HearthStatsManager: Checking for new local versions...
[14:03:36] HearthStatsManager: Checking for edited local decks...
[14:03:36] HearthStatsManager: Checking for new local matches...
[14:03:36] HearthStatsManager: Uploading 1 new matches...
[14:03:36] HearthStatsManager: trying to upload 1 matches for deck Midrange Hunter
[14:03:36] HearthStatsAPI: Game Win vs Shaman, 29.9.2015. 21:19:46 is not valid (invalid game mode: None)
[14:03:36] HearthStatsManager: No valid games
[14:03:36] HearthStatsManager: background process indicator OFF
[14:03:36] HearthStatsManager: finished sync process

**Comment by NijeMiBrodo** [comment]
This is just a few crash reports, I can't copy more

**Comment by Epix37** [comment]
@rembound 

FYI

The [v0.11.4 __beta__ release](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.11.4) breaks a few things in places where the API is bypassed. 
`Helper.MainWindow.Overlay` has been move to `Core.Overlay` ([and can also no longer be null](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Core.cs#L33)).

Are you directly accessing any other things? I'd be happy to add more API endpoints to make plugins more stable throughout changes. Just let me know what you need.

**Comment by Epix37** [comment]
@NijeMiBrodo Arena Helper doesn't work with the current pre-release. If you want to use it, downgrade  to [v0.11.3](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.11.3).

We will make sure it works properly with the next "real" release.

**Comment by NijeMiBrodo** [comment]
I'm only having this issue so far.. thx

**Comment by rembound** [comment]
I added the API changes. Hopefully it works now.
