### ISSUE TITLE
Freezes on startup

### ISSUE THREAD

**Issue by SurferL** [Epix37/Hearthstone-Deck-Tracker#1567]
Hi,

Using Windows 7, with .NET 4.5.2.

I had a power failure while playing Hearthstone (and using the deck tracker), and on restart when trying to open the deck tracker it freezes on start up.

I've tried deleting the config.xml in AppData\Roaming\HearthstoneDeckTracker, to no effect, and also deleting everything in there. I've now tried reinstalling it however it now freezes when attempting to log onto hearthstats. 

Here is the hdt_log.txt:
```
[22:25:57] Game: set CurrentGameMode to None
[22:26:10] HearthStatsAPI: System.Net.WebException: The remote server returned an error: (422) Unprocessable Entity.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsAPI.<PostAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsAPI.<RegisterAsync>d__1.MoveNext()
[22:26:43] HearthStatsAPI: Logging in...
[22:26:46] HearthStatsAPI: Successfully logged in.
[22:26:46] ConvertLegacyConfig: changed config values
[22:26:46] Game: -------- Reset ---------
[22:26:46] OpponentSecrets: Cleared secrets
[22:26:46] Game: -------- Reset ---------
[22:26:46] OpponentSecrets: Cleared secrets
[22:26:46] GameEventHandler: Reset constructed importing
```
Any help would be greatly appreciated :)

**Comment by Epix37** [comment]
Could you post the full log please? (www.pastebin.com)

**Comment by SurferL** [comment]
Is this for the full hdt_log.txt or another log?

**Comment by Epix37** [comment]
Yes, the full version of the snipped you posted above.

**Comment by SurferL** [comment]
Hmm, it somehow managed to fix itself when I tried restarting it. Not too sure what happened but keep up the good work! :)
