### ISSUE TITLE
beta 0.11.5 is crashing when I open it

### ISSUE THREAD

**Issue by radryan** [Epix37/Hearthstone-Deck-Tracker#1575]
It seems to be crashing because of a plugin which is updated. I just deleted the plugin and it works fine. The plugin is "Stats Converter". Here is the Crash report:

########## 10/8/2015 10:45:41 AM ##########
System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at AndBurn.HDT.Plugins.StatsConverter.StatsConverterPlugin.SetSettingsFlyout()
   at AndBurn.HDT.Plugins.StatsConverter.StatsConverterPlugin.<OnLoad>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Thanks

**Comment by andburn** [comment]
The plugin isn't working with the beta releases, I'll update it as soon the next normal release is available.
