### ISSUE TITLE
0.11.5 still crashing with Collection Tracker

### ISSUE THREAD

**Issue by skaforey** [Epix37/Hearthstone-Deck-Tracker#1577]
Tried to start collection tracker (updating database, and as soon as it started I got this crash):

########## 10/8/2015 8:42:51 PM ##########
System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at Hearthstone_Collection_Tracker.Internal.Importing.HearthstoneImporter.ShowHDTOverlay()
   at Hearthstone_Collection_Tracker.Internal.Importing.HearthstoneImporter.<Import>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Collection_Tracker.SettingsWindow.<ButtonImportFromGame_Click>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Yea.. I might not be able to fix that on my end after all.

@ko-vasilev 
`HearthstoneImporter.ShowHDTOverlay()` and `HearthstoneImporter.HideHDTOverlay()` need to use `API.Core.OverlayWindow` rather than `Helper.MainWindow.Overlay`. 

The new API endpoint is only available in pre-release v0.11.5 and will therefore obviously not be compatible with the current live release. I plan on releasing v0.11.6 (as an actual release) some time around sunday/monday.
