### ISSUE TITLE
Crash when importing from the Collection Tracker plugin

### ISSUE THREAD

**Issue by VPenkov** [Epix37/Hearthstone-Deck-Tracker#1597]
########## 12/10/2015 13:59:05 ##########
System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at Hearthstone_Collection_Tracker.Internal.Importing.HearthstoneImporter.ShowHDTOverlay()
   at Hearthstone_Collection_Tracker.Internal.Importing.HearthstoneImporter.<Import>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Collection_Tracker.SettingsWindow.<ButtonImportFromGame_Click>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[13:58:11] GameEventHandler: Reset constructed importing
[13:58:11] BackupManager: Running BackupManager
[13:58:11] BackupManager: Backup for today already exists
[13:58:11] HearthStatsManager: starting sync process: forceFullSync=False, background=True
[13:58:11] HearthStatsManager: background process indicator ON
[13:58:11] HearthStatsManager: Checking HearthStats for new decks...
[13:58:11] HearthStatsManager: trying to download decks
[13:58:11] HearthStatsAPI: getting decks since 1444646581
[13:58:11] PluginManager: Loading Plugins...
[13:58:11] Helper: Checking for LIVE updates...
[13:58:11] Helper: Current version: 0.12.0.0
[13:58:11] LogReader: Current region: EU
[13:58:11] UpdateOverlay: Refreshed overlay topmost status
[13:58:11] Game: Set CurrentGameMode to Friendly
[13:58:11] GameEventHandler: Reset constructed importing
[13:58:12] Game: -------- Reset ---------
[13:58:12] OpponentSecrets: Cleared secrets
[13:58:12] Helper: Latest LIVE version: 0.12.0.0
[13:58:12] HearthStatsManager: no new decks
[13:58:12] HearthStatsManager: Checking HearthStats for new matches...
[13:58:12] HearthStatsManager: trying to download games
[13:58:12] HearthStatsAPI: getting games since 1444646581
[13:58:12] Game: Set CurrentGameMode to Friendly
[13:58:12] GameEventHandler: Reset constructed importing
[13:58:13] HearthStatsManager: no new games
[13:58:13] HearthStatsManager: Checking for new local decks...
[13:58:13] HearthStatsManager: Checking for new local versions...
[13:58:13] HearthStatsManager: Checking for edited local decks...
[13:58:13] HearthStatsManager: Checking for new local matches...
[13:58:13] HearthStatsManager: Uploading 12 new matches...
[13:58:13] HearthStatsManager: trying to upload 3 matches for deck Zoo Lock
[13:58:13] HearthStatsManager: trying to upload 1 matches for deck Miracle Priest
[13:58:13] HearthStatsManager: trying to upload 3 matches for deck Mech Mage
[13:58:13] HearthStatsAPI: Game Win vs Warlock, 28/09/2015 20:25:24 is not valid (invalid game mode: None)
[13:58:13] HearthStatsAPI: Game Loss vs Shaman, 20/08/2015 13:21:59 is not valid (invalid game mode: None)
[13:58:13] HearthStatsManager: No valid games
[13:58:13] HearthStatsManager: trying to upload 2 matches for deck Handlock
[13:58:13] HearthStatsAPI: Game Loss vs Mage, 06/10/2015 00:15:51 is not valid (invalid game mode: None)
[13:58:13] HearthStatsAPI: Game Win vs Warrior, 07/10/2015 13:45:04 is not valid (invalid game mode: None)
[13:58:13] HearthStatsManager: No valid games
[13:58:13] HearthStatsManager: trying to upload 1 matches for deck Handlock
[13:58:13] HearthStatsAPI: Game Win vs Priest, 28/09/2015 22:32:33 is not valid (invalid game mode: None)
[13:58:13] HearthStatsAPI: Game Loss vs Warlock, 01/10/2015 16:03:53 is not valid (invalid game mode: None)
[13:58:13] HearthStatsManager: No valid games
[13:58:13] HearthStatsManager: trying to upload 2 matches for deck Bolster
[13:58:13] HearthStatsAPI: Game Loss vs Paladin, 09/10/2015 17:09:12 is not valid (invalid game mode: None)
[13:58:13] HearthStatsAPI: Game Win vs Warlock, 11/10/2015 23:51:42 is not valid (invalid game mode: None)
[13:58:13] HearthStatsAPI: Game Loss vs Warrior, 08/10/2015 21:15:27 is not valid (invalid game mode: None)
[13:58:13] HearthStatsManager: No valid games
[13:58:13] HearthStatsAPI: Game Loss vs Priest, 09/09/2015 12:44:28 is not valid (invalid game mode: None)
[13:58:13] HearthStatsAPI: Game Loss vs Paladin, 10/09/2015 00:44:17 is not valid (invalid game mode: None)
[13:58:13] HearthStatsManager: No valid games
[13:58:13] HearthStatsAPI: Game Win vs Druid, 13/09/2015 17:55:18 is not valid (invalid game mode: None)
[13:58:13] HearthStatsManager: No valid games
[13:58:13] HearthStatsManager: background process indicator OFF
[13:58:13] HearthStatsManager: finished sync process
[13:58:24] PluginWrapper: Loading Collection Tracker
[13:58:24] PluginWrapper: Enabled Collection Tracker
[13:58:59] UpdateOverlay: Refreshed overlay topmost status

**Comment by Epix37** [comment]
Oops. That's what happens when you mostly test with debug build I guess...

Fixed with v0.12.1.
