### ISSUE TITLE
Crash clicking "Check out the FAQ!" link

### ISSUE THREAD

**Issue by mrlefty** [Epix37/Hearthstone-Deck-Tracker#1604]
I let HDT auto-update, and then clicked the "Check out the FAQ!" link in news item #2. Got the "Oops!" dialog.

**Comment by mrlefty** [comment]
Annnd for whatever reason I can't get the crash report to upload. Here's what looks to be the relevant part.

System.ComponentModel.Win32Exception (0x80004005): Class not registered
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Hearthstone_Deck_Tracker.Utility.NewsUpdater.<ParseMarkup>b__0(Object sender, RequestNavigateEventArgs args)
   at System.Windows.Navigation.RequestNavigateEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Documents.Hyperlink.NavigateToUri(IInputElement sourceElement, Uri targetUri, String targetWindow)
   at System.Windows.Documents.Hyperlink.DoNavigation(Object sender)
   at System.Windows.Documents.Hyperlink.OnClick()
   at System.Windows.Documents.Hyperlink.DispatchNavigation(Object sender)
   at System.Windows.Documents.Hyperlink.DoUserInitiatedNavigation(Object sender)
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(MouseButtonEventArgs e)

**Comment by Epix37** [comment]
Have a look at this: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1285#issuecomment-133160591
