### ISSUE TITLE
HS DeckTracker wont start at all, immediately crashes

### ISSUE THREAD

**Issue by slappydclown** [Epix37/Hearthstone-Deck-Tracker#1632]
Here's crash report ..... 

########## 10/21/2015 7:22:01 PM ##########
System.Exception: Error restoring DeckStats backup. Please manually rename "DeckStats_backup.xml" to "DeckStats.xml" in "%appdata\HearthstoneDeckTracker". ---> System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read9_DeckStatsList()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   at Hearthstone_Deck_Tracker.Stats.DeckStatsList.Load()
   --- End of inner exception stack trace ---
   at Hearthstone_Deck_Tracker.Stats.DeckStatsList.Load()
   at Hearthstone_Deck_Tracker.Stats.DeckStatsList.get_Instance()
   at Hearthstone_Deck_Tracker.Hearthstone.Deck.get_DeckStats()
   at Hearthstone_Deck_Tracker.Hearthstone.Deck.GetRelevantGames()
   at Hearthstone_Deck_Tracker.Hearthstone.Deck.get_WinLossString()
   at Hearthstone_Deck_Tracker.PlayerWindow.SetWinRates()
   at Hearthstone_Deck_Tracker.PlayerWindow.Update()
   at Hearthstone_Deck_Tracker.PlayerWindow..ctor(GameV2 game, List`1 forScreenshot)
   at Hearthstone_Deck_Tracker.Core.Windows.get_PlayerWindow()
   at Hearthstone_Deck_Tracker.FlyoutControls.Options.Overlay.OverlayDeckWindows.UpdateAdditionalWindowsBackground(Brush brush)
   at Hearthstone_Deck_Tracker.FlyoutControls.Options.Overlay.OverlayDeckWindows.Load(GameV2 game)
   at Hearthstone_Deck_Tracker.FlyoutControls.OptionsMain.Load(GameV2 game)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.LoadConfigSettings()
   at Hearthstone_Deck_Tracker.Core.Initialize()
   at Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 10/21/2015 7:22:16 PM ##########
System.Exception: Error restoring DeckStats backup. Please manually rename "DeckStats_backup.xml" to "DeckStats.xml" in "%appdata\HearthstoneDeckTracker". ---> System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read9_DeckStatsList()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   at Hearthstone_Deck_Tracker.Stats.DeckStatsList.Load()
   --- End of inner exception stack trace ---
   at Hearthstone_Deck_Tracker.Stats.DeckStatsList.Load()
   at Hearthstone_Deck_Tracker.Stats.DeckStatsList.get_Instance()
   at Hearthstone_Deck_Tracker.Hearthstone.Deck.get_DeckStats()
   at Hearthstone_Deck_Tracker.Hearthstone.Deck.GetRelevantGames()
   at Hearthstone_Deck_Tracker.Hearthstone.Deck.get_WinLossString()
   at Hearthstone_Deck_Tracker.PlayerWindow.SetWinRates()
   at Hearthstone_Deck_Tracker.PlayerWindow.Update()
   at Hearthstone_Deck_Tracker.PlayerWindow..ctor(GameV2 game, List`1 forScreenshot)
   at Hearthstone_Deck_Tracker.Core.Windows.get_PlayerWindow()
   at Hearthstone_Deck_Tracker.FlyoutControls.Options.Overlay.OverlayDeckWindows.UpdateAdditionalWindowsBackground(Brush brush)
   at Hearthstone_Deck_Tracker.FlyoutControls.Options.Overlay.OverlayDeckWindows.Load(GameV2 game)
   at Hearthstone_Deck_Tracker.FlyoutControls.OptionsMain.Load(GameV2 game)
   at Hearthstone_Deck_Tracker.Windows.MainWindow.LoadConfigSettings()
   at Hearthstone_Deck_Tracker.Core.Initialize()
   at Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
- Go to "%AppData%/HearthstoneDeckTracker" (Win+R, paste)
- Look if you find a "DeckStats.xml" file and if so, delete it
- If you find a "DeckStats_backup.xml" file, rename that to "DeckStats.xml"
- See if it works
- If not: go to the "Backups" folder, open the latest and replace the "DeckStats.xml" with the one from the backup.
