### ISSUE TITLE
Tracker crashes after stolen secret was triggered

### ISSUE THREAD

**Issue by the-gods-are-cruel** [Epix37/Hearthstone-Deck-Tracker#1641]
can't attach file so i pasted it here:

########## 10/23/2015 2:55:02 PM ##########
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Hearthstone_Deck_Tracker.OpponentSecrets.SecretRemoved(Int32 id, String cardId)
   at Hearthstone_Deck_Tracker.GameEventHandler.HandleOpponentSecretTrigger(Entity entity, String cardId, Int32 turn, Int32 otherId)
   at Hearthstone_Deck_Tracker.GameEventHandler.Hearthstone_Deck_Tracker.IGameHandler.HandleOpponentSecretTrigger(Entity entity, String cardId, Int32 turn, Int32 otherId)
   at Hearthstone_Deck_Tracker.LogReader.Handlers.TagChangeHandler.TagChange(IHsGameState gameState, String rawTag, Int32 id, String rawValue, IGame game, Boolean isRecursive)
   at Hearthstone_Deck_Tracker.LogReader.Handlers.PowerGameStateHandler.Handle(String logLine, IHsGameState gameState, IGame game)
   at Hearthstone_Deck_Tracker.LogReader.LogReaderManager.ProcessNewLines()
   at Hearthstone_Deck_Tracker.LogReader.LogReaderManager.<StartLogReaders>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2:54:51 PM] DeckList: Set active deck to: Arena 22-10 08:03 (Paladin)
[2:54:53 PM] : Checking for duplicate matches...
[2:54:53 PM] GameEventHandler: Reset constructed importing
[2:54:53 PM] BackupManager: Running BackupManager
[2:54:53 PM] BackupManager: Backup for today already exists
[2:54:54 PM] HearthStatsManager: starting sync process: forceFullSync=False, background=True
[2:54:54 PM] HearthStatsManager: background process indicator ON
[2:54:54 PM] HearthStatsManager: Checking HearthStats for new decks...
[2:54:54 PM] HearthStatsManager: trying to download decks
[2:54:54 PM] HearthStatsAPI: getting decks since 1445586184
[2:54:54 PM] PluginManager: Loading Plugins...
[2:54:54 PM] PluginWrapper: Loading Arena Helper
[2:54:54 PM] PluginWrapper: Enabled Arena Helper
[2:54:54 PM] Helper: Checking for LIVE updates...
[2:54:54 PM] Helper: Current version: 0.12.3.0
[2:54:54 PM] LogReader: Current region: US
[2:54:54 PM] UpdateOverlay: Refreshed overlay topmost status
[2:54:55 PM] Tracker: Switched to deck: Arena 22-10 08:03
[2:54:55 PM] Game: -------- Reset ---------
[2:54:55 PM] OpponentSecrets: Cleared secrets
[2:54:56 PM] GameEventHandler: Playing against Mage
[2:54:57 PM] Helper: Latest LIVE version: 0.12.2.0
[2:54:57 PM] Helper: Checking for BETA updates...
[2:54:57 PM] Helper: Current version: 0.12.3.0
[2:54:57 PM] HearthStatsManager: no new decks
[2:54:57 PM] HearthStatsManager: Checking HearthStats for new matches...
[2:54:57 PM] HearthStatsManager: trying to download games
[2:54:57 PM] HearthStatsAPI: getting games since 1445586184
[2:54:57 PM] Helper: Latest BETA version: 0.12.3.0
[2:54:58 PM] HearthStatsManager: no new games
[2:54:58 PM] HearthStatsManager: Checking for new local decks...
[2:54:58 PM] HearthStatsManager: Checking for new local versions...
[2:54:58 PM] HearthStatsManager: Checking for edited local decks...
[2:54:58 PM] HearthStatsManager: Checking for new local matches...
[2:54:58 PM] HearthStatsManager: Uploading 5 new matches...
[2:54:58 PM] HearthStatsManager: trying to upload 2 matches for deck Scholar of the Light
[2:54:58 PM] HearthStatsManager: trying to upload 1 matches for deck The Grim Patron!
[2:54:58 PM] HearthStatsAPI: Game Loss vs Warlock, 10/1/2015 3:58:34 PM is not valid (IsClone)
[2:54:58 PM] HearthStatsAPI: Game Win vs Mage, 10/1/2015 4:16:11 PM is not valid (IsClone)
[2:54:58 PM] HearthStatsManager: No valid games
[2:54:58 PM] HearthStatsManager: trying to upload 1 matches for deck ADWCTA's
[2:54:58 PM] HearthStatsAPI: Game Win vs Rogue, 10/16/2015 8:45:37 PM is not valid (invalid game mode: None)
[2:54:58 PM] HearthStatsManager: No valid games
[2:54:58 PM] HearthStatsManager: trying to upload 1 matches for deck ADWCTA's
[2:54:58 PM] HearthStatsAPI: Game Loss vs Rogue, 9/23/2015 10:07:42 AM is not valid (invalid game mode: None)
[2:54:58 PM] HearthStatsManager: No valid games
[2:54:58 PM] HearthStatsAPI: Game Loss vs Mage, 10/17/2015 1:06:57 PM is not valid (invalid game mode: None)
[2:54:58 PM] HearthStatsManager: No valid games
[2:54:58 PM] HearthStatsManager: background process indicator OFF
[2:54:58 PM] HearthStatsManager: finished sync process
[2:54:58 PM] GameEventHandler: --- Game start ---
[2:54:58 PM] Game: -------- Reset ---------
[2:54:58 PM] OpponentSecrets: Cleared secrets
[2:54:58 PM] Game: Set CurrentGameMode to None
[2:54:59 PM] GameEventHandler: --- Opponent turn 1 ---
[2:54:59 PM] Player Draw: id=7, cardId=EX1_396, cardName=Mogu'shan Warden, turn=0
[2:54:59 PM] Player Draw: id=19, cardId=GVG_058, cardName=Shielded Minibot, turn=0
[2:54:59 PM] Player Draw: id=24, cardId=CS2_151, cardName=Silver Hand Knight, turn=0
[2:54:59 PM] Player StolenByOpponent: id=36, cardId=HERO_08, cardName=Jaina Proudmoore, turn=0
[2:54:59 PM] Opponent StolenFromOpponent: id=36, cardId=HERO_08, cardName=Jaina Proudmoore, turn=0, created=true
[2:54:59 PM] Player StolenByOpponent: id=37, cardId=CS2_034, cardName=Fireblast, turn=0
[2:54:59 PM] Opponent StolenFromOpponent: id=37, cardId=CS2_034, cardName=Fireblast, turn=0, created=true
[2:54:59 PM] Opponent Draw: id=38, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Draw: id=46, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Draw: id=57, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Draw: id=61, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Draw: id=68, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Coin: id=68, cardId=, cardName=, turn=0, mark=Coin, created=true
[2:54:59 PM] GameEventHandler: Playing against Mage
[2:54:59 PM] Opponent Draw: id=43, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Mulligan: id=38, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Draw: id=53, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Mulligan: id=57, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Draw: id=62, cardId=, cardName=, turn=0
[2:54:59 PM] Opponent Mulligan: id=61, cardId=, cardName=, turn=0
[2:54:59 PM] Player Draw: id=22, cardId=GVG_061, cardName=Muster for Battle, turn=0
[2:54:59 PM] Player Mulligan: id=7, cardId=EX1_396, cardName=Mogu'shan Warden, turn=0
[2:54:59 PM] Player Draw: id=13, cardId=FP1_020, cardName=Avenge, turn=0
[2:54:59 PM] Player Mulligan: id=24, cardId=CS2_151, cardName=Silver Hand Knight, turn=0
[2:54:59 PM] Player Draw: id=6, cardId=CS2_092, cardName=Blessing of Kings, turn=0
[2:54:59 PM] Player SecretPlayedFromHand: id=13, cardId=FP1_020, cardName=Avenge, turn=0, mark=Mulliganed
[2:54:59 PM] GameEventHandler: --- Opponent turn 1 ---
[2:54:59 PM] Opponent Draw: id=41, cardId=, cardName=, turn=1
[2:54:59 PM] GameEventHandler: --- Player turn 2 ---
[2:54:59 PM] Player Draw: id=25, cardId=EX1_556, cardName=Harvest Golem, turn=1
[2:54:59 PM] Player Play: id=19, cardId=GVG_058, cardName=Shielded Minibot, turn=1
[2:54:59 PM] GameEventHandler: --- Opponent turn 2 ---
[2:54:59 PM] Opponent Draw: id=67, cardId=, cardName=, turn=2
[2:54:59 PM] Opponent Play: id=68, cardId=GAME_005, cardName=The Coin, turn=2, mark=Coin, created=true
[2:54:59 PM] Opponent PlayToGraveyard: id=68, cardId=GAME_005, cardName=The Coin, turn=2, mark=Coin, created=true
[2:54:59 PM] Opponent Play: id=67, cardId=EX1_007, cardName=Acolyte of Pain, turn=2
[2:54:59 PM] GameEventHandler: --- Player turn 3 ---
[2:54:59 PM] Player Draw: id=28, cardId=CS2_092, cardName=Blessing of Kings, turn=2
[2:55:00 PM] Player Play: id=22, cardId=GVG_061, cardName=Muster for Battle, turn=2, mark=Mulliganed
[2:55:00 PM] Player CreateInPlay: id=69, cardId=CS2_101t, cardName=Silver Hand Recruit, turn=2, mark=Created, created=true
[2:55:00 PM] Player CreateInPlay: id=70, cardId=CS2_101t, cardName=Silver Hand Recruit, turn=2, mark=Created, created=true
[2:55:00 PM] Player CreateInPlay: id=71, cardId=CS2_101t, cardName=Silver Hand Recruit, turn=2, mark=Created, created=true
[2:55:00 PM] Player CreateInPlay: id=72, cardId=CS2_091, cardName=Light's Justice, turn=2, mark=Created, created=true
[2:55:00 PM] Player PlayToGraveyard: id=22, cardId=GVG_061, cardName=Muster for Battle, turn=2, mark=Mulliganed
[2:55:00 PM] Opponent Draw: id=52, cardId=, cardName=, turn=2
[2:55:00 PM] Opponent Draw: id=63, cardId=, cardName=, turn=2
[2:55:00 PM] Opponent PlayToGraveyard: id=67, cardId=EX1_007, cardName=Acolyte of Pain, turn=2
[2:55:00 PM] GameEventHandler: --- Opponent turn 3 ---
[2:55:00 PM] Opponent Draw: id=42, cardId=, cardName=, turn=3
[2:55:00 PM] Opponent Play: id=41, cardId=GVG_044, cardName=Spider Tank, turn=3
[2:55:00 PM] GameEventHandler: --- Player turn 4 ---
[2:55:00 PM] Player Draw: id=24, cardId=CS2_151, cardName=Silver Hand Knight, turn=3
[2:55:00 PM] Player Play: id=6, cardId=CS2_092, cardName=Blessing of Kings, turn=3
[2:55:00 PM] TagChange: WARNING - unhandled zone change (id=73): CREATED -> SETASIDE
[2:55:00 PM] Player CreateInPlay: id=73, cardId=CS2_092e, cardName=Blessing of Kings, turn=3, mark=Created, created=true
[2:55:00 PM] Player PlayToGraveyard: id=6, cardId=CS2_092, cardName=Blessing of Kings, turn=3
[2:55:00 PM] Opponent PlayToGraveyard: id=41, cardId=GVG_044, cardName=Spider Tank, turn=3
[2:55:00 PM] GameEventHandler: --- Opponent turn 4 ---
[2:55:00 PM] Opponent Draw: id=51, cardId=, cardName=, turn=4
[2:55:01 PM] Opponent Play: id=52, cardId=GVG_074, cardName=Kezan Mystic, turn=4
[2:55:01 PM] GameEventHandler: --- Player turn 5 ---
[2:55:01 PM] Player Draw: id=8, cardId=AT_076, cardName=Murloc Knight, turn=4
[2:55:01 PM] Player Play: id=28, cardId=CS2_092, cardName=Blessing of Kings, turn=4
[2:55:01 PM] TagChange: WARNING - unhandled zone change (id=74): CREATED -> SETASIDE
[2:55:01 PM] Player CreateInPlay: id=74, cardId=CS2_092e, cardName=Blessing of Kings, turn=4, mark=Created, created=true
[2:55:01 PM] Player PlayToGraveyard: id=28, cardId=CS2_092, cardName=Blessing of Kings, turn=4
[2:55:01 PM] Player PlayToGraveyard: id=19, cardId=GVG_058, cardName=Shielded Minibot, turn=4
[2:55:01 PM] Opponent PlayToGraveyard: id=52, cardId=GVG_074, cardName=Kezan Mystic, turn=4
[2:55:01 PM] GameEventHandler: --- Opponent turn 5 ---
[2:55:01 PM] Opponent Draw: id=38, cardId=, cardName=, turn=5
[2:55:01 PM] Opponent Play: id=51, cardId=GVG_085, cardName=Annoy-o-Tron, turn=5
[2:55:01 PM] Opponent Play: id=63, cardId=EX1_096, cardName=Loot Hoarder, turn=5
[2:55:01 PM] Opponent Play: id=42, cardId=NEW1_012, cardName=Mana Wyrm, turn=5
[2:55:01 PM] GameEventHandler: --- Player turn 6 ---
[2:55:01 PM] Player Draw: id=21, cardId=GVG_058, cardName=Shielded Minibot, turn=5
[2:55:02 PM] Player Play: id=8, cardId=AT_076, cardName=Murloc Knight, turn=5
[2:55:02 PM] Player CreateInPlay: id=75, cardId=CS2_101t, cardName=Silver Hand Recruit, turn=5, mark=Created, created=true
[2:55:02 PM] Player CreateInPlay: id=76, cardId=EX1_506, cardName=Murloc Tidehunter, turn=5, mark=Created, created=true
[2:55:02 PM] Player PlayToGraveyard: id=72, cardId=CS2_091, cardName=Light's Justice, turn=5, mark=Created, created=true
[2:55:02 PM] Opponent PlayToGraveyard: id=51, cardId=GVG_085, cardName=Annoy-o-Tron, turn=5
[2:55:02 PM] TagChange: WARNING - unhandled zone change (id=77): CREATED -> SETASIDE
[2:55:02 PM] Opponent CreateInPlay: id=77, cardId=FP1_020e, cardName=Vengeance, turn=5, mark=Created, created=true
[2:55:02 PM] Opponent SecretTriggered: id=13, cardId=FP1_020, cardName=Avenge, turn=5

**Comment by Epix37** [comment]
Will be fixed with the next update. Was fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/344d94a6dbdc88fadd09ef4d24a084bca0df202e and https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/344d94a6dbdc88fadd09ef4d24a084bca0df202e.
