### ISSUE TITLE
Crash when creating deck with name that already exists

### ISSUE THREAD

**Issue by SNiLD** [Epix37/Hearthstone-Deck-Tracker#1713]
I can't attach the crash report to this repository because "Attaching documents requires write permission to this repository.  Choose Files Try again with a PNG, GIF, or JPG."

You can see the two same deck names in the screenshot.

Here's the probably most interesting part from that crash report:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.Windows.MainWindow.<MenuItem_OnSubmenuOpened>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
![same deck name crash](https://cloud.githubusercontent.com/assets/5400916/11021186/560c67fe-8642-11e5-8a5a-9369a9758f0a.png)

**Comment by SNiLD** [comment]
Forgot to mention that I'm using version 0.13.1.

**Comment by Epix37** [comment]
This happens the moment you press save when adding a deck with the same name? Can you reproduce that with any deck?

**Comment by SNiLD** [comment]
I can't reproduce this with any deck. Seems that the initial thought of the same name being the culprit was wrong. But yes, this did happen the moment I pushed the save button.

**Comment by Epix37** [comment]
Should be fixed with the next update.
