### ISSUE TITLE
How do I troubleshoot syncing errors?

### ISSUE THREAD

**Issue by akarelin** [Epix37/Hearthstone-Deck-Tracker#1716]
Have not been able to sync with hearthstats for a while. HTD is stuck in "Uploading ### new matches" 
In the log I see the following:
[12:07:40] HearthStatsManager: Checking for new local decks...
[12:07:40] HearthStatsManager: Checking for new local versions...
[12:07:40] HearthStatsManager: Checking for edited local decks...
[12:07:40] HearthStatsManager: Checking for new local matches...
[12:07:40] HearthStatsManager: Uploading 136 new matches...
[12:07:40] HearthStatsManager: There was an error syncing with HearthStats:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsManager.<SyncAsync>b__115(<>f__AnonymousType22`2 x)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.GetOrderableDynamicPartitions()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsManager.<>c__DisplayClass37.<SyncAsync>b__108()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsManager.<SyncAsync>d__1.MoveNext()

**Comment by Epix37** [comment]
Should be fixed with v0.13.3

**Comment by akarelin** [comment]
Thank you very much. Just donated to express my gratitude.

**Comment by Epix37** [comment]
Thank you! :)
