### ISSUE TITLE
System.IO.IOException: There is not enough space on the disk.

### ISSUE THREAD

**Issue by Spedwards** [Epix37/Hearthstone-Deck-Tracker#1719]
```
########## 2015-11-10 08:00:48 PM ##########
System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Hearthstone_Deck_Tracker.XmlManager`1.Save(String path, Object obj)
   at Hearthstone_Deck_Tracker.DeckList.Save()
   at Hearthstone_Deck_Tracker.Windows.MainWindow.<SaveDeck>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I got this while saving a deck edit. The thing is, my C: is full, and HDT runs completely on M: so this shouldn't happen.

Also, it's not a clean, user friendly way of throwing errors. Consider a popup that says the exception message, "There is not enough space on the disk".

**Comment by Epix37** [comment]
HDT stores data in `%AppData%/HearthstoneDeckTracker`. You can uncheck `options > tracker > settings > save data in appdata` to store it with the "installation". 

Adding the exception message to the dialog is a good idea.
