### ISSUE TITLE
Deck Tracker won't open?

### ISSUE THREAD

**Issue by SnoobyMcHattery** [Epix37/Hearthstone-Deck-Tracker#1746]
When i try and open HDT, it says the "Configuration system failed to initialize"

here is the crash report
########## 13/11/2015 16:54:15 ##########
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Invalid character in the given encoding. Line 1, position 1. (C:\Users\Oli\AppData\Local\Epix\Hearthstone_Deck_Tracker._Url_d5xtaimxuzu03jeku1si4p5od4t324c5\0.1.0.0\user.config line 1) ---> System.Xml.XmlException: Invalid character in the given encoding. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.InvalidCharRecovery(Int32& bytesCount, Int32& charsCount)
   at System.Xml.XmlTextReaderImpl.GetChars(Int32 maxCharsCount)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.SwitchEncoding(Encoding newEncoding)
   at System.Xml.XmlTextReaderImpl.SwitchEncodingToUTF8()
   at System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(Boolean isTextDecl)
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at MahApps.Metro.Controls.WindowApplicationSettings.get_Placement()
   at MahApps.Metro.Controls.WindowSettings.LoadWindowState()
   at MahApps.Metro.Controls.WindowSettings.WindowSourceInitialized(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Window.OnSourceInitialized(EventArgs e)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at Hearthstone_Deck_Tracker.Core.Initialize()
   at Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Did you unzip it before running the exe?

**Comment by SnoobyMcHattery** [comment]
I've been using it for weeks and it's just done it today!

Sent from my iPhone

On 13 Nov 2015, at 20:54, Alexander Zeier <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you unzip it before running the exe?

-

**Comment by Kraivo** [comment]
Same problem

########## 29.11.2015 19:45:05 ##########
System.Windows.Markup.XamlParseException: Инициализатор типа "MahApps.Metro.Controls.TextBoxHelper" выдал исключение. ---> System.TypeLoadException: Не удалось загрузить тип "System.Windows.Input.ICommand" из сборки "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089".
   в MahApps.Metro.Controls.TextBoxHelper..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   в System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   в System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   в System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   в Hearthstone_Deck_Tracker.LoginWindow.InitializeComponent()
   в Hearthstone_Deck_Tracker.LoginWindow..ctor()
   в Hearthstone_Deck_Tracker.Core.Initialize()
   в Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   в System.Windows.Application.OnStartup(StartupEventArgs e)
   в System.Windows.Application.<.ctor>b__1(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
########## 29.11.2015 19:45:05 ##########
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Hearthstone_Deck_Tracker.App.App_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)
   в System.Windows.Threading.Dispatcher.CatchException(Exception e)
   в System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   в System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   в System.Threading.ExecutionContext.runTryCode(Object userData)
   в System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
########## 29.11.2015 19:45:54 ##########
System.Windows.Markup.XamlParseException: Инициализатор типа "MahApps.Metro.Controls.TextBoxHelper" выдал исключение. ---> System.TypeLoadException: Не удалось загрузить тип "System.Windows.Input.ICommand" из сборки "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089".
   в MahApps.Metro.Controls.TextBoxHelper..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   в System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   в System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   в System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   в Hearthstone_Deck_Tracker.LoginWindow.InitializeComponent()
   в Hearthstone_Deck_Tracker.LoginWindow..ctor()
   в Hearthstone_Deck_Tracker.Core.Initialize()
   в Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   в System.Windows.Application.OnStartup(StartupEventArgs e)
   в System.Windows.Application.<.ctor>b__1(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
########## 29.11.2015 19:45:54 ##########
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Hearthstone_Deck_Tracker.App.App_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)
   в System.Windows.Threading.Dispatcher.CatchException(Exception e)
   в System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   в System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   в System.Threading.ExecutionContext.runTryCode(Object userData)
   в System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by riQQ** [comment]
See #1786:
> Go to this path: `C:\Users\John Sherman\AppData\Local\Epix\` and delete the contents of this folder.

**Comment by riQQ** [comment]
@Kraivo https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-starting

I think this can be closed.
