### ISSUE TITLE
HDT crashed when saving deck as v1.01

### ISSUE THREAD

**Issue by t-babin** [Epix37/Hearthstone-Deck-Tracker#1829]
After playing a few games I made some adjustments to my deck in the deck tracker, then tried to save as v1.01. As soon as doing so, the deck tracker crashed. Here are the first few lines of the error report:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Should be fixed.
