### ISSUE TITLE
HDT Crashes with the new brawl (week 50)

### ISSUE THREAD

**Issue by SNiLD** [Epix37/Hearthstone-Deck-Tracker#1837]
Select "no deck" from HDT, pick warlock, join queue and HDT crashes (the latest beta version).

########## 2015-12-09 19:21:57 ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.LogReader.Handlers.TagChangeHandler.TagChange(IHsGameState gameState, String rawTag, Int32 id, String rawValue, IGame game, Boolean isRecursive)
   at Hearthstone_Deck_Tracker.LogReader.Handlers.PowerHandler.Handle(String logLine, IHsGameState gameState, IGame game)
   at Hearthstone_Deck_Tracker.LogReader.LogReaderManager.ProcessNewLines()
   at Hearthstone_Deck_Tracker.LogReader.LogReaderManager.<StartLogReaders>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SNiLD** [comment]
Seems to crash with priest as well, so not class dependent.

**Comment by Epix37** [comment]
This is TagChangeHandler line 380, because `game.PlayerEntity` is still null.

Not entirely sure what the best way of fixing this is yet.

**Comment by tknights2015** [comment]
I can also duplicate this issue. Did not have this problem prior to the new release.

**Comment by Epix37** [comment]
Should be fixed with v0.13.5

**Comment by tknights2015** [comment]
Hi,
Thank you. I just uninstalled the beta and took the earlier version.  The beta was also logging all of my ranks games as casual,
I created a post on the git-hub site for that one.
 
Regards,
Tracy

**Comment by SNiLD** [comment]
I can confirm that this is now fixed.
