### ISSUE TITLE
This specific deck won't export from HDT to HS

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1959]
[This deck](http://www.hearthpwn.com/decks/408126-firestorm-5-0-top-100-legend) has problems exporting to HS. In HS, the mouse just clicks on the deck name, and doesn't even change it. Then nothing happens.

Error log:

```
[4:51:15 PM] DeckExporter: Exporting deckname:Firestorm 5.0 (Top 100 LEGEND), class:Mage, cards:30
[4:51:15 PM] DeckExporter: HsHandle=722310 HsRect={X=0,Y=0,Width=1920,Height=1080} Ratio=0.75 SearchBoxPosX=0.5 SearchBoxPosY=0.915 CardPosX=0.04 Card2PosX=0.2 CardPosY=0.168 ExportPasteClipboard=False ExportNameDeckX=0.85 ExportNameDeckY=0.075 PrioritizeGolden=True DeckExportDelay=60 EnableExportAutoFilter=True ExportZeroButtonX=0.118 ExportZeroButtonY=0.917
[4:51:15 PM] UpdateOverlay: Refreshed overlay topmost status
[4:51:15 PM] DeckExporter: Waiting for 0 seconds before starting the export process
[4:51:15 PM] DeckExporter: Clearing deck...
[4:51:15 PM] DeckExporter: Setting deck name...
[4:51:15 PM] DeckExporter: Error exporting deck: System.ArgumentException: Group delimiters are not balanced.
   at System.Windows.Forms.SendKeys.ParseKeys(String keys, IntPtr hwnd)
   at System.Windows.Forms.SendKeys.Send(String keys, Control control, Boolean wait)
   at Hearthstone_Deck_Tracker.Exporting.ExportingActions.<SetDeckName>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Exporting.DeckExporter.<Export>d__1.MoveNext()
```

**Comment by Epix37** [comment]
This is probably a problem with the parenthesis. Weird thing is: it works fine for me and the deckname in-game contains none. 

Try removing them from the deckname in HDT.

**Comment by GaryKing** [comment]
Removing the parentheses fixes the problem.

**Comment by GiggliG** [comment]
I've noticed this with parentheses too. i remember it failing with another character too, cant remember what it was - maybe a "+".

The export shouldn't fail when the name isn't read properly. It should just enter what the name is detected as, without the failing characters, and then continue with the export.
