### ISSUE TITLE
When exporting a specific deck, "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by TheCodeFiend** [Epix37/Hearthstone-Deck-Tracker#1964]
Windows 10 1511 x64
HDT v0.13.7
Hearthstone v4.1.0.10956

All other decks I have work just fine.  I tried adjusting the speed just in case.

Here is the deck that breaks it.
http://www.icy-veins.com/hearthstone/legendary-coren-direbrew-priest-deck-heroic-mode

Here is the XML for it.
`<Deck>
    <Cards>
      <Card>
        <Id>EX1_332</Id>
        <Count>2</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>BRM_027h</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>CS1_130</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>CS1_129</Id>
        <Count>2</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>CS2_004</Id>
        <Count>2</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>CS2_236</Id>
        <Count>2</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>BRM_017</Id>
        <Count>2</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>CS2_234</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>EX1_622</Id>
        <Count>2</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>EX1_339</Id>
        <Count>2</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>EX1_626</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>CS1_112</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>EX1_624</Id>
        <Count>2</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>GVG_008</Id>
        <Count>2</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>EX1_016</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>FP1_013</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>GVG_114</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>EX1_563</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>GVG_116</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>EX1_572</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
      <Card>
        <Id>CS1_113</Id>
        <Count>1</Count>
        <HighlightFrame>false</HighlightFrame>
      </Card>
    </Cards>
    <Class>Priest</Class>
    <HearthStatsDeckVersionId>6560848</HearthStatsDeckVersionId>
    <HearthStatsId>5864854</HearthStatsId>
    <LastEdited>2016-01-06T23:08:08.1817579-05:00</LastEdited>
    <MissingCards />
    <Url>http://www.icy-veins.com/hearthstone/legendary-coren-direbrew-priest-deck-heroic-mode</Url>
    <Version>
      <Build>0</Build>
      <Major>1</Major>
      <Minor>0</Minor>
      <Revision>0</Revision>
    </Version>
    <DeckHistory />
    <Archived>false</Archived>
    <Note />
    <SelectedVersion>
      <Build>0</Build>
      <Major>1</Major>
      <Minor>0</Minor>
      <Revision>0</Revision>
    </SelectedVersion>
    <HearthStatsIdsAlreadyReset>false</HearthStatsIdsAlreadyReset>
    <IsArenaDeck>false</IsArenaDeck>
    <DeckId>84bf9a9f-3f74-4781-be63-f666f3f43470</DeckId>
    <Name>Priest vs Direbrew</Name>
    <SyncWithHearthStats>true</SyncWithHearthStats>
    <Tags />
    <HearthStatsIdForUploading>5864854</HearthStatsIdForUploading>
  </Deck>`

Here is the log.
[23:00:28] Game: -------- Reset ---------
[23:00:28] Player Name: 
[23:00:28] Opponent Name: 
[23:00:28] OpponentSecrets: Cleared secrets
[23:00:28] LogReaderManager: Restarting LogReaders.
[23:00:35] LogReader: Current region: US
[23:00:35] UpdateOverlay: Refreshed overlay topmost status
[23:00:51] GameEventHandler: Reset constructed importing
[23:00:58] UpdateOverlay: Refreshed overlay topmost status
[23:01:03] DeckExporter: Exporting deckname:Priest vs Direbrew, class:Priest, cards:30
[23:01:03] DeckExporter: HsHandle=2100624 HsRect={X=0,Y=0,Width=1920,Height=1080} Ratio=0.75 SearchBoxPosX=0.5 SearchBoxPosY=0.915 CardPosX=0.04 Card2PosX=0.2 CardPosY=0.168 ExportPasteClipboard=False ExportNameDeckX=0.85 ExportNameDeckY=0.075 PrioritizeGolden=True DeckExportDelay=40 EnableExportAutoFilter=True ExportZeroButtonX=0.118 ExportZeroButtonY=0.917
[23:01:03] UpdateOverlay: Refreshed overlay topmost status
[23:01:03] DeckExporter: Waiting for 1 seconds before starting the export process
[23:01:04] DeckExporter: Clearing deck...
[23:01:05] DeckExporter: Setting deck name...
[23:01:05] DeckExporter: Clearing "Zero" crystal...
[23:01:05] DeckExporter: Clearing set filter...
[23:01:05] DeckExporter: Creating deck...
[23:01:06] DeckExporter: Error exporting deck: System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.Exporting.ExportingHelper.GetSearchString(Card card)
   at Hearthstone_Deck_Tracker.Exporting.ExportingActions.<AddCardToDeck>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Exporting.ExportingActions.<CreateDeck>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Deck_Tracker.Exporting.DeckExporter.<Export>d__1.MoveNext()

**Comment by Epix37** [comment]
Remove and manually re-add ragnaros to/from the deck.
