### ISSUE TITLE
Stuck at prompt to download new version

### ISSUE THREAD

**Issue by HandEyeProtege** [Epix37/Hearthstone-Deck-Tracker#2141]
When I start HDT it works for a short while, until it realizes there is a new version available.  Then the screen greys out, but I don't see the prompt to update to the new version and there is no way to dismiss the grey overlay and get back into the UI.  See the screenshot to see what I mean:

![screenshot](https://cloud.githubusercontent.com/assets/11563983/13305703/2a17d3ca-db12-11e5-8b66-1c1de015526e.png)

**Comment by HandEyeProtege** [comment]
I dug into it a little bit; here's the exception that gets thrown when trying to open the Updater dialog:

System.Exception: The component 'MahApps.Metro.Controls.Dialogs.MessageDialog' does not have a resource identified by the URI '/MahApps.Metro;component/themes/dialogs/messagedialog.xaml'.
    at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
    at MahApps.Metro.Controls.Dialogs.MessageDialog.InitializeComponent()
    at MahApps.Metro.Controls.Dialogs.DialogManager.<>c__DisplayClass31.<ShowMessageAsync>b__28()   
    at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore()
    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
    at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
    at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
    at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback)
    at MahApps.Metro.Controls.Dialogs.DialogManager.<>c__DisplayClass31.<ShowMessageAsync>b__27(Task z)
    at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
    at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at Hearthstone_Deck_Tracker.Utility.Updater.<ShowNewUpdateMessage>d__7.MoveNext() in C:\\Users\\smikula\\Dropbox\\Projects\\HearthstoneDeckTracker\\Hearthstone Deck Tracker\\Utility\\Updater.cs:line 64

**Comment by riQQ** [comment]
What's your .NET Framework version?

**Comment by HandEyeProtege** [comment]
Looks like I'm on 4.6.1.  (My OS is Windows 10 with the November Update.)

**Comment by riQQ** [comment]
This looks like a MahApps.Metro problem. Which version of MahApps.Metro is referenced in your project? 1.1.2.0?

**Comment by HandEyeProtege** [comment]
Yes, it's 1.1.2.0

**Comment by HandEyeProtege** [comment]
Okay, I got to the bottom of this.  A clean install of HDT works fine; it only happened when I included a plugin that I've been developing.  My plugin also had a reference to MahApps.Metro (i.e. a second copy of it in my plug folder).  Once I deleted that extra copy of it the error went away.

Thanks for pointing me in the right direction!
