### ISSUE TITLE
Tracker crashing at startup if hearthstone was never run

### ISSUE THREAD

**Issue by Yehomer** [Epix37/Hearthstone-Deck-Tracker#2206]
Hi,

I installed and tried to run deck tracker after installing hearthstone on a new computer but before running it.

The tracker crashed without an error message.

This is the crash report:

########## 13/03/2016 21:22:58 ##########
System.TypeInitializationException: The type initializer for 'Hearthstone_Deck_Tracker.Utility.LogConfig.LogConfigWatcher' threw an exception. ---> System.ArgumentException: The directory name C:\Users\omery\AppData\Local\Blizzard\Hearthstone is invalid.
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at Hearthstone_Deck_Tracker.Utility.LogConfig.LogConfigWatcher..cctor()
   --- End of inner exception stack trace ---
   at Hearthstone_Deck_Tracker.Utility.LogConfig.LogConfigWatcher.get_FileWatcher()
   at Hearthstone_Deck_Tracker.Utility.LogConfig.LogConfigWatcher.Start()
   at Hearthstone_Deck_Tracker.Core.Initialize()
   at Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Cheers :)

**Comment by Epix37** [comment]
Will be fixed with the next release (https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/097e0f7d95c07119770957946afbe260e01a84d4).

**Comment by Epix37** [comment]
Should be fixed with v0.13.16.
