### ISSUE TITLE
Games duplicated, won't delete and some games not showing up

### ISSUE THREAD

**Issue by piercy** [Epix37/Hearthstone-Deck-Tracker#497]
Hi, I started using this today so, it could be that i've done something to mess it up.  I've only got 3 decks that i use. A Shaman, Warlock and Druid.  The druid is very new i've only done a couple of game with it.  One of the druid games showed up earlier but it was showing up under the Shaman's deck stats.  I tried to move it but couldn't as the deck didnt exist in the tracker yet.  I thought this was odd, and wanted it to be entered automatically so i deleted this entry in the stats.  The delete seemed to work and i can no longer see it.  However, a solo practice game i played 10 minutes ago isn't showing up.  I added the deck to the tracker manually first.  Even in game it showed the correct cards in the overlay.  However, it doesn't show up in the stats (its like that deck hasn't been played yet). see the top line of this image, thats my newest game tracked, except the last i played was the druid (and it showed the correct overlay): http://i.imgur.com/BZf41M4.png

I also have 4 other druid games listed in the stats. They all show the same date, time and duration.  When i check the details there are no hands shown. It's like this stat has got corrupted.  I tried to delete them (all 4) and upon restart of the program they just come back. image: http://i.imgur.com/BZf41M4.png

The warlock deck seems to be tracking ok except for occasionally it seems to track the stats for the wrong deck (ie, i played the shaman and it logged the game against warlock).

Not sure if this is related from a file in the crash reports folder (its the only file):
```
    ########## 03/01/2015 00:30:41 ##########
    System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Hearthstone_Deck_Tracker.DeckStatsControl.MoveGameToOtherDeck(GameStats selectedGame)
   at Hearthstone_Deck_Tracker.DeckStatsControl.BtnOverallMoveToOtherDeck_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[23:55:09] : Checking for updates...
[23:55:09] : Copied log.config to C:\Users\michael\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
```
edit:sorry hit enter and somehow it submitted the ticket empty.

**Comment by Epix37** [comment]
Hey,

could you zip your "%AppData%/HearthstoneDeckTracker" (options > other > open appdata folder) and send it via email to epikz37@gmail.com?

**Comment by piercy** [comment]
Just sent them over. 

Thanks!

**Comment by Epix37** [comment]
Good news: I got the crash fixed.
Not so good news: No idea why they were duplicated or why you can't delete them. Deleting works fine on my end, don't show up again either.

**Comment by piercy** [comment]
No worries. I probably got it in a muddle some how. I presume i'm ok to clear that folder out?  I'll probably clear it out and start over with the next version just to make sure i haven't got anything causing problems.  I havent used it much since i posted as ive been playing on my tablet so im not worried about losing stats etc.

Thanks for your help.

**Comment by Epix37** [comment]
Everything you delete in the folder will be generated if needed, so yea you can delete everything if you like. (You got the backup zip anyway :))
