### ISSUE TITLE
Try to open and instantly crashes

### ISSUE THREAD

**Issue by DalekRy** [Epix37/Hearthstone-Deck-Tracker#594]
I love this addon, but as of a couple hours ago it stopped working.

It immediately crashes.I tried a fresh install and got the exact same crash. Please advise!

Below is the copied data from the Crash Report:

########## 1/19/2015 11:00:53 PM ##########
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.MainWindow' that matches the specified binding constraints threw an exception. ---> System.ArgumentException: '-86' is not a valid value for property 'Width'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.FrameworkElement.set_Width(Double value)
   at Hearthstone_Deck_Tracker.MainWindow.LoadConfig()
   at Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[11:00:50 PM] : Checking for updates...
[11:00:51 PM] : Copied log.config to C:\Users\Funder\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[11:00:51 PM] Hearthstone: Done loading card database (enUS)
[11:00:51 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[11:00:51 PM] OpponentSecrets: Cleared secrets

**Comment by Epix37** [comment]
See #591.

**Comment by DalekRy** [comment]
Vielen Dank! Pardon my incomplete troubleshooting on the matter. I am new to github and navigating it is still a bit unfamiliar.

Your beautiful program works once again!
