### ISSUE TITLE
Crash Report - 1/26/2015

### ISSUE THREAD

**Issue by LookItzJoe** [Epix37/Hearthstone-Deck-Tracker#607]
Just loading into game while recording with OBS.

CRASH REPORT: 

########## 1/26/2015 8:45:42 PM ##########
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   at Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[8:45:39 PM] : Checking for updates...
[8:45:40 PM] : Copied log.config to C:\Users\Look Itz Joe\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[8:45:40 PM] Hearthstone: Done loading card database (enUS)
[8:45:40 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:45:40 PM] OpponentSecrets: Cleared secrets
[8:45:41 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:45:41 PM] OpponentSecrets: Cleared secrets
[8:45:41 PM] : Set player itemsource as playerdeck
[8:45:41 PM] : Switched to deck: Zalae ESL Wk 7 Hunter
[8:45:41 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:45:41 PM] OpponentSecrets: Cleared secrets
[8:45:41 PM] : Game start
[8:45:41 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:45:41 PM] OpponentSecrets: Cleared secrets
[8:45:41 PM] Gamestats: Started new game
[8:45:41 PM] LogReader: Opponent-turn (1)
[8:45:41 PM] LogReader: PlayerDraw (id:EX1_538 turn:0 from:-1)
[8:45:41 PM] Hearthstone: (player deck) Unleash the Hounds count 2 -> 1
[8:45:41 PM] GameStats: New play: PlayerDraw (EX1_538, turn: 0)
[8:45:41 PM] LogReader: PlayerDraw (id:FP1_004 turn:0 from:-1)
[8:45:41 PM] Hearthstone: (player deck) Mad Scientist count 2 -> 1
[8:45:41 PM] GameStats: New play: PlayerDraw (FP1_004, turn: 0)
[8:45:41 PM] LogReader: PlayerDraw (id:EX1_536 turn:0 from:-1)
[8:45:41 PM] Hearthstone: (player deck) Eaglehorn Bow count 2 -> 1
[8:45:41 PM] GameStats: New play: PlayerDraw (EX1_536, turn: 0)
[8:45:41 PM] LogReader: PlayerDraw (id:EX1_029 turn:0 from:-1)
[8:45:41 PM] Hearthstone: (player deck) Leper Gnome count 2 -> 1
[8:45:41 PM] GameStats: New play: PlayerDraw (EX1_029, turn: 0)
[8:45:41 PM] LogReader: OpponentDraw (id: turn:0 from:-1)
[8:45:41 PM] Hearthstone: Set card 0 to age 0
[8:45:41 PM] Hearthstone: Opponent Hand after draw: 0K,  ,  ,  ,0C,  ,  ,  ,  ,  
[8:45:41 PM] GameStats: New play: OpponentDraw (, turn: 0)
[8:45:41 PM] LogReader: OpponentDraw (id: turn:0 from:-1)
[8:45:41 PM] Hearthstone: Set card 1 to age 0
[8:45:41 PM] Hearthstone: Opponent Hand after draw: 0K,0K,  ,  ,0C,  ,  ,  ,  ,  
[8:45:41 PM] GameStats: New play: OpponentDraw (, turn: 0)
[8:45:41 PM] LogReader: OpponentDraw (id: turn:0 from:-1)
[8:45:41 PM] Hearthstone: Set card 2 to age 0
[8:45:41 PM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,  ,0C,  ,  ,  ,  ,  
[8:45:41 PM] GameStats: New play: OpponentDraw (, turn: 0)
[8:45:41 PM] LogReader: PlayerGet (id:GAME_005 turn:0 from:-1)
[8:45:41 PM] Hearthstone: Player got the coin
[8:45:41 PM] GameStats: Got coin
[8:45:41 PM] GameStats: New play: PlayerGet (GAME_005, turn: 0)
[8:45:42 PM] : Refreshed overlay topmost status

########## 1/26/2015 8:45:49 PM ##########
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   at Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[8:45:47 PM] : Checking for updates...
[8:45:47 PM] : Copied log.config to C:\Users\Look Itz Joe\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[8:45:48 PM] Hearthstone: Done loading card database (enUS)
[8:45:48 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:45:48 PM] OpponentSecrets: Cleared secrets
[8:45:48 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:45:48 PM] OpponentSecrets: Cleared secrets
[8:45:48 PM] : Set player itemsource as playerdeck
[8:45:48 PM] : Switched to deck: Zalae ESL Wk 7 Hunter
[8:45:49 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:45:49 PM] OpponentSecrets: Cleared secrets
[8:45:49 PM] : Game start
[8:45:49 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:45:49 PM] OpponentSecrets: Cleared secrets
[8:45:49 PM] Gamestats: Started new game
[8:45:49 PM] LogReader: Opponent-turn (1)
[8:45:49 PM] LogReader: PlayerDraw (id:EX1_538 turn:0 from:-1)
[8:45:49 PM] Hearthstone: (player deck) Unleash the Hounds count 2 -> 1
[8:45:49 PM] GameStats: New play: PlayerDraw (EX1_538, turn: 0)
[8:45:49 PM] LogReader: PlayerDraw (id:FP1_004 turn:0 from:-1)
[8:45:49 PM] Hearthstone: (player deck) Mad Scientist count 2 -> 1
[8:45:49 PM] GameStats: New play: PlayerDraw (FP1_004, turn: 0)
[8:45:49 PM] LogReader: PlayerDraw (id:EX1_536 turn:0 from:-1)
[8:45:49 PM] Hearthstone: (player deck) Eaglehorn Bow count 2 -> 1
[8:45:49 PM] GameStats: New play: PlayerDraw (EX1_536, turn: 0)
[8:45:49 PM] LogReader: PlayerDraw (id:EX1_029 turn:0 from:-1)
[8:45:49 PM] Hearthstone: (player deck) Leper Gnome count 2 -> 1
[8:45:49 PM] GameStats: New play: PlayerDraw (EX1_029, turn: 0)
[8:45:49 PM] LogReader: OpponentDraw (id: turn:0 from:-1)
[8:45:49 PM] Hearthstone: Set card 0 to age 0
[8:45:49 PM] Hearthstone: Opponent Hand after draw: 0K,  ,  ,  ,0C,  ,  ,  ,  ,  
[8:45:49 PM] GameStats: New play: OpponentDraw (, turn: 0)
[8:45:49 PM] LogReader: OpponentDraw (id: turn:0 from:-1)
[8:45:49 PM] Hearthstone: Set card 1 to age 0
[8:45:49 PM] Hearthstone: Opponent Hand after draw: 0K,0K,  ,  ,0C,  ,  ,  ,  ,  
[8:45:49 PM] GameStats: New play: OpponentDraw (, turn: 0)
[8:45:49 PM] LogReader: OpponentDraw (id: turn:0 from:-1)
[8:45:49 PM] Hearthstone: Set card 2 to age 0
[8:45:49 PM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,  ,0C,  ,  ,  ,  ,  
[8:45:49 PM] GameStats: New play: OpponentDraw (, turn: 0)
[8:45:49 PM] LogReader: PlayerGet (id:GAME_005 turn:0 from:-1)
[8:45:49 PM] Hearthstone: Player got the coin
[8:45:49 PM] GameStats: Got coin
[8:45:49 PM] GameStats: New play: PlayerGet (GAME_005, turn: 0)

**Comment by eduardoddutra** [comment]
Same here, crash as soon as turn 1 starts...

**Comment by eduardoddutra** [comment]
it has something to do with card age and/or card marks... this crash occurred when i dismark them to show me these informations.. when i choose to hide again, it worked again.. :D

**Comment by Epix37** [comment]
should be fixed with v0.8.0
