### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by jmaacrks** [Epix37/Hearthstone-Deck-Tracker#612]
I just downloaded the Deck Tracker (0.7.5), extracted the files and tried to run. Immediately Windows pops up saying that "Hearthstone Deck Tracker has stopped working". I am running Windows 8.1 and when I tried to download .NET 4.5 I was told I already had it. Sorry for the lack of information to help, but any aid would be greatly appreciated.

**Comment by jmaacrks** [comment]
I have tried running as administrator.

**Comment by jmaacrks** [comment]
So i just updated to .NET 4.5.2 and now I am getting a crash report. Here it is:
########## 1/28/2015 10:30:15 PM ##########
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.MainWindow' that matches the specified binding constraints threw an exception. ---> System.IO.IOException: The file 'C:\Users\jack\AppData\Roaming\HearthstoneDeckTracker\config_backup.xml' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Hearthstone_Deck_Tracker.XmlManager`1.Save(String path, Object obj)
   at Hearthstone_Deck_Tracker.Config.Save()
   at Hearthstone_Deck_Tracker.SortFilterDecks.Selector_OnSelectionChanged(Object sender, SelectionChangedEventArgs e)
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Controls.Primitives.Selector.set_SelectedItem(Object value)
   at Hearthstone_Deck_Tracker.MainWindow.LoadConfig()
   at Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[10:30:14 PM] : Checking for updates...
[10:30:14 PM] : Copied log.config to C:\Users\jack\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[10:30:15 PM] Hearthstone: Done loading card database (enUS)
[10:30:15 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[10:30:15 PM] OpponentSecrets: Cleared secrets

**Comment by Epix37** [comment]
Go to "%appdata%/hearthstonedecktracker" (press WIN+R, paste) and delete the "config_backup.xml" file.

**Comment by jmaacrks** [comment]
These are the only files present: 
![image](https://cloud.githubusercontent.com/assets/10751413/5958203/1a35513c-a790-11e4-8ad6-d7b99b20c45f.png)

**Comment by Epix37** [comment]
Uuh.. ookay.. 
`The file 'C:\Users\jack\AppData\Roaming\HearthstoneDeckTracker\config_backup.xml' already exists.` is apparently why it crahed.

Try deleting all the files there and see if it starts.

**Comment by jmaacrks** [comment]
Have tried. I just receive the same thing,  "Hearthstone Deck Tracker has stopped working". There are no crash reports and I have no way to tell what is wrong. I'm sorry if I am little help, but I am unsure what to do. I appreciate all the help you are giving. I will be sure to donate.

**Comment by Epix37** [comment]
I know you already updated .NET framework, but try reinstalling it again, reboot, see if it starts then.
