### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by chfalcao** [Epix37/Hearthstone-Deck-Tracker#661]
When: on auto-loading loading the program after Windows (8.1 64bit) start up

Crash report:

########## 10/02/2015 1:12:06 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at MahApps.Metro.Behaviours.GlowWindowBehavior.AssociatedObjectStateChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Window.OnStateChanged(EventArgs e)
   at System.Windows.Window.WmSizeChanged(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[1:12:04 PM] : Checking for updates...
[1:12:04 PM] : Copied log.config to C:\Users\Biocentric Living\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[1:12:04 PM] Hearthstone: Done loading card database (enUS)
[1:12:04 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[1:12:04 PM] OpponentSecrets: Cleared secrets
[1:12:05 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[1:12:05 PM] OpponentSecrets: Cleared secrets
[1:12:05 PM] : Set player itemsource as playerdeck
[1:12:05 PM] : Switched to deck: [AcB] Jotto's Tempo Shaman
[1:12:05 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[1:12:05 PM] OpponentSecrets: Cleared secrets

**Comment by Epix37** [comment]
That is an issue with updating behaviour, sorry. Please manually download the latest version here: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases

The next update will fix this (not yet released). To prevent this from happening the next time you could disable "minimize to tray" until then.
