### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Incarceron** [Epix37/Hearthstone-Deck-Tracker#671]
When I run HDT it immediately crashes and generates an error.
Here is the error:

########## 2/10/2015 8:11:07 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at MahApps.Metro.Behaviours.GlowWindowBehavior.AssociatedObjectStateChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Window.OnStateChanged(EventArgs e)
   at System.Windows.Window.WmSizeChanged(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[8:11:05 PM] : Checking for updates...
[8:11:06 PM] : Copied log.config to C:\Users\Austin\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[8:11:06 PM] Hearthstone: Done loading card database (enUS)
[8:11:06 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:11:06 PM] OpponentSecrets: Cleared secrets
[8:11:06 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:11:06 PM] OpponentSecrets: Cleared secrets
[8:11:06 PM] : Set player itemsource as playerdeck
[8:11:06 PM] : Switched to deck: Harder, Better, Faster, Stronger - The Daft Priest (Tested today and is tearing people up)
[8:11:06 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[8:11:06 PM] OpponentSecrets: Cleared secrets
[8:11:07 PM] : >> GAME MODE: Ranked
[8:11:07 PM] : >> GAME MODE: Ranked

**Comment by Epix37** [comment]
That is an issue with updating behaviour. Please manually download the latest version here: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases (should be fixed with this one).

If the current version doesn't open from the tray: rightclick - exit and start it again. Will be fixed with the next update.
