### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by hsbobeck** [Epix37/Hearthstone-Deck-Tracker#688]
Opened Hearthstone, then opened the deck tracker, and I got a crash. Tried some more, but it is crashing every time.

Log:

########## 2/12/2015 6:48:37 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at MahApps.Metro.Behaviours.GlowWindowBehavior.AssociatedObjectStateChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Window.OnStateChanged(EventArgs e)
   at System.Windows.Window.WmSizeChanged(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[6:48:35 PM] : Checking for updates...
[6:48:35 PM] : Copied log.config to C:\Users\user\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[6:48:36 PM] Hearthstone: Done loading card database (enUS)
[6:48:36 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[6:48:36 PM] OpponentSecrets: Cleared secrets
[6:48:36 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[6:48:36 PM] OpponentSecrets: Cleared secrets
[6:48:36 PM] : Set player itemsource as playerdeck
[6:48:36 PM] : Switched to deck: Headhunter
[6:48:36 PM] : >>>>>>>>>>> Reset <<<<<<<<<<<
[6:48:36 PM] OpponentSecrets: Cleared secrets

**Comment by Epix37** [comment]
That is an issue with updating behaviour, sorry. Please manually download the latest version here: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases
