### ISSUE TITLE
Overlay - hide in spectator doesn't work

### ISSUE THREAD

**Issue by Gessarlol** [Epix37/Hearthstone-Deck-Tracker#778]
Hide in spectator doesn't work for me.

Tried to remove Hearthstone-Deck-Tracker completely and use fresh - didn't help.

I'm still seeing my deck in spectator even when hide in spectator is checked

**Comment by Gessarlol** [comment]
Log if helps:

[12:28:36] Helper: Checking for updates...
[12:28:36] Helper: Current version: 0.9.6.0
[12:28:37] ConvertLegacyConfig: changed config values
[12:28:37] Load: Copied log.config to C:\Users\Gessar\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[12:28:37] Game: set CurrentGameMode to None
[12:28:37] Game: Done loading card database (enUS)
[12:28:37] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:28:37] OpponentSecrets: Cleared secrets
[12:28:50] UpdateOverlay: Refreshed overlay topmost status
[12:29:01] UpdateOverlay: Refreshed overlay topmost status
[12:29:18] UpdateOverlayLoop: Exited game
[12:29:18] LogReader: Error cleared log file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Hearthstone_Data\output_log.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Hearthstone_Deck_Tracker.HsLogReader.ClearLog()
[12:29:18] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:29:18] OpponentSecrets: Cleared secrets
[12:31:10] DeckImporter: Importing deck from http://www.hearthstonetopdecks.com/decks/senxs-season-11-1-eu-midrange-hunter/
[12:31:13] DelsectDeck: set player item source to PlayerDrawn
[12:31:13] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:31:13] OpponentSecrets: Cleared secrets
[12:31:16] SaveDeck: Saved Decks
[12:31:16] SaveDeck: auto uploading new/edited deck
[12:31:16] HearthStatsManager: trying to upload deck SenX’s Season 11 #1 EU Midrange Hunter (Hunter)
[12:31:16] HearthStatsManager: error: not logged in
[12:31:16] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:31:16] OpponentSecrets: Cleared secrets
[12:31:16] Tracker: Set player itemsource as playerdeck
[12:31:16] Tracker: Switched to deck: SenX’s Season 11 #1 EU Midrange Hunter
[12:31:21] UpdateOverlay: Refreshed overlay topmost status

**Comment by Epix37** [comment]
Does the tracker work at all? 

```
[12:29:18] LogReader: Error cleared log file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Hearthstone_Data\output_log.txt'.
```
Would suggest otherwise. 

Given, I think spectator does indeed have issue right now, fixing your hearthstone path might help (at least with other functionality). Options > other > tracker > set hearthstone path

**Comment by Gessarlol** [comment]
Hey, actually the tracker works.

I will try to set the hearthstone path to see if it helps,

Thank you for the quick reply

**Comment by Elitesparkle** [comment]
What about disabling the interface, rather than hiding it, when we choose to hide the overlay in Spectator mode?
This way the window for a wrong deck detection should't appear.

**Comment by Epix37** [comment]
What do you mean by disabling?

**Comment by Epix37** [comment]
(This is actually what I've been working on for the past hour)
Spectator mode detection is fixed (this also resulted in notedialog / deck detection behaving inproperly). Game result detection still has issues but I think most people won't care about recording spectator game stats anyway.

**Comment by Elitesparkle** [comment]
> What do you mean by disabling?

When we choose to hide, I think the software is still doing the same work but we can't see it on the overlay. I guess it since it still detects wrong decks.

Instead, if I chose to hide, the software shouldn't load the same things and do the same operations since I won't see them.

I don't know if my explanation is clear.
