### ISSUE TITLE
Crashed after trying to "Move to other deck"

### ISSUE THREAD

**Issue by jimrrchen** [Epix37/Hearthstone-Deck-Tracker#787]
I accidentally deleted a deck in hearthstone tracker and I re-created it again. Then I would like to attribute some games to that deck. So I selected some games and then click on "Move to other deck" and click on the deck I'd like to move to. Then it crashed

![capture](https://cloud.githubusercontent.com/assets/580362/6635977/cf3b8592-c928-11e4-9bf0-2d815d093785.PNG)

Paste of the crash report:

########## 3/13/2015 2:24:37 AM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.DeckStatsControl.MoveGameToOtherDeck(GameStats selectedGame)
   at Hearthstone_Deck_Tracker.DeckStatsControl.BtnOverallMoveToOtherDeck_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2:20:42 AM] Helper: Checking for updates...
[2:20:42 AM] Helper: Current version: 0.9.6.0
[2:20:42 AM] Load: Copied log.config to C:\Users\Singularity\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[2:20:42 AM] Game: set CurrentGameMode to None
[2:20:42 AM] Game: Done loading card database (enUS)
[2:20:42 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:20:42 AM] OpponentSecrets: Cleared secrets
[2:20:42 AM] Tracker: Set player itemsource as playerdeck
[2:20:42 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:20:42 AM] OpponentSecrets: Cleared secrets
[2:20:44 AM] UpdateOverlay: Refreshed overlay topmost status
[2:20:47 AM] UpdateOverlayLoop: Exited game
[2:20:47 AM] LogReader: Cleared log file
[2:20:47 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:20:47 AM] OpponentSecrets: Cleared secrets
[2:21:16 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:21:16 AM] OpponentSecrets: Cleared secrets
[2:21:16 AM] Tracker: Switched to deck: Mech Mage
[2:21:17 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:21:17 AM] OpponentSecrets: Cleared secrets
[2:21:17 AM] Tracker: Switched to deck: Perfect Zoo
[2:21:24 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:21:24 AM] OpponentSecrets: Cleared secrets
[2:21:24 AM] Tracker: Switched to deck: Mech Mage
[2:23:43 AM] HearthStatsManager: trying to move game Win vs Shaman, 3/13/2015 1:41:37 AM to Perfect Zoo (Warlock)
[2:23:43 AM] HearthStatsManager: background process indicator ON
[2:23:43 AM] HearthStatsAPI: error: game has no HearthStatsId
[2:23:43 AM] HearthStatsManager: background process indicator OFF
[2:23:53 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:23:53 AM] OpponentSecrets: Cleared secrets
[2:23:53 AM] Tracker: Switched to deck: Perfect Zoo
[2:24:14 AM] DelsectDeck: set player item source to PlayerDrawn
[2:24:14 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:24:14 AM] OpponentSecrets: Cleared secrets

**Comment by Epix37** [comment]
I had no success reproducing this.

Could you email me (epikz37@gmail.com) your `PlayerDecks.xml` and `DecksStats.xml` (found in `%AppData%/HearthstoneDeckTracker´ - Win+R, paste) as well as the name of the deck you were trying to move the games to?
