### ISSUE TITLE
HP Steam 7 Crash on Startup

### ISSUE THREAD

**Issue by KaiserWilly** [Epix37/Hearthstone-Deck-Tracker#796]
So, downloaded HDT on my tablet to have this on the go as I play on the go. Crashes every time I attempt to run it. Tried compatibility mode to Win7, and admin privileges, to no avail.
It's a HP Stream 7. Runs 32-bit OS (full Win 8) on a 64-bit Processor (Intel Atom Z3735) with 1GB RAM on it. When trying to start program, it opens, then crashes with this crash report:

########## 3/15/2015 5:45:51 PM ##########
System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception. ---> System.IO.FileNotFoundException: Could not find file 'C:\Program Files\Hearthstone\Addons\Hearthstone.Deck.Tracker-v0.9.6\Images\HearthstoneDeckTracker.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at MS.Internal.AppModel.ContentFilePart.CriticalOpenFile(String filename)
   at MS.Internal.AppModel.ContentFilePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Windows.Baml2006.TypeConverterMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Thanks!

**Comment by Epix37** [comment]
Sounds like HDT doesn't have permissions to access it's folders. 

I think creating the folders manually (HDT, HDT/Files and HDT/Images), then dropping the corresponding files in there worked before with this type of issue. 

Just adjusting the security properties of the folder might work, too.

*Or* you are straight up missing files? Especially the "Images\HearthstoneDeckTracker.ico"

**Comment by KaiserWilly** [comment]
I will look at that, and see. They are stored in program files, so that could be it. Won't be able to test till this afternoon, so it could be a while...

**Comment by KaiserWilly** [comment]
You are 100% correct. For some reason, the entire folder didn't copy over when I transferred it. Seems to be working working fine now, but it's crashed on the icon, a frame image, and one or two others. thanks again!

**Comment by Epix37** [comment]
Ok good :).
