### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by jdkgithub** [Epix37/Hearthstone-Deck-Tracker#809]
When I boot up the Tracker, it crashes on start up and briefly flashes a window message that is too quick to read.  Here is the log (I cannot find an appdata folder):

########## 3/17/2015 5:38:18 PM ##########
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.MainWindow' that matches the specified binding constraints threw an exception. ---> System.Exception: Error restoring DeckStats backup. Please manually rename "DeckStats_backup.xml" to "DeckStats.xml" in "%appdata\HearthstoneDeckTracker". ---> System.InvalidOperationException: There is an error in XML document (3111, 32). ---> System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: VerifiedHeroes, Game, Games, Deck, DeckStats, DeckStatsList. Line 3111, position 32.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.ReadString()
   at System.Xml.XmlTextReader.ReadString()
   at System.Xml.XmlReader.ReadElementString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read5_GameStats(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read6_DeckStats(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read7_DeckStatsList(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckStatsList.Read8_DeckStatsList()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   at Hearthstone_Deck_Tracker.Stats.DeckStatsList.Load()
   --- End of inner exception stack trace ---
   at Hearthstone_Deck_Tracker.Stats.DeckStatsList.Load()
   at Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Go to "%appdata%/HearthstoneDeckTracker" and rename the "DeckStats_backup.xml" file to "DeckStats.xml"

If the problem still persists, open the "Backups" folder, open the latest zip (or second to latest possibly) and replace the "DeckStats.xml" with the one from the zip.

**Comment by jdkgithub** [comment]
So, I delete the previous DeckStats.xml and replace it with the new DeckStats.xml?  I tried it, didn't work.  Only works if I delete all history.

**Comment by Epix37** [comment]
What so you mean by "all history"?

**Comment by jdkgithub** [comment]
I mean I delete all the files in "%appdata%/HearthstoneDeckTracker".

**Comment by Epix37** [comment]
In addition to what I said before, try 
a) deleting the config.xml
b) replacing all the files from one of the backup zips
