### ISSUE TITLE
Crash when starting a new game

### ISSUE THREAD

**Issue by stogle** [Epix37/Hearthstone-Deck-Tracker#811]
HDT is crashing when I start a new game, as the Find Opponent wheel comes to a stop. Here is the crash report:

########## 21/03/2015 1:24:17 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.SetPlayerHero(String hero)
   at Hearthstone_Deck_Tracker.GameEventHandler.Hearthstone_Deck_Tracker.IGameHandler.SetPlayerHero(String hero)
   at Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   at Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[1:22:14 PM] Load: Copied log.config to C:\Users\Glen\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[1:22:14 PM] Game: set CurrentGameMode to None
[1:22:14 PM] Game: Done loading card database (enUS)
[1:22:14 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[1:22:14 PM] OpponentSecrets: Cleared secrets
[1:22:14 PM] Tracker: Set player itemsource as PlayerDeck
[1:22:14 PM] Tracker: Switched to deck: a Little Greedy - by Kripparian
[1:22:14 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[1:22:14 PM] OpponentSecrets: Cleared secrets
[1:22:14 PM] Helper: Checking for updates...
[1:22:14 PM] Helper: Current version: 0.9.7.0
[1:22:14 PM] BackupManager: Running BackupManager
[1:22:14 PM] BackupManager: Backup for today already exists
[1:22:16 PM] Helper: Latest version: 0.9.7.0
[1:23:47 PM] LogReader: Current region: US
[1:23:56 PM] UpdateOverlay: Refreshed overlay topmost status
[1:23:58 PM] Game: set CurrentGameMode to Casual
[1:24:15 PM] GameEventHandler: Game start
[1:24:15 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[1:24:15 PM] OpponentSecrets: Cleared secrets
[1:24:15 PM] Game: set CurrentGameMode to None
[1:24:15 PM] GameEventHandler: Opponent-turn (1)
[1:24:15 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:24:15 PM] Hearthstone: Set card 0 to age 0
[1:24:15 PM] Hearthstone: Opponent Hand after draw: 0K,  ,  ,  ,0C,  ,  ,  ,  ,  
[1:24:15 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:24:15 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:24:15 PM] Hearthstone: Set card 1 to age 0
[1:24:15 PM] Hearthstone: Opponent Hand after draw: 0K,0K,  ,  ,0C,  ,  ,  ,  ,  
[1:24:15 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:24:15 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:24:15 PM] Hearthstone: Set card 2 to age 0
[1:24:15 PM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,  ,0C,  ,  ,  ,  ,  
[1:24:15 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:24:15 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:24:15 PM] Hearthstone: Set card 3 to age 0
[1:24:15 PM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,0K,0C,  ,  ,  ,  ,  
[1:24:15 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:24:15 PM] GameEventHandler: PlayerDraw (id:CS2_012 turn:0 from:-1)
[1:24:15 PM] GameEventHandler: Found incorrect deck on PlayerDraw
[1:24:15 PM] GameStats: New play: PlayerDraw (CS2_012, turn: 0)
[1:24:15 PM] GameEventHandler: PlayerDraw (id:EX1_050 turn:0 from:-1)
[1:24:15 PM] GameStats: New play: PlayerDraw (EX1_050, turn: 0)
[1:24:15 PM] GameEventHandler: PlayerDraw (id:EX1_154 turn:0 from:-1)
[1:24:15 PM] GameStats: New play: PlayerDraw (EX1_154, turn: 0)
[1:24:16 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:24:16 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:24:16 PM] IncorrectDeckMessage: 0 possible decks found.
[1:24:16 PM] GameEventHandler: Playing against Mage

**Comment by Epix37** [comment]
Same as #795 

Workaround: disable `TRACKER > AUTO DECK SELECTION` (you might be able to reenable it again, after)
