### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DeSpilk** [Epix37/Hearthstone-Deck-Tracker#814]
########## 3/21/2015 3:45:41 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.SetPlayerHero(String hero)
   at Hearthstone_Deck_Tracker.GameEventHandler.Hearthstone_Deck_Tracker.IGameHandler.SetPlayerHero(String hero)
   at Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   at Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Same as #795 

Workaround: disable `TRACKER > AUTO DECK SELECTION` (you might be able to reenable it again, after)
