### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mkrain** [Epix37/Hearthstone-Deck-Tracker#832]
Not sure why the app is crashing but here's the log:

########## 3/30/2015 10:50:09 AM ##########
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.MainWindow' that matches the specified binding constraints threw an exception. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\J\SkyDrive\Hearthstone Data\HearthstoneDeckTracker\PlayerDecks.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Hearthstone_Deck_Tracker.MainWindow.SetupDeckListFile()
   at Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

The file is present but the app renames it to PlayerDecks.xml{number}.  Could it be something in my file?

**Comment by Epix37** [comment]
That's weird. Try replacing it with the one from the latest zip in the
"Backups" folder.

2015-03-30 18:54 GMT+02:00 Jeremiah Medina <notifications@github.com>:

**Comment by mkrain** [comment]
I did.  What worked was deleting the config.xml file and restarting.

**Comment by mkrain** [comment]
I've narrowed this down to the options > Tracker > Settings: Set Hearthstone Path, setting.  If I change this and reopen the tracker it fails to find the aforementioned XML file.  Maybe I'm not using this correct but it's not clear, at least there are not tool-tips indicating, what this is used for and how.

**Comment by Epix37** [comment]
Interesting... Do you have any special characters in your path?

**Comment by mkrain** [comment]
Nope: C:\Users\J\SkyDrive\Hearthstone Data\HearthstoneDeckTracker

**Comment by Epix37** [comment]
To your question before: the Hearthstone path is (or should be) usually detected automatically. The button does exactly that for cases with multiple installations or detection issues.

Can you reproduce the crash consistently by setting the path? Seems to work fine on my end.

**Comment by mkrain** [comment]
Ugh, sorry, it's not HS path but Data Path that's the issue, i.e. "Set Data Path".

**Comment by Epix37** [comment]
Ah that makes more sense! I will look into this. Do so have save config/data in appdata disabled?

**Comment by mkrain** [comment]
Yes both are checked.

**Comment by Epix37** [comment]
Hm.. It works just as expected for me. Setting the datapath without "Save data in AppData" unchecked does not do anything. 

Unchecking "Save data in AppData" moves all data to the previously set path.
