### ISSUE TITLE
Deck Exporter Error

### ISSUE THREAD

**Issue by dantedog** [Epix37/Hearthstone-Deck-Tracker#867]
First off, I have no idea how to reproduce this, I'll do some more digging after I type this up. 

After hitting export deck to hearthstone, the creating deck window appears for about a second, then the export 'process' ends. Checking the log, this 

```
[6:13:54 PM] DeckExporter: Error exporting deck: System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(String format, Object[] args)
   at Hearthstone_Deck_Tracker.DeckExporter.<Export>d__1.MoveNext()
```

error is showing.

Restarting deck tracker and hearthstone doesn't help. Switching Mage decks (this first showed up trying to export a mage deck) results in tracker searching for every card in the deck in game, but failing to attempt to add them (No error message in log). The export incomplete dialog shows up. Switching deck classes (tried druid) changed nothing. Switching back to the original mage deck results in the above error displaying in the log again.

Restarting computer. Has no effect.

**Comment by Epix37** [comment]
Could you post the full log?

**Comment by dantedog** [comment]
After restarting, full log:

```
[6:29:11 PM] Load: Copied log.config to C:\Users\Devin\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[6:29:11 PM] Game: set CurrentGameMode to None
[6:29:11 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[6:29:11 PM] OpponentSecrets: Cleared secrets
[6:29:12 PM] Tracker: Set player itemsource as PlayerDeck
[6:29:12 PM] Tracker: Switched to deck: [BRM} Freeze Mage
[6:29:12 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[6:29:12 PM] OpponentSecrets: Cleared secrets
[6:29:12 PM] Helper: Checking for updates...
[6:29:12 PM] Helper: Current version: 0.9.10.0
[6:29:12 PM] LogReader: Current region: US
[6:29:12 PM] BackupManager: Running BackupManager
[6:29:12 PM] BackupManager: Backup for today already exists
[6:29:12 PM] GameEventHandler: Reset constructed importing
[6:29:13 PM] HearthStatsManager: starting sync process: forceFullSync=False, background=True
[6:29:13 PM] HearthStatsManager: background process indicator ON
[6:29:13 PM] HearthStatsManager: Checking HearthStats for new decks...
[6:29:13 PM] HearthStatsManager: trying to download decks
[6:29:13 PM] HearthStatsAPI: getting decks since 1428171351
[6:29:13 PM] Helper: Latest version: 0.9.10.0
[6:29:22 PM] HearthStatsManager: Checking for new versions...
[6:29:22 PM] HearthStatsManager: Checking for edited decks...
[6:29:22 PM] HearthStatsManager: Checking HearthStats for new matches...
[6:29:22 PM] HearthStatsManager: trying to download games
[6:29:22 PM] HearthStatsAPI: getting games since 1428171351
[6:29:23 PM] UpdateOverlay: Refreshed overlay topmost status
[6:29:30 PM] DeckExporter: Error exporting deck: System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(String format, Object[] args)
   at Hearthstone_Deck_Tracker.DeckExporter.<Export>d__1.MoveNext()
[6:29:30 PM] HearthStatsManager: deck Emperor Druid (Druid) already has match Win vs Hunter, 4/4/2015 5:16:19 PM
[6:29:30 PM] HearthStatsManager: deck Emperor Druid (Druid) already has match Win vs Priest, 4/4/2015 5:26:53 PM
[6:29:30 PM] HearthStatsManager: deck Emperor Druid (Druid) already has match Loss vs Warlock, 4/4/2015 5:35:07 PM
[6:29:30 PM] HearthStatsManager: deck Emperor Druid (Druid) already has match Loss vs Warlock, 4/4/2015 5:52:53 PM
[6:29:30 PM] HearthStatsManager: Checking for new local decks...
[6:29:30 PM] HearthStatsManager: Checking for new local versions...
[6:29:30 PM] HearthStatsManager: Checking for new local matches...
[6:29:30 PM] HearthStatsManager: Uploading 28 new matches...
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Warrior, 2/27/2015 11:33:05 AM
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Priest, 2/22/2015 12:38:08 PM
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Druid, 2/27/2015 9:20:38 PM
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Priest, 2/12/2015 9:47:11 AM
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Druid, 2/25/2015 10:04:13 AM
[6:29:30 PM] HearthStatsManager: trying to upload match: Win vs Paladin, 4/4/2015 5:03:10 PM
[6:29:30 PM] HearthStatsAPI: Game Win vs Paladin, 4/4/2015 5:03:10 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsAPI: Game Loss vs Warrior, 2/27/2015 11:33:05 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Win vs Warrior, 2/22/2015 9:29:01 PM
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Shaman, 2/27/2015 3:08:17 PM
[6:29:30 PM] HearthStatsAPI: Game Win vs Warrior, 2/22/2015 9:29:01 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Mage, 2/12/2015 8:49:36 AM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Mage, 2/12/2015 8:49:36 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsAPI: Game Loss vs Shaman, 2/27/2015 3:08:17 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Warlock, 3/2/2015 8:52:34 AM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Warlock, 3/2/2015 8:52:34 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Druid, 2/26/2015 9:25:10 PM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Druid, 2/26/2015 9:25:10 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Mage, 2/26/2015 10:38:17 PM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Mage, 2/26/2015 10:38:17 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Win vs Hunter, 3/3/2015 9:59:26 AM
[6:29:30 PM] HearthStatsAPI: Game Win vs Hunter, 3/3/2015 9:59:26 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Druid, 3/2/2015 10:07:21 AM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Druid, 3/2/2015 10:07:21 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Mage, 3/4/2015 12:10:47 AM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Mage, 3/4/2015 12:10:47 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Win vs Mage, 3/4/2015 9:24:43 AM
[6:29:30 PM] HearthStatsAPI: Game Win vs Mage, 3/4/2015 9:24:43 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Win vs Priest, 3/21/2015 3:31:48 PM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Druid, 2/25/2015 10:04:13 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsAPI: Game Win vs Priest, 3/21/2015 3:31:48 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Paladin, 4/1/2015 10:57:44 AM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Paladin, 4/1/2015 10:57:44 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Win vs Shaman, 2/25/2015 6:54:09 PM
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Warlock, 3/27/2015 10:25:59 AM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Warlock, 3/27/2015 10:25:59 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Win vs Mage, 3/23/2015 9:44:55 AM
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Priest, 3/14/2015 10:06:05 AM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Priest, 3/14/2015 10:06:05 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Paladin, 2/20/2015 3:01:35 PM
[6:29:30 PM] HearthStatsAPI: Game Win vs Mage, 3/23/2015 9:44:55 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsAPI: Game Loss vs Paladin, 2/20/2015 3:01:35 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Hunter, 3/3/2015 11:44:24 PM
[6:29:30 PM] HearthStatsAPI: Game Win vs Shaman, 2/25/2015 6:54:09 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Win vs Druid, 2/27/2015 8:54:52 AM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Priest, 2/22/2015 12:38:08 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsAPI: Game Loss vs Hunter, 3/3/2015 11:44:24 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Warlock, 3/8/2015 11:51:48 AM
[6:29:30 PM] HearthStatsAPI: Game Win vs Druid, 2/27/2015 8:54:52 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsAPI: Game Loss vs Warlock, 3/8/2015 11:51:48 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsAPI: Game Loss vs Druid, 2/27/2015 9:20:38 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsAPI: Game Loss vs Priest, 2/12/2015 9:47:11 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Hunter, 4/1/2015 4:42:38 PM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Hunter, 4/1/2015 4:42:38 PM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: trying to upload match: Loss vs Mage, 3/31/2015 9:58:47 AM
[6:29:30 PM] HearthStatsAPI: Game Loss vs Mage, 3/31/2015 9:58:47 AM is not valid (invalid game mode: None)
[6:29:30 PM] HearthStatsManager: background process indicator OFF
[6:29:30 PM] HearthStatsManager: finished sync process

```

**Comment by dantedog** [comment]
Deck that throws an error instead of not working is: 

![](http://i.imgur.com/5qW4uLM.png)

```
<Deck>
    <Archived>false</Archived>
    <Cards>
      <Card>
        <Id>CS2_031</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>CS2_024</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>CS2_023</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>CS2_026</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>EX1_289</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>EX1_295</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>CS2_029</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>CS2_028</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>CS2_032</Id>
        <Count>1</Count>
      </Card>
      <Card>
        <Id>EX1_559</Id>
        <Count>1</Count>
      </Card>
      <Card>
        <Id>EX1_279</Id>
        <Count>1</Count>
      </Card>
      <Card>
        <Id>EX1_012</Id>
        <Count>1</Count>
      </Card>
      <Card>
        <Id>NEW1_021</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>GVG_076</Id>
        <Count>1</Count>
      </Card>
      <Card>
        <Id>EX1_096</Id>
        <Count>1</Count>
      </Card>
      <Card>
        <Id>FP1_004</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>EX1_007</Id>
        <Count>2</Count>
      </Card>
      <Card>
        <Id>BRM_028</Id>
        <Count>1</Count>
      </Card>
      <Card>
        <Id>EX1_561</Id>
        <Count>1</Count>
      </Card>
    </Cards>
    <Class>Mage</Class>
    <HearthStatsDeckVersionId>172775</HearthStatsDeckVersionId>
    <HearthStatsId>380546</HearthStatsId>
    <LastEdited>2015-04-04T18:12:50.1107936-04:00</LastEdited>
    <MissingCards />
    <Note />
    <SelectedVersion>
      <Build>0</Build>
      <Major>1</Major>
      <Minor>0</Minor>
      <Revision>0</Revision>
    </SelectedVersion>
    <Url>http://www.hearthpwn.com/decks/217160-brm-freeze-mage-easy-climb</Url>
    <Version>
      <Build>0</Build>
      <Major>1</Major>
      <Minor>0</Minor>
      <Revision>0</Revision>
    </Version>
    <DeckHistory />
    <HearthStatsIdsAlreadyReset>false</HearthStatsIdsAlreadyReset>
    <IsArenaDeck>false</IsArenaDeck>
    <DeckId>bd3569d4-04d7-4ef8-9879-e1958dd40d57</DeckId>
    <Name>[BRM} Freeze Mage</Name>
    <SyncWithHearthStats>true</SyncWithHearthStats>
    <Tags />
    <HearthStatsIdForUploading>380546</HearthStatsIdForUploading>
  </Deck>
```

**Comment by Epix37** [comment]
Ah :) it's the "}" in the deckname.

**Comment by dantedog** [comment]
Good call :)

**Comment by Epix37** [comment]
Fixed now!

**Comment by dantedog** [comment]
Ever thought about adding a menu option to switch either skip the "export deckname to Hearthstone" screen, or set the default option to export instead of cancel?

**Comment by Epix37** [comment]
The default option being cancel is how those mahapps flyouts work. I read some justification on why that is and it made some sense but I can't recall anything exact. 

Having an option to disable the dialog is not a bad idea!

**Comment by dantedog** [comment]
Its a super small thing that hadn't really bothered me too much before, but after exporting a bunch of times in a row it seemed worth a mention ^_^.

**Comment by Epix37** [comment]
It never bothered me either, but now it probably will :D.
New option: `tracker > exporting > show dialog before exporting`
