### ISSUE TITLE
Crashed, will not launch.

### ISSUE THREAD

**Issue by ArxUmbra** [Epix37/Hearthstone-Deck-Tracker#907]
HDT crashed and now will not launch. Below is the contents of the crash report log.

########## 4/21/2015 12:05:14 AM ##########
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[12:03:12 AM] Load: Copied log.config to C:\Users\Aaron\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[12:03:12 AM] Game: set CurrentGameMode to None
[12:03:12 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:03:12 AM] OpponentSecrets: Cleared secrets
[12:03:13 AM] Tracker: Set player itemsource as PlayerDeck
[12:03:13 AM] Tracker: Switched to deck: [BRM] Mill Rogue is Back!
[12:03:13 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:03:13 AM] OpponentSecrets: Cleared secrets
[12:03:13 AM] Helper: Checking for updates...
[12:03:13 AM] Helper: Current version: 0.9.10.0
[12:03:13 AM] BackupManager: Running BackupManager
[12:03:13 AM] BackupManager: Deleting old backup: Backup_04042015.zip
[12:03:13 AM] BackupManager: Creating backup for today
[12:03:14 AM] Helper: Latest version: 0.9.10.0

########## 4/21/2015 12:05:15 AM ##########
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[12:03:12 AM] Load: Copied log.config to C:\Users\Aaron\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[12:03:12 AM] Game: set CurrentGameMode to None
[12:03:12 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:03:12 AM] OpponentSecrets: Cleared secrets
[12:03:13 AM] Tracker: Set player itemsource as PlayerDeck
[12:03:13 AM] Tracker: Switched to deck: [BRM] Mill Rogue is Back!
[12:03:13 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:03:13 AM] OpponentSecrets: Cleared secrets
[12:03:13 AM] Helper: Checking for updates...
[12:03:13 AM] Helper: Current version: 0.9.10.0
[12:03:13 AM] BackupManager: Running BackupManager
[12:03:13 AM] BackupManager: Deleting old backup: Backup_04042015.zip
[12:03:13 AM] BackupManager: Creating backup for today
[12:03:14 AM] Helper: Latest version: 0.9.10.0

########## 4/21/2015 12:05:18 AM ##########
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[12:03:12 AM] Load: Copied log.config to C:\Users\Aaron\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[12:03:12 AM] Game: set CurrentGameMode to None
[12:03:12 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:03:12 AM] OpponentSecrets: Cleared secrets
[12:03:13 AM] Tracker: Set player itemsource as PlayerDeck
[12:03:13 AM] Tracker: Switched to deck: [BRM] Mill Rogue is Back!
[12:03:13 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:03:13 AM] OpponentSecrets: Cleared secrets
[12:03:13 AM] Helper: Checking for updates...
[12:03:13 AM] Helper: Current version: 0.9.10.0
[12:03:13 AM] BackupManager: Running BackupManager
[12:03:13 AM] BackupManager: Deleting old backup: Backup_04042015.zip
[12:03:13 AM] BackupManager: Creating backup for today
[12:03:14 AM] Helper: Latest version: 0.9.10.0

**Comment by Epix37** [comment]
Any chance restarting hearthstone and your machine helps? Maybe try updating .Net framework... Not really sure what might cause this.

**Comment by ArxUmbra** [comment]
Restarting my PC worked. Thanks!

**Comment by Epix37** [comment]
great!
