### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by rftiiv15** [Epix37/Hearthstone-Deck-Tracker#918]
########## 4/28/2015 1:48:30 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[1:39:37 PM] Load: Copied log.config to C:\Users\DayLan\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[1:39:37 PM] Game: set CurrentGameMode to None
[1:39:37 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[1:39:37 PM] OpponentSecrets: Cleared secrets
[1:39:38 PM] Overlay: Enabled mouse hook
[1:39:38 PM] Tracker: set player item source to PlayerDrawn
[1:39:38 PM] Tracker: Deselected deck
[1:39:38 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[1:39:38 PM] OpponentSecrets: Cleared secrets
[1:39:38 PM] Helper: Checking for updates...
[1:39:38 PM] Helper: Current version: 0.9.10.0
[1:39:38 PM] LogReader: Current region: US
[1:39:38 PM] BackupManager: Running BackupManager
[1:39:38 PM] BackupManager: Creating backup for today
[1:39:38 PM] GameEventHandler: Reset constructed importing
[1:39:39 PM] Helper: Latest version: 0.10.0.0
[1:39:43 PM] DeckImporter: Importing deck from http://www.hearthpwn.com/decks/80747-heigan-the-unclean-heroic
[1:39:44 PM] UpdateOverlay: Refreshed overlay topmost status
[1:39:46 PM] UpdateOverlay: Refreshed overlay topmost status
[1:39:47 PM] DeckExporter: Exporting deckname:Heigan the Unclean Heroic, class:Warlock, cards:30
[1:39:47 PM] DeckExporter: Waiting for 0 seconds before starting the export process
[1:39:47 PM] DeckExporter: Clearing deck...
[1:39:47 PM] DeckExporter: Setting deck name...
[1:39:47 PM] DeckExporter: Clicking "all" crystal...
[1:39:47 PM] DeckExporter: Creating deck...
[1:39:49 PM] DeckExporter: Exporting aborted, window lost focus
[1:39:51 PM] UpdateOverlay: Refreshed overlay topmost status
[1:39:57 PM] DeckImporter: Importing deck from http://www.hearthpwn.com/decks/80747-heigan-the-unclean-heroic
[1:39:58 PM] UpdateOverlay: Refreshed overlay topmost status
[1:40:01 PM] DeckExporter: Exporting deckname:Heigan the Unclean Heroic, class:Warlock, cards:30
[1:40:01 PM] UpdateOverlay: Refreshed overlay topmost status
[1:40:02 PM] DeckExporter: Waiting for 0 seconds before starting the export process
[1:40:02 PM] DeckExporter: Clearing deck...
[1:40:02 PM] DeckExporter: Setting deck name...
[1:40:02 PM] DeckExporter: Clicking "all" crystal...
[1:40:03 PM] DeckExporter: Creating deck...
[1:40:13 PM] DeckExporter: Done creating deck.
[1:40:39 PM] UpdateOverlay: Refreshed overlay topmost status
[1:40:40 PM] Game: set CurrentGameMode to Casual
[1:41:18 PM] UpdateOverlay: Refreshed overlay topmost status
[1:41:40 PM] UpdateOverlay: Refreshed overlay topmost status
[1:41:41 PM] GameEventHandler: Reset constructed importing
[1:42:27 PM] UpdateOverlay: Refreshed overlay topmost status
[1:42:29 PM] GameEventHandler: Reset constructed importing
[1:42:34 PM] UpdateOverlay: Refreshed overlay topmost status
[1:42:44 PM] UpdateOverlay: Refreshed overlay topmost status
[1:43:03 PM] UpdateOverlay: Refreshed overlay topmost status
[1:43:11 PM] DeckImporter: Importing deck from http://www.hearthpwn.com/decks/235569-heroic-brm-easy-heroic-nefarius
[1:43:15 PM] DeckExporter: Exporting deckname:[Heroic BRM] Easy Heroic Nefarius, class:Rogue, cards:30
[1:43:15 PM] UpdateOverlay: Refreshed overlay topmost status
[1:43:15 PM] DeckExporter: Waiting for 0 seconds before starting the export process
[1:43:15 PM] DeckExporter: Clearing deck...
[1:43:15 PM] DeckExporter: Setting deck name...
[1:43:15 PM] DeckExporter: Clicking "all" crystal...
[1:43:16 PM] DeckExporter: Creating deck...
[1:43:26 PM] DeckExporter: Done creating deck.
[1:43:44 PM] GameEventHandler: Game start
[1:43:44 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[1:43:44 PM] OpponentSecrets: Cleared secrets
[1:43:44 PM] Game: set CurrentGameMode to None
[1:43:45 PM] GameEventHandler: Opponent-turn (1)
[1:43:45 PM] GameEventHandler: PlayerDraw (id:GVG_022 turn:0 from:-1)
[1:43:45 PM] GameStats: New play: PlayerDraw (GVG_022, turn: 0)
[1:43:45 PM] GameEventHandler: PlayerDraw (id:CS2_074 turn:0 from:-1)
[1:43:45 PM] GameStats: New play: PlayerDraw (CS2_074, turn: 0)
[1:43:45 PM] GameEventHandler: PlayerDraw (id:FP1_030 turn:0 from:-1)
[1:43:45 PM] GameStats: New play: PlayerDraw (FP1_030, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:43:45 PM] Hearthstone: Set card 0 to age 0
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0K,  ,  ,  ,0C,  ,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:43:45 PM] Hearthstone: Set card 1 to age 0
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0K,0K,  ,  ,0C,  ,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:43:45 PM] Hearthstone: Set card 2 to age 0
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,  ,0C,  ,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:43:45 PM] Hearthstone: Set card 3 to age 0
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,0K,0C,  ,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:43:45 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:43:45 PM] Hearthstone: Set card 5 to age 0
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0K,0K,0K,0K,0C,0K,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentMulligan (id: turn:0 from:1)
[1:43:45 PM] Hearthstone: Fixed hand ages after mulligan (removed 5)
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0M,0K,0K,0K,0C, K,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentMulligan (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:43:45 PM] Hearthstone: Set card 5 to age 0
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0M,0K,0K,0K,0C,0K,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentMulligan (id: turn:0 from:2)
[1:43:45 PM] Hearthstone: Fixed hand ages after mulligan (removed 5)
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0K,0K,0C, K,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentMulligan (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[1:43:45 PM] Hearthstone: Set card 5 to age 0
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0K,0K,0C,0K,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentDraw (, turn: 0)
[1:43:45 PM] GameEventHandler: OpponentMulligan (id: turn:0 from:3)
[1:43:45 PM] Hearthstone: Fixed hand ages after mulligan (removed 5)
[1:43:45 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C, K,  ,  ,  ,  
[1:43:45 PM] GameStats: New play: OpponentMulligan (, turn: 0)
[1:43:45 PM] GameEventHandler: Playing against Lord Victor Nefarius
[1:43:45 PM] GameEventHandler: Playing against True Form
[1:43:49 PM] GameEventHandler: set rank to 15
[1:44:07 PM] UpdateOverlay: Refreshed overlay topmost status
[1:44:10 PM] GameEventHandler: PlayerDraw (id:NEW1_026 turn:0 from:-1)
[1:44:10 PM] GameStats: New play: PlayerDraw (NEW1_026, turn: 0)
[1:44:10 PM] GameEventHandler: PlayerMulligan (id:FP1_030 turn:0 from:-1)
[1:44:10 PM] GameStats: New play: PlayerMulligan (FP1_030, turn: 0)
[1:44:10 PM] GameEventHandler: PlayerDraw (id:CS2_077 turn:0 from:-1)
[1:44:10 PM] GameStats: New play: PlayerDraw (CS2_077, turn: 0)
[1:44:10 PM] GameEventHandler: PlayerMulligan (id:GVG_022 turn:0 from:-1)
[1:44:10 PM] GameStats: New play: PlayerMulligan (GVG_022, turn: 0)
[1:44:10 PM] GameEventHandler: PlayerDraw (id:EX1_012 turn:0 from:-1)
[1:44:10 PM] GameStats: New play: PlayerDraw (EX1_012, turn: 0)
[1:44:20 PM] GameEventHandler: OpponentDraw (id: turn:1 from:-1)
[1:44:20 PM] Hearthstone: Set card 5 to age 1
[1:44:20 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,  ,  ,  ,  
[1:44:20 PM] GameStats: New play: OpponentDraw (, turn: 1)
[1:44:20 PM] GameEventHandler: OpponentDraw (id: turn:1 from:-1)
[1:44:20 PM] Hearthstone: Set card 6 to age 1
[1:44:20 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,1 ,  ,  ,  
[1:44:20 PM] GameStats: New play: OpponentDraw (, turn: 1)
[1:44:20 PM] GameEventHandler: OpponentDraw (id: turn:1 from:-1)
[1:44:20 PM] Hearthstone: Set card 7 to age 1
[1:44:20 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,1 ,1 ,  ,  
[1:44:20 PM] GameStats: New play: OpponentDraw (, turn: 1)
[1:44:20 PM] GameEventHandler: Player-turn (2)
[1:44:20 PM] GameEventHandler: PlayerDraw (id:EX1_284 turn:0 from:-1)
[1:44:20 PM] GameStats: New play: PlayerDraw (EX1_284, turn: 1)
[1:44:29 PM] GameEventHandler: Playing against Wild Magic
[1:44:38 PM] GameEventHandler: PlayerPlay (id:EX1_012 turn:0 from:-1)
[1:44:38 PM] GameStats: New play: PlayerPlay (EX1_012, turn: 1)
[1:44:39 PM] GameEventHandler: OpponentDraw (id: turn:2 from:-1)
[1:44:39 PM] Hearthstone: Set card 8 to age 2
[1:44:39 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,1 ,1 ,2 ,  
[1:44:39 PM] GameStats: New play: OpponentDraw (, turn: 2)
[1:44:39 PM] GameEventHandler: OpponentGet (id: turn:2 from:-1)
[1:44:39 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,1 ,1 ,2 ,2S
[1:44:39 PM] GameStats: New play: OpponentGet (, turn: 2)
[1:44:39 PM] GameEventHandler: OpponentPlay (id:CS2_032 turn:2 from:8)
[1:44:39 PM] Hearthstone: (opponent deck) Flamestrike count 0 -> 1
[1:44:39 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,1 ,2 ,2S,  
[1:44:39 PM] GameStats: New play: OpponentPlay (CS2_032, turn: 2)
[1:44:39 PM] GameEventHandler: PlayerDraw (id:EX1_129 turn:0 from:-1)
[1:44:39 PM] GameStats: New play: PlayerDraw (EX1_129, turn: 2)
[1:44:39 PM] GameEventHandler: OpponentPlay (id:NEW1_023 turn:2 from:7)
[1:44:39 PM] Hearthstone: (opponent deck) Faerie Dragon count 0 -> 1
[1:44:39 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,2 ,2S,  ,  
[1:44:39 PM] GameStats: New play: OpponentPlay (NEW1_023, turn: 2)
[1:44:40 PM] GameEventHandler: Player-turn (3)
[1:44:40 PM] GameEventHandler: PlayerDraw (id:EX1_581 turn:0 from:-1)
[1:44:40 PM] GameStats: New play: PlayerDraw (EX1_581, turn: 2)
[1:44:40 PM] GameEventHandler: PlayerGet (id:BRMA13_6 turn:0 from:-1)
[1:44:40 PM] GameStats: New play: PlayerGet (BRMA13_6, turn: 2)
[1:45:01 PM] GameEventHandler: PlayerHeroPower (id:CS2_083b turn:2 from:-1)
[1:45:01 PM] GameStats: New play: PlayerHeroPower (CS2_083b, turn: 2)
[1:45:01 PM] GameEventHandler: PlayerPlay (id:CS2_074 turn:0 from:-1)
[1:45:01 PM] GameStats: New play: PlayerPlay (CS2_074, turn: 2)
[1:45:03 PM] GameEventHandler: OpponentDraw (id: turn:3 from:-1)
[1:45:03 PM] Hearthstone: Set card 8 to age 3
[1:45:03 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,2 ,2S,3 ,  
[1:45:03 PM] GameStats: New play: OpponentDraw (, turn: 3)
[1:45:03 PM] GameEventHandler: OpponentGet (id: turn:3 from:-1)
[1:45:03 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,2 ,2S,3 ,3S
[1:45:03 PM] GameStats: New play: OpponentGet (, turn: 3)
[1:45:03 PM] GameEventHandler: OpponentPlay (id:BRM_024 turn:3 from:9)
[1:45:03 PM] Hearthstone: (opponent deck) Drakonid Crusher count 0 -> 1
[1:45:03 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,1 ,2 ,2S,3S,  
[1:45:03 PM] GameStats: New play: OpponentPlay (BRM_024, turn: 3)
[1:45:03 PM] GameEventHandler: OpponentPlay (id:BRM_033 turn:3 from:6)
[1:45:03 PM] Hearthstone: (opponent deck) Blackwing Technician count 0 -> 1
[1:45:03 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,2 ,2S,3S,  ,  
[1:45:03 PM] GameStats: New play: OpponentPlay (BRM_033, turn: 3)
[1:45:03 PM] GameEventHandler: Player-turn (4)
[1:45:03 PM] GameEventHandler: PlayerDraw (id:GVG_022 turn:0 from:-1)
[1:45:03 PM] GameStats: New play: PlayerDraw (GVG_022, turn: 3)
[1:45:24 PM] GameEventHandler: PlayerPlay (id:BRMA13_6 turn:0 from:-1)
[1:45:24 PM] GameStats: New play: PlayerPlay (BRMA13_6, turn: 3)
[1:45:27 PM] GameEventHandler: PlayerPlay (id:GVG_022 turn:0 from:-1)
[1:45:27 PM] GameStats: New play: PlayerPlay (GVG_022, turn: 3)
[1:45:31 PM] GameEventHandler: OpponentDraw (id: turn:4 from:-1)
[1:45:31 PM] Hearthstone: Set card 8 to age 4
[1:45:31 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,2 ,2S,3S,4 ,  
[1:45:31 PM] GameStats: New play: OpponentDraw (, turn: 4)
[1:45:31 PM] GameEventHandler: OpponentGet (id: turn:4 from:-1)
[1:45:31 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0M,0K,0C,2 ,2S,3S,4 ,4S
[1:45:31 PM] GameStats: New play: OpponentGet (, turn: 4)
[1:45:31 PM] GameEventHandler: OpponentPlay (id:BRM_034 turn:4 from:2)
[1:45:31 PM] Hearthstone: (opponent deck) Blackwing Corruptor count 0 -> 1
[1:45:31 PM] Hearthstone: Opponent Hand after draw: 0M,0M,0K,0C,2 ,2S,3S,4 ,4S,  
[1:45:31 PM] GameStats: New play: OpponentPlay (BRM_034, turn: 4)
[1:45:31 PM] GameEventHandler: OpponentPlay (id:BRM_003 turn:4 from:2)
[1:45:31 PM] Hearthstone: (opponent deck) Dragon's Breath count 0 -> 1
[1:45:31 PM] Hearthstone: Opponent Hand after draw: 0M,0K,0C,2 ,2S,3S,4 ,4S,  ,  
[1:45:31 PM] GameStats: New play: OpponentPlay (BRM_003, turn: 4)
[1:45:31 PM] GameEventHandler: Player-turn (5)
[1:45:31 PM] GameEventHandler: PlayerDraw (id:GVG_022 turn:0 from:-1)
[1:45:31 PM] GameStats: New play: PlayerDraw (GVG_022, turn: 4)
[1:45:54 PM] GameEventHandler: PlayerPlay (id:EX1_284 turn:0 from:-1)
[1:45:54 PM] GameStats: New play: PlayerPlay (EX1_284, turn: 4)
[1:45:54 PM] GameEventHandler: PlayerDraw (id:EX1_129 turn:0 from:-1)
[1:45:54 PM] GameStats: New play: PlayerDraw (EX1_129, turn: 4)
[1:45:56 PM] GameEventHandler: OpponentDraw (id: turn:5 from:-1)
[1:45:56 PM] Hearthstone: Set card 8 to age 5
[1:45:56 PM] Hearthstone: Opponent Hand after draw: 0M,0K,0C,2 ,2S,3S,4 ,4S,5 ,  
[1:45:56 PM] GameStats: New play: OpponentDraw (, turn: 5)
[1:45:56 PM] GameEventHandler: OpponentGet (id: turn:5 from:-1)
[1:45:56 PM] Hearthstone: Opponent Hand after draw: 0M,0K,0C,2 ,2S,3S,4 ,4S,5 ,5S
[1:45:56 PM] GameStats: New play: OpponentGet (, turn: 5)
[1:45:56 PM] GameEventHandler: OpponentPlay (id:EX1_581 turn:5 from:10)
[1:45:56 PM] Hearthstone: (opponent deck) Sap count 0 -> 1
[1:45:56 PM] Game: Opponent played stolen card from 10
[1:45:56 PM] Hearthstone: Opponent Hand after draw: 0M,0K,0C,2 ,2S,3S,4 ,4S,5 ,  
[1:45:56 PM] GameStats: New play: OpponentPlay (EX1_581, turn: 5)
[1:45:56 PM] GameEventHandler: PlayerBackToHand (id:EX1_284 turn:0 from:-1)
[1:45:56 PM] GameStats: New play: PlayerBackToHand (EX1_284, turn: 5)
[1:45:56 PM] GameEventHandler: OpponentPlay (id:BRM_024 turn:5 from:7)
[1:45:56 PM] Hearthstone: (opponent deck) Drakonid Crusher count 1 -> 2
[1:45:56 PM] Hearthstone: Opponent Hand after draw: 0M,0K,0C,2 ,2S,3S,4S,5 ,  ,  
[1:45:56 PM] GameStats: New play: OpponentPlay (BRM_024, turn: 5)
[1:45:56 PM] GameEventHandler: OpponentPlay (id:CS2_005 turn:5 from:1)
[1:45:56 PM] Hearthstone: (opponent deck) Claw count 0 -> 1
[1:45:56 PM] Hearthstone: Opponent Hand after draw: 0K,0C,2 ,2S,3S,4S,5 ,  ,  ,  
[1:45:56 PM] GameStats: New play: OpponentPlay (CS2_005, turn: 5)
[1:45:56 PM] GameEventHandler: Player-turn (6)
[1:45:56 PM] GameEventHandler: PlayerDraw (id:CS2_233 turn:0 from:-1)
[1:45:56 PM] GameStats: New play: PlayerDraw (CS2_233, turn: 5)
[1:47:12 PM] GameEventHandler: PlayerPlay (id:EX1_581 turn:0 from:-1)
[1:47:12 PM] GameStats: New play: PlayerPlay (EX1_581, turn: 5)
[1:47:12 PM] GameEventHandler: OpponentBackToHand (id:BRM_024 turn:5 from:-1)
[1:47:12 PM] Hearthstone: (opponent deck) Drakonid Crusher count 2 -> 1
[1:47:12 PM] GameStats: New play: OpponentBackToHand (BRM_024, turn: 5)
[1:47:16 PM] GameEventHandler: OpponentDraw (id: turn:6 from:-1)
[1:47:16 PM] Hearthstone: Set card 8 to age 6
[1:47:16 PM] Hearthstone: Opponent Hand after draw: 0K,0C,2 ,2S,3S,4S,5 ,5R,6 ,  
[1:47:16 PM] GameStats: New play: OpponentDraw (, turn: 6)
[1:47:16 PM] GameEventHandler: OpponentGet (id: turn:6 from:-1)
[1:47:16 PM] Hearthstone: Opponent Hand after draw: 0K,0C,2 ,2S,3S,4S,5 ,5R,6 ,6S
[1:47:16 PM] GameStats: New play: OpponentGet (, turn: 6)
[1:47:16 PM] GameEventHandler: OpponentPlay (id:BRM_024 turn:6 from:8)
[1:47:16 PM] Hearthstone: (opponent deck) Drakonid Crusher count 0 -> 1
[1:47:16 PM] Game: Opponent played stolen card from 8
[1:47:16 PM] Hearthstone: Opponent Hand after draw: 0K,0C,2 ,2S,3S,4S,5 ,6 ,6S,  
[1:47:16 PM] GameStats: New play: OpponentPlay (BRM_024, turn: 6)
[1:47:16 PM] GameEventHandler: OpponentPlay (id:GAME_005 turn:6 from:2)
[1:47:16 PM] Hearthstone: (opponent deck) The Coin count 0 -> 1
[1:47:16 PM] Hearthstone: Opponent Hand after draw: 0K,2 ,2S,3S,4S,5 ,6 ,6S,  ,  
[1:47:16 PM] GameStats: New play: OpponentPlay (GAME_005, turn: 6)
[1:47:16 PM] GameEventHandler: OpponentPlay (id:BRM_026 turn:6 from:7)
[1:47:16 PM] Hearthstone: (opponent deck) Hungry Dragon count 0 -> 1
[1:47:16 PM] Hearthstone: Opponent Hand after draw: 0K,2 ,2S,3S,4S,5 ,6S,  ,  ,  
[1:47:16 PM] GameStats: New play: OpponentPlay (BRM_026, turn: 6)
[1:47:16 PM] GameEventHandler: Player-turn (7)
[1:47:16 PM] GameEventHandler: PlayerDraw (id:CS2_117 turn:0 from:-1)
[1:47:16 PM] GameStats: New play: PlayerDraw (CS2_117, turn: 6)
[1:48:10 PM] GameEventHandler: PlayerPlay (id:EX1_284 turn:0 from:-1)
[1:48:10 PM] GameStats: New play: PlayerPlay (EX1_284, turn: 6)
[1:48:10 PM] GameEventHandler: PlayerDraw (id:EX1_124 turn:0 from:-1)
[1:48:10 PM] GameStats: New play: PlayerDraw (EX1_124, turn: 6)

**Comment by Epix37** [comment]
`[1:39:38 PM] Helper: Current version: 0.9.10.0` 

Does this still happen with the latest update ?
