### ISSUE TITLE
Syncing never completes

### ISSUE THREAD

**Issue by ghostbirdd** [Epix37/Hearthstone-Deck-Tracker#923]
When I select to sync with hearthstats, it just continues forever if I already have decks in the tracker.

Tried deleting all decks in tracker, then do full sync, and that works, and continues to work until I add a deck to hearthstats, then it's back to syncing forever.

**Comment by Epix37** [comment]
Possibly a problem with the hearthstats servers? Not sure...

Could you try again and after upload the log, found in "%AppData%/HearthstoneDeckTracker/Logs"? (WIn+R, paste)

**Comment by jemiller226** [comment]
I have the same problem. Also, Issue #884 is not fixed. See my update to that ticket.

**Comment by Epix37** [comment]
How does that work? Doesn't the syncing have to complete for you to have the other issue?

Also, please do post a log for this issue.

**Comment by jemiller226** [comment]
Good question! :)

I have this problem when I have synced once and try to re-sync to see if it picked up missing deck versions. This is where it hangs as far as I can tell:

[5:53:33 PM] Load: Copied log.config to C:\Users\Administrator\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[5:53:33 PM] Game: set CurrentGameMode to None
[5:53:33 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[5:53:33 PM] OpponentSecrets: Cleared secrets
[5:53:34 PM] Tracker: Set player itemsource as PlayerDeck
[5:53:34 PM] Tracker: Switched to deck: Dubbel Chow-Rag Druid
[5:53:34 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[5:53:34 PM] OpponentSecrets: Cleared secrets
[5:53:35 PM] Helper: Checking for updates...
[5:53:35 PM] Helper: Current version: 0.10.0.0
[5:53:35 PM] BackupManager: Running BackupManager
[5:53:35 PM] BackupManager: Creating backup for today
[5:53:35 PM] PluginManager: Loading Plugins...
[5:53:35 PM] Helper: Latest version: 0.10.0.0
[5:54:31 PM] HearthStatsManager: starting sync process: forceFullSync=True, background=False
[5:54:31 PM] HearthStatsManager: Checking HearthStats for new decks...
[5:54:31 PM] HearthStatsManager: trying to download decks
[5:54:31 PM] HearthStatsAPI: getting decks since 0
[5:54:35 PM] HearthStatsAPI: error converting DeckObject: System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.HearthStats.API.Objects.DeckObject.ToDeck(CardObject[] cards, String[] rawTags, DeckVersion[] versions, String version)
[5:54:36 PM] HearthStatsManager: There was an error syncing with HearthStats:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsManager.<>c__DisplayClass22.<SyncAsync>b__40(Deck localDeck)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsManager.<>c__DisplayClass21.<SyncAsync>b__38(Deck deck)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Hearthstone_Deck_Tracker.HearthStats.API.HearthStatsManager.<SyncAsync>d__1.MoveNext()

**Comment by Epix37** [comment]
This (at least in your case) seems to be the same problem causing it as in #884.

**Comment by jemiller226** [comment]
Yeah, I was thinking that. I hate to assume they're related, but those logs sure do look similar.

**Comment by Elitesparkle** [comment]
@Epix37, could I add a "Cancel" button and a "Retry" button so we could cancel the import or update of a given deck and try again?
It could be useful in those cases.
