### ISSUE TITLE
Crashed while attempting to view replay

### ISSUE THREAD

**Issue by VicTT** [Epix37/Hearthstone-Deck-Tracker#944]
########## 06.05.2015 12:21:06 PM ##########
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.Replay.ReplayViewer.get_PlayerEntity()
   at Hearthstone_Deck_Tracker.Replay.ReplayViewer.Load(List`1 replay)
   at Hearthstone_Deck_Tracker.Replay.ReplayReader.Read(String fileName)
   at Hearthstone_Deck_Tracker.DeckStatsControl.OpenGameDetails(GameStats selected)
   at Hearthstone_Deck_Tracker.DeckStatsControl.BtnOverallDetails_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[12:20:35 PM] Load: Copied log.config to C:\Users\VicTT_Acer\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[12:20:35 PM] Game: set CurrentGameMode to None
[12:20:36 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:20:36 PM] OpponentSecrets: Cleared secrets
[12:20:36 PM] Tracker: set player item source to PlayerDrawn
[12:20:36 PM] Tracker: Deselected deck
[12:20:36 PM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:20:36 PM] OpponentSecrets: Cleared secrets
[12:20:38 PM] Helper: Checking for updates...
[12:20:38 PM] Helper: Current version: 0.10.0.0
[12:20:41 PM] LogReader: Current region: EU
[12:20:41 PM] UpdateOverlay: Refreshed overlay topmost status
[12:20:41 PM] BackupManager: Running BackupManager
[12:20:41 PM] BackupManager: Deleting old backup: Backup_28042015.zip
[12:20:41 PM] BackupManager: Backup for today already exists
[12:20:41 PM] Game: set CurrentGameMode to Spectator
[12:20:43 PM] Helper: Latest version: 0.10.0.0
[12:20:44 PM] UpdateOverlay: Refreshed overlay topmost status

It was a spectated game. I am linking you one of the games for which it crashed (there are 3 and the crash reports are the same).
https://www.wetransfer.com/downloads/ab965f1efaa488ec30920ef482ba7baa20150506092942/21bb236cc089f0223f7ea4e7d9b7200c20150506092942/6e8488
Any chance the really old bug of every opponent's card in a spectated game having the index=-1 gets fixed soon?

**Comment by Epix37** [comment]
Fixed with 0012166. 

The -1 bug... To be completely honest it's probably gonna stay like that for a while. Not very high up on the priority list and requires most likely a decent amount of work to figure out.
