### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by DrW13** [Epix37/Hearthstone-Deck-Tracker#982]
Just recently got a new computer with Windows 8 unfortunately. Here is the message:

########## 5/21/2015 6:30:22 PM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.HandlePossibleConstructedCard(String id, Boolean canBeDoneImporting)
   at Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   at Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

any help would be greatly appreciated. Used this program flawlessly before on my old computer.

**Comment by Epix37** [comment]
Should be fine after just restarting hearthstone.
